// Generic loomi component style build. Identical across component packages.
// Compiles Tailwind utilities ONCE at build time and inlines the result into
// `src/generated/styles.css.ts` (a Lit CSSResult). Colors resolve through the
// overridable `--<prefix>-*` slots (never hardcoded hex); runtime-interpolated
// class names are emitted via a safelist.

import { createRequire } from "node:module";
import { spawnSync } from "node:child_process";
import {
  readFileSync,
  writeFileSync,
  mkdirSync,
  rmSync,
  existsSync,
} from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const require = createRequire(import.meta.url);
const __dirname = dirname(fileURLToPath(import.meta.url));
const pkgRoot = resolve(__dirname, "..");

const palette = JSON.parse(
  readFileSync(require.resolve("@loomidev/theme/palette.json"), "utf8"),
);
const { colors, shades } = palette;
const prefix = palette.prefix ?? "loomi";

const colorMap = [];
for (const color of colors) {
  for (const shade of shades) {
    colorMap.push(
      `  --color-${color}-${shade}: var(--${prefix}-${color}-${shade}, var(--_${prefix}-${color}-${shade}-default));`,
    );
  }
}

let passthrough = readFileSync(resolve(pkgRoot, "src/styles.css"), "utf8");

const colorRe = new RegExp(
  `var\\(--${prefix}-(${colors.join("|")})-(\\d{2,3})\\)`,
  "g",
);
passthrough = passthrough.replace(
  colorRe,
  (_m, c, s) => `var(--${prefix}-${c}-${s}, var(--_${prefix}-${c}-${s}-default))`,
);

const input = `@layer theme, base, components, utilities;
@import "tailwindcss/theme.css" layer(theme);
@import "tailwindcss/utilities.css" layer(utilities);

@theme inline {
${colorMap.join("\n")}
}

@source "./src/**/*.ts";
@source not "./src/generated/**/*";

/* ---- component-scoped plain CSS (passed through untouched) ---- */
${passthrough}
`;

const inputPath = resolve(pkgRoot, ".loomi-tw-input.css");
const outputPath = resolve(pkgRoot, ".loomi-tw-output.css");
writeFileSync(inputPath, input);

const cliPkgJson = require.resolve("@tailwindcss/cli/package.json");
const cliDir = dirname(cliPkgJson);
const cliManifest = JSON.parse(readFileSync(cliPkgJson, "utf8"));
const binRel =
  typeof cliManifest.bin === "string"
    ? cliManifest.bin
    : cliManifest.bin.tailwindcss;
const cliEntry = resolve(cliDir, binRel);

const result = spawnSync(
  process.execPath,
  [cliEntry, "--input", inputPath, "--output", outputPath, "--minify"],
  { cwd: pkgRoot, stdio: ["ignore", "inherit", "inherit"] },
);

if (result.status !== 0) {
  rmSync(inputPath, { force: true });
  throw new Error(`Tailwind CLI failed with exit code ${result.status}`);
}

const compiled = readFileSync(outputPath, "utf8").trim();

const pkgName = JSON.parse(
  readFileSync(resolve(pkgRoot, "package.json"), "utf8"),
).name;

const generated = `// Generated by ${pkgName} — do not edit by hand. Run \`pnpm build\` to regenerate.
import { unsafeCSS } from "lit";

/** Compiled, Shadow-DOM-scoped styles. Colors resolve via \`var(--${prefix}-*)\`. */
export const componentStyles = unsafeCSS(${JSON.stringify(compiled)});
`;

mkdirSync(resolve(pkgRoot, "src/generated"), { recursive: true });
writeFileSync(resolve(pkgRoot, "src/generated/styles.css.ts"), generated);

rmSync(inputPath, { force: true });
if (existsSync(outputPath)) rmSync(outputPath, { force: true });

console.log(
  `Built styles for ${pkgName} -> src/generated/styles.css.ts (${compiled.length} chars)`,
);
