// Generic loomi default-image build. Inlines the package's built-in
// illustration as a base64 data URI into `src/generated/default-image.ts`,
// so the component ships the image with no separate asset-loading step and
// no dependency on a consumer's bundler to resolve a static file path.
//
// To swap the built-in illustration, replace `src/assets/default-image.png`
// with a same-named PNG and rebuild — no code changes needed.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const pkgRoot = resolve(__dirname, "..");

const assetPath = resolve(pkgRoot, "src/assets/default-image.png");
const base64 = readFileSync(assetPath).toString("base64");

const pkgName = JSON.parse(
  readFileSync(resolve(pkgRoot, "package.json"), "utf8"),
).name;

const generated = `// Generated by ${pkgName} — do not edit by hand. Run \`pnpm build\` to regenerate.
// Source image: src/assets/default-image.png — replace that file (same name)
// and rebuild to change the built-in illustration.

/** Built-in empty-state illustration, inlined as a data URI. */
export const DEFAULT_IMAGE = "data:image/png;base64,${base64}";
`;

mkdirSync(resolve(pkgRoot, "src/generated"), { recursive: true });
writeFileSync(resolve(pkgRoot, "src/generated/default-image.ts"), generated);

console.log(
  `[${pkgName}] inlined default image (${(base64.length / 1024).toFixed(1)} kB base64).`,
);
