/**
 * Representative markup for every custom element the library defines — the single source
 * of truth shared by the accessibility sweep (`a11y.test.ts`), the visual regression
 * suite (`visual/components.spec.mjs`) and `scripts/check-a11y-coverage.mjs`.
 *
 * Each entry is `[tag, markup]`. `null` markup means the element renders bare, which is
 * only correct for components that are already meaningful with no attributes or content.
 * Everything else gets markup representing **correct, realistic use** — a form control
 * with its label, a menu item inside its menu, a button with a name. A bare
 * `<loomi-input>` legitimately has no accessible name and renders as an empty box, so
 * asserting on it would measure the fixture rather than the component.
 *
 * Keep this list exhaustive: `pnpm check:a11y-coverage` fails if a tag declared in any
 * custom-elements.json is missing, so a new component cannot silently skip either suite.
 */
export const CASES = [
  ["loomi-accordion", null],
  [
    "loomi-accordion-item",
    '<loomi-accordion><loomi-accordion-item title="Section">Body</loomi-accordion-item></loomi-accordion>',
  ],
  ["loomi-alert", null],
  ["loomi-arc-meter", null],
  ["loomi-autocomplete", null],
  ["loomi-avatar", null],
  ["loomi-avatars", null],
  ["loomi-bell", null],
  ["loomi-bottom-nav", null],
  [
    "loomi-bottom-nav-item",
    '<loomi-bottom-nav><loomi-bottom-nav-item label="Home"></loomi-bottom-nav-item></loomi-bottom-nav>',
  ],
  ["loomi-button", "<loomi-button>Save</loomi-button>"],
  ["loomi-button-group", null],
  [
    "loomi-button-group-item",
    '<loomi-button-group aria-label="Views"><loomi-button-group-item label="List"></loomi-button-group-item></loomi-button-group>',
  ],
  ["loomi-calendar", null],
  ["loomi-card", null],
  ["loomi-card-action", null],
  ["loomi-card-content", null],
  ["loomi-card-description", null],
  ["loomi-card-footer", null],
  ["loomi-card-header", null],
  ["loomi-card-title", null],
  ["loomi-centered-content", null],
  ["loomi-chart", null],
  ["loomi-chat-message", null],
  ["loomi-chat-window", null],
  ["loomi-checkbox", '<loomi-checkbox label="Accept terms"></loomi-checkbox>'],
  [
    "loomi-checkcard",
    '<loomi-checkcards><loomi-checkcard value="pro" title="Pro plan"></loomi-checkcard></loomi-checkcards>',
  ],
  ["loomi-checkcards", null],
  ["loomi-clipboard", null],
  ["loomi-colorpicker", null],
  ["loomi-command-palette", null],
  ["loomi-contact-card", null],
  [
    "loomi-context-menu",
    '<loomi-context-menu><span slot="target">Right-click me</span><loomi-context-menu-item>Copy</loomi-context-menu-item></loomi-context-menu>',
  ],
  [
    "loomi-context-menu-item",
    '<loomi-context-menu><span slot="target">Right-click me</span><loomi-context-menu-item>Copy</loomi-context-menu-item></loomi-context-menu>',
  ],
  ["loomi-countries", null],
  ["loomi-creditcard", null],
  ["loomi-data-grid", null],
  ["loomi-date-range-picker", null],
  ["loomi-datepicker", null],
  ["loomi-divider", null],
  ["loomi-drawer", null],
  [
    "loomi-dropmenu",
    '<loomi-dropmenu label="Actions"><loomi-dropmenu-item>Edit</loomi-dropmenu-item></loomi-dropmenu>',
  ],
  [
    "loomi-dropmenu-item",
    '<loomi-dropmenu label="Actions"><loomi-dropmenu-item>Edit</loomi-dropmenu-item></loomi-dropmenu>',
  ],
  ["loomi-emoji-picker", null],
  ["loomi-empty-state", null],
  ["loomi-fab", null],
  [
    "loomi-fab-item",
    '<loomi-fab label="Actions"><loomi-fab-item label="New file"></loomi-fab-item></loomi-fab>',
  ],
  ["loomi-filepicker", null],
  ["loomi-filter-builder", null],
  ["loomi-floating-panel", null],
  ["loomi-horizontal-line-graph", null],
  ["loomi-icon", null],
  ["loomi-input", '<loomi-input label="Full name"></loomi-input>'],
  ["loomi-lightbox-image", null],
  ["loomi-listview", null],
  [
    "loomi-listview-item",
    "<loomi-listview><loomi-listview-item>Row one</loomi-listview-item></loomi-listview>",
  ],
  ["loomi-modal", null],
  ["loomi-notification", null],
  ["loomi-number", '<loomi-number label="Quantity"></loomi-number>'],
  ["loomi-otp", null],
  ["loomi-pagination", null],
  ["loomi-password", '<loomi-password label="Password"></loomi-password>'],
  ["loomi-photo-gallery", null],
  ["loomi-photo-gallery-item", null],
  [
    "loomi-popover",
    '<loomi-popover title="Details"><span slot="trigger">Open</span>Body text</loomi-popover>',
  ],
  ["loomi-processing", null],
  ["loomi-profile-menu", null],
  ["loomi-progress-bar", null],
  ["loomi-progress-circle", null],
  [
    "loomi-progress-step",
    '<loomi-progress-steps><loomi-progress-step label="Details"></loomi-progress-step></loomi-progress-steps>',
  ],
  ["loomi-progress-steps", null],
  ["loomi-qrcode", null],
  ["loomi-radio", '<loomi-radio label="Standard shipping"></loomi-radio>'],
  ["loomi-rating", null],
  ["loomi-resizable-handle", null],
  ["loomi-resizable-panel", null],
  ["loomi-resizable-panel-group", null],
  ["loomi-scroller", null],
  ["loomi-select", null],
  ["loomi-side-nav", null],
  [
    "loomi-side-nav-item",
    '<loomi-side-nav label="Main"><loomi-side-nav-item label="Dashboard"></loomi-side-nav-item></loomi-side-nav>',
  ],
  ["loomi-slider", null],
  ["loomi-sortable", null],
  ["loomi-spinner", null],
  ["loomi-split-button", '<loomi-split-button menu-label="More actions">Save</loomi-split-button>'],
  ["loomi-statistic", null],
  ["loomi-tab", null],
  ["loomi-table", null],
  ["loomi-tabs", null],
  ["loomi-tag", null],
  ["loomi-tag-input", '<loomi-tag-input label="Tags"></loomi-tag-input>'],
  ["loomi-tags", null],
  ["loomi-text-editor", null],
  ["loomi-textarea", '<loomi-textarea label="Message"></loomi-textarea>'],
  ["loomi-theme-switcher", null],
  ["loomi-timeline", null],
  ["loomi-timeline-item", null],
  ["loomi-timepicker", null],
  ["loomi-timer", null],
  ["loomi-timezonepicker", null],
  ["loomi-toggle", '<loomi-toggle label="Email notifications"></loomi-toggle>'],
  ["loomi-tooltip", '<loomi-tooltip content="Saves your work">Save</loomi-tooltip>'],
  ["loomi-video", null],
];
