// Generic loomi component style build. Compiles Tailwind utilities ONCE at build
// time and inlines the result into `src/generated/styles.css.ts` (a Lit CSSResult).
// Colors resolve through overridable `--<prefix>-*` CSS custom properties (never
// hardcoded hex); component-scoped plain CSS is passed through untouched.

import { createRequire } from "node:module";
import { spawnSync } from "node:child_process";
import {
  readFileSync,
  writeFileSync,
  mkdirSync,
  rmSync,
  existsSync,
  readdirSync,
} from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const require = createRequire(import.meta.url);
const __dirname = dirname(fileURLToPath(import.meta.url));
const pkgRoot = resolve(__dirname, "..");
const workspaceRoot = resolve(pkgRoot, "../..");

const palette = JSON.parse(
  readFileSync(
    existsSync(resolve(workspaceRoot, "packages/theme/palette.json"))
      ? resolve(workspaceRoot, "packages/theme/palette.json")
      : require.resolve("@loomidev/theme/palette.json"),
    "utf8",
  ),
);
const { colors, shades } = palette;
const prefix = palette.prefix ?? "loomi";

const colorMap = [];
for (const color of colors) {
  for (const shade of shades) {
    colorMap.push(
      `  --color-${color}-${shade}: var(--${prefix}-${color}-${shade}, var(--_${prefix}-${color}-${shade}-default));`,
    );
  }
}

let passthrough = readFileSync(resolve(pkgRoot, "src/styles.css"), "utf8");

const colorRe = new RegExp(
  `var\\(--${prefix}-(${colors.join("|")})-(\\d{2,3})\\)`,
  "g",
);
passthrough = passthrough.replace(
  colorRe,
  (_m, c, s) => `var(--${prefix}-${c}-${s}, var(--_${prefix}-${c}-${s}-default))`,
);

function resolveTailwindCssFile(fileName) {
  try {
    return require.resolve(`tailwindcss/${fileName}`);
  } catch {
    const pnpmDir = resolve(workspaceRoot, "node_modules/.pnpm");
    const cssEntryDir = existsSync(pnpmDir)
      ? readdirSync(pnpmDir).find((entry) => entry.startsWith("tailwindcss@"))
      : undefined;
    if (cssEntryDir) {
      const candidate = resolve(pnpmDir, cssEntryDir, "node_modules/tailwindcss", fileName);
      if (existsSync(candidate)) return candidate;
    }
    throw new Error(`Cannot resolve tailwindcss/${fileName}`);
  }
}

const tailwindThemeCss = resolveTailwindCssFile("theme.css");
const tailwindUtilitiesCss = resolveTailwindCssFile("utilities.css");

const input = `@layer theme, base, components, utilities;
@import ${JSON.stringify(tailwindThemeCss)} layer(theme);
@import ${JSON.stringify(tailwindUtilitiesCss)} layer(utilities);

@theme inline {
${colorMap.join("\n")}
}


${passthrough}
`;

const inputPath = resolve(pkgRoot, ".loomi-tw-input.css");
const outputPath = resolve(pkgRoot, ".loomi-tw-output.css");
writeFileSync(inputPath, input);

function resolveTailwindCliPackageJson() {
  try {
    return require.resolve("@tailwindcss/cli/package.json");
  } catch {
    const pnpmDir = resolve(workspaceRoot, "node_modules/.pnpm");
    const cliEntryDir = existsSync(pnpmDir)
      ? readdirSync(pnpmDir).find((entry) => entry.startsWith("@tailwindcss+cli@"))
      : undefined;
    if (cliEntryDir) {
      const candidate = resolve(pnpmDir, cliEntryDir, "node_modules/@tailwindcss/cli/package.json");
      if (existsSync(candidate)) return candidate;
    }
    throw new Error("Cannot resolve @tailwindcss/cli/package.json");
  }
}

const cliPkgJson = resolveTailwindCliPackageJson();
const cliDir = dirname(cliPkgJson);
const cliManifest = JSON.parse(readFileSync(cliPkgJson, "utf8"));
const binRel =
  typeof cliManifest.bin === "string"
    ? cliManifest.bin
    : cliManifest.bin.tailwindcss;
const cliEntry = resolve(cliDir, binRel);

const result = spawnSync(
  process.execPath,
  [cliEntry, "--input", inputPath, "--output", outputPath, "--minify"],
  { cwd: pkgRoot, stdio: ["ignore", "inherit", "inherit"] },
);

if (result.status !== 0) {
  rmSync(inputPath, { force: true });
  throw new Error(`Tailwind CLI failed with exit code ${result.status}`);
}

const compiled = readFileSync(outputPath, "utf8").trim();

const pkgName = JSON.parse(
  readFileSync(resolve(pkgRoot, "package.json"), "utf8"),
).name;

const generated = `// Generated by ${pkgName} — do not edit by hand. Run \`pnpm build\` to regenerate.
import { unsafeCSS } from "lit";

/** Compiled, Shadow-DOM-scoped styles. Colors resolve via \`var(--${prefix}-*)\`. */
export const componentStyles = unsafeCSS(${JSON.stringify(compiled)});
`;

mkdirSync(resolve(pkgRoot, "src/generated"), { recursive: true });
writeFileSync(resolve(pkgRoot, "src/generated/styles.css.ts"), generated);

rmSync(inputPath, { force: true });
if (existsSync(outputPath)) rmSync(outputPath, { force: true });

console.log(
  `[${pkgName}] compiled styles (${(compiled.length / 1024).toFixed(1)} kB).`,
);
