// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import { createComponent } from "./create-component.js";

import "@loomidev/components/accordion";
import "@loomidev/components/alert";
import "@loomidev/components/arc-meter";
import "@loomidev/components/autocomplete";
import "@loomidev/components/avatar";
import "@loomidev/components/bell";
import "@loomidev/components/bottom-nav";
import "@loomidev/components/button";
import "@loomidev/components/button-group";
import "@loomidev/components/calendar";
import "@loomidev/components/card";
import "@loomidev/components/centered-content";
import "@loomidev/components/chart";
import "@loomidev/components/chat";
import "@loomidev/components/checkbox";
import "@loomidev/components/checkcards";
import "@loomidev/components/clipboard";
import "@loomidev/components/colorpicker";
import "@loomidev/components/command-palette";
import "@loomidev/components/contact-card";
import "@loomidev/components/context-menu";
import "@loomidev/components/countries";
import "@loomidev/components/creditcard";
import "@loomidev/components/data-grid";
import "@loomidev/components/date-range-picker";
import "@loomidev/components/datepicker";
import "@loomidev/components/divider";
import "@loomidev/components/drawer";
import "@loomidev/components/dropmenu";
import "@loomidev/components/emoji-picker";
import "@loomidev/components/empty-state";
import "@loomidev/components/fab";
import "@loomidev/components/filepicker";
import "@loomidev/components/filter-builder";
import "@loomidev/components/floating-panel";
import "@loomidev/components/horizontal-line-graph";
import "@loomidev/components/icon";
import "@loomidev/components/input";
import "@loomidev/components/lightbox";
import "@loomidev/components/listview";
import "@loomidev/components/modal";
import "@loomidev/components/notification";
import "@loomidev/components/number";
import "@loomidev/components/otp";
import "@loomidev/components/pagination";
import "@loomidev/components/password";
import "@loomidev/components/photo-gallery";
import "@loomidev/components/popover";
import "@loomidev/components/processing";
import "@loomidev/components/profile-menu";
import "@loomidev/components/progress";
import "@loomidev/components/qrcode";
import "@loomidev/components/radio";
import "@loomidev/components/rating";
import "@loomidev/components/resizable";
import "@loomidev/components/scroller";
import "@loomidev/components/select";
import "@loomidev/components/side-nav";
import "@loomidev/components/slider";
import "@loomidev/components/sortable";
import "@loomidev/components/spinner";
import "@loomidev/components/split-button";
import "@loomidev/components/statistic";
import "@loomidev/components/tab";
import "@loomidev/components/table";
import "@loomidev/components/tag";
import "@loomidev/components/tag-input";
import "@loomidev/components/text-editor";
import "@loomidev/components/textarea";
import "@loomidev/components/theme-switcher";
import "@loomidev/components/timeline";
import "@loomidev/components/timepicker";
import "@loomidev/components/timer";
import "@loomidev/components/timezonepicker";
import "@loomidev/components/toggle";
import "@loomidev/components/tooltip";
import "@loomidev/components/video";

export const Accordion: ForwardRefExoticComponent<JSX.IntrinsicElements["loomi-accordion"]> =
  createComponent("loomi-accordion", {}) as unknown as ForwardRefExoticComponent<
    JSX.IntrinsicElements["loomi-accordion"]
  >;

export const AccordionItem: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-accordion-item"], "onLoomiAccordionToggle"> & {
    onLoomiAccordionToggle?: (e: Event) => void;
  }
> = createComponent("loomi-accordion-item", {
  "loomi-accordion-toggle": "onLoomiAccordionToggle",
}) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-accordion-item"], "onLoomiAccordionToggle"> & {
    onLoomiAccordionToggle?: (e: Event) => void;
  }
>;

export const Alert: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-alert"], "onClose"> & {
    onClose?: (e: Event) => void;
  }
> = createComponent("loomi-alert", { close: "onClose" }) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-alert"], "onClose"> & {
    onClose?: (e: Event) => void;
  }
>;

export const ArcMeter: ForwardRefExoticComponent<JSX.IntrinsicElements["loomi-arc-meter"]> =
  createComponent("loomi-arc-meter", {}) as unknown as ForwardRefExoticComponent<
    JSX.IntrinsicElements["loomi-arc-meter"]
  >;

export const Autocomplete: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-autocomplete"], "onInput" | "onChange" | "onLoomiSelect"> & {
    onInput?: (e: Event) => void;
    onChange?: (e: Event) => void;
    onLoomiSelect?: (e: Event) => void;
  }
> = createComponent("loomi-autocomplete", {
  input: "onInput",
  change: "onChange",
  "loomi-select": "onLoomiSelect",
}) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-autocomplete"], "onInput" | "onChange" | "onLoomiSelect"> & {
    onInput?: (e: Event) => void;
    onChange?: (e: Event) => void;
    onLoomiSelect?: (e: Event) => void;
  }
>;

export const Avatar: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-avatar"], "onChange"> & {
    onChange?: (e: Event) => void;
  }
> = createComponent("loomi-avatar", { change: "onChange" }) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-avatar"], "onChange"> & {
    onChange?: (e: Event) => void;
  }
>;

export const Avatars: ForwardRefExoticComponent<JSX.IntrinsicElements["loomi-avatars"]> =
  createComponent("loomi-avatars", {}) as unknown as ForwardRefExoticComponent<
    JSX.IntrinsicElements["loomi-avatars"]
  >;

export const Bell: ForwardRefExoticComponent<JSX.IntrinsicElements["loomi-bell"]> = createComponent(
  "loomi-bell",
  {},
) as unknown as ForwardRefExoticComponent<JSX.IntrinsicElements["loomi-bell"]>;

export const BottomNav: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-bottom-nav"], "onLoomiChange"> & {
    onLoomiChange?: (e: Event) => void;
  }
> = createComponent("loomi-bottom-nav", {
  "loomi-change": "onLoomiChange",
}) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-bottom-nav"], "onLoomiChange"> & {
    onLoomiChange?: (e: Event) => void;
  }
>;

export const BottomNavItem: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-bottom-nav-item"], "onLoomiChange"> & {
    onLoomiChange?: (e: Event) => void;
  }
> = createComponent("loomi-bottom-nav-item", {
  "loomi-change": "onLoomiChange",
}) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-bottom-nav-item"], "onLoomiChange"> & {
    onLoomiChange?: (e: Event) => void;
  }
>;

export const Button: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-button"], "onClick"> & {
    onClick?: (e: Event) => void;
  }
> = createComponent("loomi-button", { click: "onClick" }) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-button"], "onClick"> & {
    onClick?: (e: Event) => void;
  }
>;

export const ButtonGroup: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-button-group"], "onLoomiButtonGroupChange"> & {
    onLoomiButtonGroupChange?: (e: Event) => void;
  }
> = createComponent("loomi-button-group", {
  "loomi-button-group-change": "onLoomiButtonGroupChange",
}) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-button-group"], "onLoomiButtonGroupChange"> & {
    onLoomiButtonGroupChange?: (e: Event) => void;
  }
>;

export const ButtonGroupItem: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-button-group-item"], "onLoomiBgClick"> & {
    onLoomiBgClick?: (e: Event) => void;
  }
> = createComponent("loomi-button-group-item", {
  "loomi-bg-click": "onLoomiBgClick",
}) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-button-group-item"], "onLoomiBgClick"> & {
    onLoomiBgClick?: (e: Event) => void;
  }
>;

export const Calendar: ForwardRefExoticComponent<
  Omit<
    JSX.IntrinsicElements["loomi-calendar"],
    | "onLoomiEventChange"
    | "onLoomiSlotSelect"
    | "onLoomiEventClick"
    | "onLoomiReminderClick"
    | "onLoomiViewChange"
    | "onLoomiDateChange"
    | "onLoomiSidebarToggle"
    | "onLoomiEventCreate"
    | "onLoomiEventDelete"
    | "onLoomiReminderChange"
    | "onLoomiReminderDelete"
    | "onLoomiEventDuplicate"
  > & {
    onLoomiEventChange?: (e: Event) => void;
    onLoomiSlotSelect?: (e: Event) => void;
    onLoomiEventClick?: (e: Event) => void;
    onLoomiReminderClick?: (e: Event) => void;
    onLoomiViewChange?: (e: Event) => void;
    onLoomiDateChange?: (e: Event) => void;
    onLoomiSidebarToggle?: (e: Event) => void;
    onLoomiEventCreate?: (e: Event) => void;
    onLoomiEventDelete?: (e: Event) => void;
    onLoomiReminderChange?: (e: Event) => void;
    onLoomiReminderDelete?: (e: Event) => void;
    onLoomiEventDuplicate?: (e: Event) => void;
  }
> = createComponent("loomi-calendar", {
  "loomi-event-change": "onLoomiEventChange",
  "loomi-slot-select": "onLoomiSlotSelect",
  "loomi-event-click": "onLoomiEventClick",
  "loomi-reminder-click": "onLoomiReminderClick",
  "loomi-view-change": "onLoomiViewChange",
  "loomi-date-change": "onLoomiDateChange",
  "loomi-sidebar-toggle": "onLoomiSidebarToggle",
  "loomi-event-create": "onLoomiEventCreate",
  "loomi-event-delete": "onLoomiEventDelete",
  "loomi-reminder-change": "onLoomiReminderChange",
  "loomi-reminder-delete": "onLoomiReminderDelete",
  "loomi-event-duplicate": "onLoomiEventDuplicate",
}) as unknown as ForwardRefExoticComponent<
  Omit<
    JSX.IntrinsicElements["loomi-calendar"],
    | "onLoomiEventChange"
    | "onLoomiSlotSelect"
    | "onLoomiEventClick"
    | "onLoomiReminderClick"
    | "onLoomiViewChange"
    | "onLoomiDateChange"
    | "onLoomiSidebarToggle"
    | "onLoomiEventCreate"
    | "onLoomiEventDelete"
    | "onLoomiReminderChange"
    | "onLoomiReminderDelete"
    | "onLoomiEventDuplicate"
  > & {
    onLoomiEventChange?: (e: Event) => void;
    onLoomiSlotSelect?: (e: Event) => void;
    onLoomiEventClick?: (e: Event) => void;
    onLoomiReminderClick?: (e: Event) => void;
    onLoomiViewChange?: (e: Event) => void;
    onLoomiDateChange?: (e: Event) => void;
    onLoomiSidebarToggle?: (e: Event) => void;
    onLoomiEventCreate?: (e: Event) => void;
    onLoomiEventDelete?: (e: Event) => void;
    onLoomiReminderChange?: (e: Event) => void;
    onLoomiReminderDelete?: (e: Event) => void;
    onLoomiEventDuplicate?: (e: Event) => void;
  }
>;

export const Card: ForwardRefExoticComponent<JSX.IntrinsicElements["loomi-card"]> = createComponent(
  "loomi-card",
  {},
) as unknown as ForwardRefExoticComponent<JSX.IntrinsicElements["loomi-card"]>;

export const CardAction: ForwardRefExoticComponent<JSX.IntrinsicElements["loomi-card-action"]> =
  createComponent("loomi-card-action", {}) as unknown as ForwardRefExoticComponent<
    JSX.IntrinsicElements["loomi-card-action"]
  >;

export const CardContent: ForwardRefExoticComponent<JSX.IntrinsicElements["loomi-card-content"]> =
  createComponent("loomi-card-content", {}) as unknown as ForwardRefExoticComponent<
    JSX.IntrinsicElements["loomi-card-content"]
  >;

export const CardDescription: ForwardRefExoticComponent<
  JSX.IntrinsicElements["loomi-card-description"]
> = createComponent("loomi-card-description", {}) as unknown as ForwardRefExoticComponent<
  JSX.IntrinsicElements["loomi-card-description"]
>;

export const CardFooter: ForwardRefExoticComponent<JSX.IntrinsicElements["loomi-card-footer"]> =
  createComponent("loomi-card-footer", {}) as unknown as ForwardRefExoticComponent<
    JSX.IntrinsicElements["loomi-card-footer"]
  >;

export const CardHeader: ForwardRefExoticComponent<JSX.IntrinsicElements["loomi-card-header"]> =
  createComponent("loomi-card-header", {}) as unknown as ForwardRefExoticComponent<
    JSX.IntrinsicElements["loomi-card-header"]
  >;

export const CardTitle: ForwardRefExoticComponent<JSX.IntrinsicElements["loomi-card-title"]> =
  createComponent("loomi-card-title", {}) as unknown as ForwardRefExoticComponent<
    JSX.IntrinsicElements["loomi-card-title"]
  >;

export const CenteredContent: ForwardRefExoticComponent<
  JSX.IntrinsicElements["loomi-centered-content"]
> = createComponent("loomi-centered-content", {}) as unknown as ForwardRefExoticComponent<
  JSX.IntrinsicElements["loomi-centered-content"]
>;

export const Chart: ForwardRefExoticComponent<JSX.IntrinsicElements["loomi-chart"]> =
  createComponent("loomi-chart", {}) as unknown as ForwardRefExoticComponent<
    JSX.IntrinsicElements["loomi-chart"]
  >;

export const ChatMessage: ForwardRefExoticComponent<JSX.IntrinsicElements["loomi-chat-message"]> =
  createComponent("loomi-chat-message", {}) as unknown as ForwardRefExoticComponent<
    JSX.IntrinsicElements["loomi-chat-message"]
  >;

export const ChatWindow: ForwardRefExoticComponent<
  Omit<
    JSX.IntrinsicElements["loomi-chat-window"],
    "onLoomiReset" | "onLoomiAddUser" | "onLoomiConversationSelect" | "onLoomiSend"
  > & {
    onLoomiReset?: (e: Event) => void;
    onLoomiAddUser?: (e: Event) => void;
    onLoomiConversationSelect?: (e: Event) => void;
    onLoomiSend?: (e: Event) => void;
  }
> = createComponent("loomi-chat-window", {
  "loomi-reset": "onLoomiReset",
  "loomi-add-user": "onLoomiAddUser",
  "loomi-conversation-select": "onLoomiConversationSelect",
  "loomi-send": "onLoomiSend",
}) as unknown as ForwardRefExoticComponent<
  Omit<
    JSX.IntrinsicElements["loomi-chat-window"],
    "onLoomiReset" | "onLoomiAddUser" | "onLoomiConversationSelect" | "onLoomiSend"
  > & {
    onLoomiReset?: (e: Event) => void;
    onLoomiAddUser?: (e: Event) => void;
    onLoomiConversationSelect?: (e: Event) => void;
    onLoomiSend?: (e: Event) => void;
  }
>;

export const Checkbox: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-checkbox"], "onChange"> & {
    onChange?: (e: Event) => void;
  }
> = createComponent("loomi-checkbox", {
  change: "onChange",
}) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-checkbox"], "onChange"> & {
    onChange?: (e: Event) => void;
  }
>;

export const Checkcard: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-checkcard"], "onLoomiCheckcardClick"> & {
    onLoomiCheckcardClick?: (e: Event) => void;
  }
> = createComponent("loomi-checkcard", {
  "loomi-checkcard-click": "onLoomiCheckcardClick",
}) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-checkcard"], "onLoomiCheckcardClick"> & {
    onLoomiCheckcardClick?: (e: Event) => void;
  }
>;

export const Checkcards: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-checkcards"], "onChange"> & {
    onChange?: (e: Event) => void;
  }
> = createComponent("loomi-checkcards", {
  change: "onChange",
}) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-checkcards"], "onChange"> & {
    onChange?: (e: Event) => void;
  }
>;

export const Clipboard: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-clipboard"], "onLoomiCopied" | "onLoomiCopyError"> & {
    onLoomiCopied?: (e: Event) => void;
    onLoomiCopyError?: (e: Event) => void;
  }
> = createComponent("loomi-clipboard", {
  "loomi-copied": "onLoomiCopied",
  "loomi-copy-error": "onLoomiCopyError",
}) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-clipboard"], "onLoomiCopied" | "onLoomiCopyError"> & {
    onLoomiCopied?: (e: Event) => void;
    onLoomiCopyError?: (e: Event) => void;
  }
>;

export const Colorpicker: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-colorpicker"], "onChange"> & {
    onChange?: (e: Event) => void;
  }
> = createComponent("loomi-colorpicker", {
  change: "onChange",
}) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-colorpicker"], "onChange"> & {
    onChange?: (e: Event) => void;
  }
>;

export const CommandPalette: ForwardRefExoticComponent<
  Omit<
    JSX.IntrinsicElements["loomi-command-palette"],
    "onLoomiCommandSelect" | "onLoomiCommandOpenChange"
  > & {
    onLoomiCommandSelect?: (e: Event) => void;
    onLoomiCommandOpenChange?: (e: Event) => void;
  }
> = createComponent("loomi-command-palette", {
  "loomi-command-select": "onLoomiCommandSelect",
  "loomi-command-open-change": "onLoomiCommandOpenChange",
}) as unknown as ForwardRefExoticComponent<
  Omit<
    JSX.IntrinsicElements["loomi-command-palette"],
    "onLoomiCommandSelect" | "onLoomiCommandOpenChange"
  > & {
    onLoomiCommandSelect?: (e: Event) => void;
    onLoomiCommandOpenChange?: (e: Event) => void;
  }
>;

export const ContactCard: ForwardRefExoticComponent<JSX.IntrinsicElements["loomi-contact-card"]> =
  createComponent("loomi-contact-card", {}) as unknown as ForwardRefExoticComponent<
    JSX.IntrinsicElements["loomi-contact-card"]
  >;

export const ContextMenu: ForwardRefExoticComponent<JSX.IntrinsicElements["loomi-context-menu"]> =
  createComponent("loomi-context-menu", {}) as unknown as ForwardRefExoticComponent<
    JSX.IntrinsicElements["loomi-context-menu"]
  >;

export const ContextMenuItem: ForwardRefExoticComponent<
  JSX.IntrinsicElements["loomi-context-menu-item"]
> = createComponent("loomi-context-menu-item", {}) as unknown as ForwardRefExoticComponent<
  JSX.IntrinsicElements["loomi-context-menu-item"]
>;

export const Countries: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-countries"], "onChange" | "onLoomiSelect" | "onInput"> & {
    onChange?: (e: Event) => void;
    onLoomiSelect?: (e: Event) => void;
    onInput?: (e: Event) => void;
  }
> = createComponent("loomi-countries", {
  change: "onChange",
  "loomi-select": "onLoomiSelect",
  input: "onInput",
}) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-countries"], "onChange" | "onLoomiSelect" | "onInput"> & {
    onChange?: (e: Event) => void;
    onLoomiSelect?: (e: Event) => void;
    onInput?: (e: Event) => void;
  }
>;

export const Creditcard: ForwardRefExoticComponent<
  Omit<
    JSX.IntrinsicElements["loomi-creditcard"],
    "onType" | "onLoomiFlip" | "onInput" | "onChange"
  > & {
    onType?: (e: Event) => void;
    onLoomiFlip?: (e: Event) => void;
    onInput?: (e: Event) => void;
    onChange?: (e: Event) => void;
  }
> = createComponent("loomi-creditcard", {
  type: "onType",
  "loomi-flip": "onLoomiFlip",
  input: "onInput",
  change: "onChange",
}) as unknown as ForwardRefExoticComponent<
  Omit<
    JSX.IntrinsicElements["loomi-creditcard"],
    "onType" | "onLoomiFlip" | "onInput" | "onChange"
  > & {
    onType?: (e: Event) => void;
    onLoomiFlip?: (e: Event) => void;
    onInput?: (e: Event) => void;
    onChange?: (e: Event) => void;
  }
>;

export const DataGrid: ForwardRefExoticComponent<JSX.IntrinsicElements["loomi-data-grid"]> =
  createComponent("loomi-data-grid", {}) as unknown as ForwardRefExoticComponent<
    JSX.IntrinsicElements["loomi-data-grid"]
  >;

export const DateRangePicker: ForwardRefExoticComponent<
  JSX.IntrinsicElements["loomi-date-range-picker"]
> = createComponent("loomi-date-range-picker", {}) as unknown as ForwardRefExoticComponent<
  JSX.IntrinsicElements["loomi-date-range-picker"]
>;

export const Datepicker: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-datepicker"], "onChange"> & {
    onChange?: (e: Event) => void;
  }
> = createComponent("loomi-datepicker", {
  change: "onChange",
}) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-datepicker"], "onChange"> & {
    onChange?: (e: Event) => void;
  }
>;

export const Divider: ForwardRefExoticComponent<JSX.IntrinsicElements["loomi-divider"]> =
  createComponent("loomi-divider", {}) as unknown as ForwardRefExoticComponent<
    JSX.IntrinsicElements["loomi-divider"]
  >;

export const Drawer: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-drawer"], "onOpen" | "onClose"> & {
    onOpen?: (e: Event) => void;
    onClose?: (e: Event) => void;
  }
> = createComponent("loomi-drawer", {
  open: "onOpen",
  close: "onClose",
}) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-drawer"], "onOpen" | "onClose"> & {
    onOpen?: (e: Event) => void;
    onClose?: (e: Event) => void;
  }
>;

export const Dropmenu: ForwardRefExoticComponent<JSX.IntrinsicElements["loomi-dropmenu"]> =
  createComponent("loomi-dropmenu", {}) as unknown as ForwardRefExoticComponent<
    JSX.IntrinsicElements["loomi-dropmenu"]
  >;

export const DropmenuItem: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-dropmenu-item"], "onChange"> & {
    onChange?: (e: Event) => void;
  }
> = createComponent("loomi-dropmenu-item", {
  change: "onChange",
}) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-dropmenu-item"], "onChange"> & {
    onChange?: (e: Event) => void;
  }
>;

export const EmojiPicker: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-emoji-picker"], "onLoomiEmojiSelect" | "onChange"> & {
    onLoomiEmojiSelect?: (e: Event) => void;
    onChange?: (e: Event) => void;
  }
> = createComponent("loomi-emoji-picker", {
  "loomi-emoji-select": "onLoomiEmojiSelect",
  change: "onChange",
}) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-emoji-picker"], "onLoomiEmojiSelect" | "onChange"> & {
    onLoomiEmojiSelect?: (e: Event) => void;
    onChange?: (e: Event) => void;
  }
>;

export const EmptyState: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-empty-state"], "onAction" | "onLoomiAction"> & {
    onAction?: (e: Event) => void;
    onLoomiAction?: (e: Event) => void;
  }
> = createComponent("loomi-empty-state", {
  action: "onAction",
  "loomi-action": "onLoomiAction",
}) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-empty-state"], "onAction" | "onLoomiAction"> & {
    onAction?: (e: Event) => void;
    onLoomiAction?: (e: Event) => void;
  }
>;

export const Fab: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-fab"], "onOpen" | "onClose"> & {
    onOpen?: (e: Event) => void;
    onClose?: (e: Event) => void;
  }
> = createComponent("loomi-fab", {
  open: "onOpen",
  close: "onClose",
}) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-fab"], "onOpen" | "onClose"> & {
    onOpen?: (e: Event) => void;
    onClose?: (e: Event) => void;
  }
>;

export const FabItem: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-fab-item"], "onLoomiSelect"> & {
    onLoomiSelect?: (e: Event) => void;
  }
> = createComponent("loomi-fab-item", {
  "loomi-select": "onLoomiSelect",
}) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-fab-item"], "onLoomiSelect"> & {
    onLoomiSelect?: (e: Event) => void;
  }
>;

export const Filepicker: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-filepicker"], "onChange"> & {
    onChange?: (e: Event) => void;
  }
> = createComponent("loomi-filepicker", {
  change: "onChange",
}) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-filepicker"], "onChange"> & {
    onChange?: (e: Event) => void;
  }
>;

export const FilterBuilder: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-filter-builder"], "onLoomiFilterChange"> & {
    onLoomiFilterChange?: (e: Event) => void;
  }
> = createComponent("loomi-filter-builder", {
  "loomi-filter-change": "onLoomiFilterChange",
}) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-filter-builder"], "onLoomiFilterChange"> & {
    onLoomiFilterChange?: (e: Event) => void;
  }
>;

export const FloatingPanel: ForwardRefExoticComponent<
  Omit<
    JSX.IntrinsicElements["loomi-floating-panel"],
    "onOpen" | "onClose" | "onLoomiDrag" | "onLoomiResize" | "onLoomiMinimize" | "onLoomiMaximize"
  > & {
    onOpen?: (e: Event) => void;
    onClose?: (e: Event) => void;
    onLoomiDrag?: (e: Event) => void;
    onLoomiResize?: (e: Event) => void;
    onLoomiMinimize?: (e: Event) => void;
    onLoomiMaximize?: (e: Event) => void;
  }
> = createComponent("loomi-floating-panel", {
  open: "onOpen",
  close: "onClose",
  "loomi-drag": "onLoomiDrag",
  "loomi-resize": "onLoomiResize",
  "loomi-minimize": "onLoomiMinimize",
  "loomi-maximize": "onLoomiMaximize",
}) as unknown as ForwardRefExoticComponent<
  Omit<
    JSX.IntrinsicElements["loomi-floating-panel"],
    "onOpen" | "onClose" | "onLoomiDrag" | "onLoomiResize" | "onLoomiMinimize" | "onLoomiMaximize"
  > & {
    onOpen?: (e: Event) => void;
    onClose?: (e: Event) => void;
    onLoomiDrag?: (e: Event) => void;
    onLoomiResize?: (e: Event) => void;
    onLoomiMinimize?: (e: Event) => void;
    onLoomiMaximize?: (e: Event) => void;
  }
>;

export const HorizontalLineGraph: ForwardRefExoticComponent<
  JSX.IntrinsicElements["loomi-horizontal-line-graph"]
> = createComponent("loomi-horizontal-line-graph", {}) as unknown as ForwardRefExoticComponent<
  JSX.IntrinsicElements["loomi-horizontal-line-graph"]
>;

export const Icon: ForwardRefExoticComponent<JSX.IntrinsicElements["loomi-icon"]> = createComponent(
  "loomi-icon",
  {},
) as unknown as ForwardRefExoticComponent<JSX.IntrinsicElements["loomi-icon"]>;

export const Input: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-input"], "onType" | "onInput" | "onChange"> & {
    onType?: (e: Event) => void;
    onInput?: (e: Event) => void;
    onChange?: (e: Event) => void;
  }
> = createComponent("loomi-input", {
  type: "onType",
  input: "onInput",
  change: "onChange",
}) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-input"], "onType" | "onInput" | "onChange"> & {
    onType?: (e: Event) => void;
    onInput?: (e: Event) => void;
    onChange?: (e: Event) => void;
  }
>;

export const LightboxImage: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-lightbox-image"], "onLoomiOpen" | "onLoomiClose"> & {
    onLoomiOpen?: (e: Event) => void;
    onLoomiClose?: (e: Event) => void;
  }
> = createComponent("loomi-lightbox-image", {
  "loomi-open": "onLoomiOpen",
  "loomi-close": "onLoomiClose",
}) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-lightbox-image"], "onLoomiOpen" | "onLoomiClose"> & {
    onLoomiOpen?: (e: Event) => void;
    onLoomiClose?: (e: Event) => void;
  }
>;

export const Listview: ForwardRefExoticComponent<JSX.IntrinsicElements["loomi-listview"]> =
  createComponent("loomi-listview", {}) as unknown as ForwardRefExoticComponent<
    JSX.IntrinsicElements["loomi-listview"]
  >;

export const ListviewItem: ForwardRefExoticComponent<JSX.IntrinsicElements["loomi-listview-item"]> =
  createComponent("loomi-listview-item", {}) as unknown as ForwardRefExoticComponent<
    JSX.IntrinsicElements["loomi-listview-item"]
  >;

export const Modal: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-modal"], "onOpen" | "onClose" | "onOk"> & {
    onOpen?: (e: Event) => void;
    onClose?: (e: Event) => void;
    onOk?: (e: Event) => void;
  }
> = createComponent("loomi-modal", {
  open: "onOpen",
  close: "onClose",
  ok: "onOk",
}) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-modal"], "onOpen" | "onClose" | "onOk"> & {
    onOpen?: (e: Event) => void;
    onClose?: (e: Event) => void;
    onOk?: (e: Event) => void;
  }
>;

export const Notification: ForwardRefExoticComponent<JSX.IntrinsicElements["loomi-notification"]> =
  createComponent("loomi-notification", {}) as unknown as ForwardRefExoticComponent<
    JSX.IntrinsicElements["loomi-notification"]
  >;

export const Number: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-number"], "onInput" | "onChange"> & {
    onInput?: (e: Event) => void;
    onChange?: (e: Event) => void;
  }
> = createComponent("loomi-number", {
  input: "onInput",
  change: "onChange",
}) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-number"], "onInput" | "onChange"> & {
    onInput?: (e: Event) => void;
    onChange?: (e: Event) => void;
  }
>;

export const Otp: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-otp"], "onLoomiVerify"> & {
    onLoomiVerify?: (e: Event) => void;
  }
> = createComponent("loomi-otp", {
  "loomi-verify": "onLoomiVerify",
}) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-otp"], "onLoomiVerify"> & {
    onLoomiVerify?: (e: Event) => void;
  }
>;

export const Pagination: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-pagination"], "onLoomiPageChange"> & {
    onLoomiPageChange?: (e: Event) => void;
  }
> = createComponent("loomi-pagination", {
  "loomi-page-change": "onLoomiPageChange",
}) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-pagination"], "onLoomiPageChange"> & {
    onLoomiPageChange?: (e: Event) => void;
  }
>;

export const Password: ForwardRefExoticComponent<
  Omit<
    JSX.IntrinsicElements["loomi-password"],
    "onType" | "onLoomiPrefixChange" | "onInput" | "onChange"
  > & {
    onType?: (e: Event) => void;
    onLoomiPrefixChange?: (e: Event) => void;
    onInput?: (e: Event) => void;
    onChange?: (e: Event) => void;
  }
> = createComponent("loomi-password", {
  type: "onType",
  "loomi-prefix-change": "onLoomiPrefixChange",
  input: "onInput",
  change: "onChange",
}) as unknown as ForwardRefExoticComponent<
  Omit<
    JSX.IntrinsicElements["loomi-password"],
    "onType" | "onLoomiPrefixChange" | "onInput" | "onChange"
  > & {
    onType?: (e: Event) => void;
    onLoomiPrefixChange?: (e: Event) => void;
    onInput?: (e: Event) => void;
    onChange?: (e: Event) => void;
  }
>;

export const PhotoGallery: ForwardRefExoticComponent<
  Omit<
    JSX.IntrinsicElements["loomi-photo-gallery"],
    | "onLoomiFavourite"
    | "onLoomiAlbumChange"
    | "onLoomiSlideshowStart"
    | "onLoomiSlideshowEnd"
    | "onLoomiPhotoOpen"
    | "onLoomiPhotoChange"
    | "onLoomiPhotoClose"
    | "onLoomiRotate"
    | "onLoomiShare"
  > & {
    onLoomiFavourite?: (e: Event) => void;
    onLoomiAlbumChange?: (e: Event) => void;
    onLoomiSlideshowStart?: (e: Event) => void;
    onLoomiSlideshowEnd?: (e: Event) => void;
    onLoomiPhotoOpen?: (e: Event) => void;
    onLoomiPhotoChange?: (e: Event) => void;
    onLoomiPhotoClose?: (e: Event) => void;
    onLoomiRotate?: (e: Event) => void;
    onLoomiShare?: (e: Event) => void;
  }
> = createComponent("loomi-photo-gallery", {
  "loomi-favourite": "onLoomiFavourite",
  "loomi-album-change": "onLoomiAlbumChange",
  "loomi-slideshow-start": "onLoomiSlideshowStart",
  "loomi-slideshow-end": "onLoomiSlideshowEnd",
  "loomi-photo-open": "onLoomiPhotoOpen",
  "loomi-photo-change": "onLoomiPhotoChange",
  "loomi-photo-close": "onLoomiPhotoClose",
  "loomi-rotate": "onLoomiRotate",
  "loomi-share": "onLoomiShare",
}) as unknown as ForwardRefExoticComponent<
  Omit<
    JSX.IntrinsicElements["loomi-photo-gallery"],
    | "onLoomiFavourite"
    | "onLoomiAlbumChange"
    | "onLoomiSlideshowStart"
    | "onLoomiSlideshowEnd"
    | "onLoomiPhotoOpen"
    | "onLoomiPhotoChange"
    | "onLoomiPhotoClose"
    | "onLoomiRotate"
    | "onLoomiShare"
  > & {
    onLoomiFavourite?: (e: Event) => void;
    onLoomiAlbumChange?: (e: Event) => void;
    onLoomiSlideshowStart?: (e: Event) => void;
    onLoomiSlideshowEnd?: (e: Event) => void;
    onLoomiPhotoOpen?: (e: Event) => void;
    onLoomiPhotoChange?: (e: Event) => void;
    onLoomiPhotoClose?: (e: Event) => void;
    onLoomiRotate?: (e: Event) => void;
    onLoomiShare?: (e: Event) => void;
  }
>;

export const PhotoGalleryItem: ForwardRefExoticComponent<
  JSX.IntrinsicElements["loomi-photo-gallery-item"]
> = createComponent("loomi-photo-gallery-item", {}) as unknown as ForwardRefExoticComponent<
  JSX.IntrinsicElements["loomi-photo-gallery-item"]
>;

export const Popover: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-popover"], "onLoomiToggle"> & {
    onLoomiToggle?: (e: Event) => void;
  }
> = createComponent("loomi-popover", {
  "loomi-toggle": "onLoomiToggle",
}) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-popover"], "onLoomiToggle"> & {
    onLoomiToggle?: (e: Event) => void;
  }
>;

export const Processing: ForwardRefExoticComponent<JSX.IntrinsicElements["loomi-processing"]> =
  createComponent("loomi-processing", {}) as unknown as ForwardRefExoticComponent<
    JSX.IntrinsicElements["loomi-processing"]
  >;

export const ProfileMenu: ForwardRefExoticComponent<JSX.IntrinsicElements["loomi-profile-menu"]> =
  createComponent("loomi-profile-menu", {}) as unknown as ForwardRefExoticComponent<
    JSX.IntrinsicElements["loomi-profile-menu"]
  >;

export const ProgressBar: ForwardRefExoticComponent<JSX.IntrinsicElements["loomi-progress-bar"]> =
  createComponent("loomi-progress-bar", {}) as unknown as ForwardRefExoticComponent<
    JSX.IntrinsicElements["loomi-progress-bar"]
  >;

export const ProgressCircle: ForwardRefExoticComponent<
  JSX.IntrinsicElements["loomi-progress-circle"]
> = createComponent("loomi-progress-circle", {}) as unknown as ForwardRefExoticComponent<
  JSX.IntrinsicElements["loomi-progress-circle"]
>;

export const ProgressStep: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-progress-step"], "onLoomiProgressStepSelect"> & {
    onLoomiProgressStepSelect?: (e: Event) => void;
  }
> = createComponent("loomi-progress-step", {
  "loomi-progress-step-select": "onLoomiProgressStepSelect",
}) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-progress-step"], "onLoomiProgressStepSelect"> & {
    onLoomiProgressStepSelect?: (e: Event) => void;
  }
>;

export const ProgressSteps: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-progress-steps"], "onLoomiProgressStepsChange"> & {
    onLoomiProgressStepsChange?: (e: Event) => void;
  }
> = createComponent("loomi-progress-steps", {
  "loomi-progress-steps-change": "onLoomiProgressStepsChange",
}) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-progress-steps"], "onLoomiProgressStepsChange"> & {
    onLoomiProgressStepsChange?: (e: Event) => void;
  }
>;

export const Qrcode: ForwardRefExoticComponent<JSX.IntrinsicElements["loomi-qrcode"]> =
  createComponent("loomi-qrcode", {}) as unknown as ForwardRefExoticComponent<
    JSX.IntrinsicElements["loomi-qrcode"]
  >;

export const Radio: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-radio"], "onChange"> & {
    onChange?: (e: Event) => void;
  }
> = createComponent("loomi-radio", { change: "onChange" }) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-radio"], "onChange"> & {
    onChange?: (e: Event) => void;
  }
>;

export const Rating: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-rating"], "onChange"> & {
    onChange?: (e: Event) => void;
  }
> = createComponent("loomi-rating", { change: "onChange" }) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-rating"], "onChange"> & {
    onChange?: (e: Event) => void;
  }
>;

export const ResizableHandle: ForwardRefExoticComponent<
  JSX.IntrinsicElements["loomi-resizable-handle"]
> = createComponent("loomi-resizable-handle", {}) as unknown as ForwardRefExoticComponent<
  JSX.IntrinsicElements["loomi-resizable-handle"]
>;

export const ResizablePanel: ForwardRefExoticComponent<
  JSX.IntrinsicElements["loomi-resizable-panel"]
> = createComponent("loomi-resizable-panel", {}) as unknown as ForwardRefExoticComponent<
  JSX.IntrinsicElements["loomi-resizable-panel"]
>;

export const ResizablePanelGroup: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-resizable-panel-group"], "onLoomiLayoutChange"> & {
    onLoomiLayoutChange?: (e: Event) => void;
  }
> = createComponent("loomi-resizable-panel-group", {
  "loomi-layout-change": "onLoomiLayoutChange",
}) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-resizable-panel-group"], "onLoomiLayoutChange"> & {
    onLoomiLayoutChange?: (e: Event) => void;
  }
>;

export const Scroller: ForwardRefExoticComponent<
  Omit<
    JSX.IntrinsicElements["loomi-scroller"],
    "onLoomiScrollerItemClick" | "onLoomiScrollComplete"
  > & {
    onLoomiScrollerItemClick?: (e: Event) => void;
    onLoomiScrollComplete?: (e: Event) => void;
  }
> = createComponent("loomi-scroller", {
  "loomi-scroller-item-click": "onLoomiScrollerItemClick",
  "loomi-scroll-complete": "onLoomiScrollComplete",
}) as unknown as ForwardRefExoticComponent<
  Omit<
    JSX.IntrinsicElements["loomi-scroller"],
    "onLoomiScrollerItemClick" | "onLoomiScrollComplete"
  > & {
    onLoomiScrollerItemClick?: (e: Event) => void;
    onLoomiScrollComplete?: (e: Event) => void;
  }
>;

export const Select: ForwardRefExoticComponent<
  Omit<
    JSX.IntrinsicElements["loomi-select"],
    "onChange" | "onLoomiSelect" | "onLoomiEmptyAction"
  > & {
    onChange?: (e: Event) => void;
    onLoomiSelect?: (e: Event) => void;
    onLoomiEmptyAction?: (e: Event) => void;
  }
> = createComponent("loomi-select", {
  change: "onChange",
  "loomi-select": "onLoomiSelect",
  "loomi-empty-action": "onLoomiEmptyAction",
}) as unknown as ForwardRefExoticComponent<
  Omit<
    JSX.IntrinsicElements["loomi-select"],
    "onChange" | "onLoomiSelect" | "onLoomiEmptyAction"
  > & {
    onChange?: (e: Event) => void;
    onLoomiSelect?: (e: Event) => void;
    onLoomiEmptyAction?: (e: Event) => void;
  }
>;

export const SideNav: ForwardRefExoticComponent<JSX.IntrinsicElements["loomi-side-nav"]> =
  createComponent("loomi-side-nav", {}) as unknown as ForwardRefExoticComponent<
    JSX.IntrinsicElements["loomi-side-nav"]
  >;

export const SideNavItem: ForwardRefExoticComponent<JSX.IntrinsicElements["loomi-side-nav-item"]> =
  createComponent("loomi-side-nav-item", {}) as unknown as ForwardRefExoticComponent<
    JSX.IntrinsicElements["loomi-side-nav-item"]
  >;

export const Slider: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-slider"], "onInput" | "onChange"> & {
    onInput?: (e: Event) => void;
    onChange?: (e: Event) => void;
  }
> = createComponent("loomi-slider", {
  input: "onInput",
  change: "onChange",
}) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-slider"], "onInput" | "onChange"> & {
    onInput?: (e: Event) => void;
    onChange?: (e: Event) => void;
  }
>;

export const Sortable: ForwardRefExoticComponent<
  Omit<
    JSX.IntrinsicElements["loomi-sortable"],
    "onLoomiFilter" | "onLoomiItemClick" | "onLoomiReorder" | "onLoomiTransfer"
  > & {
    onLoomiFilter?: (e: Event) => void;
    onLoomiItemClick?: (e: Event) => void;
    onLoomiReorder?: (e: Event) => void;
    onLoomiTransfer?: (e: Event) => void;
  }
> = createComponent("loomi-sortable", {
  "loomi-filter": "onLoomiFilter",
  "loomi-item-click": "onLoomiItemClick",
  "loomi-reorder": "onLoomiReorder",
  "loomi-transfer": "onLoomiTransfer",
}) as unknown as ForwardRefExoticComponent<
  Omit<
    JSX.IntrinsicElements["loomi-sortable"],
    "onLoomiFilter" | "onLoomiItemClick" | "onLoomiReorder" | "onLoomiTransfer"
  > & {
    onLoomiFilter?: (e: Event) => void;
    onLoomiItemClick?: (e: Event) => void;
    onLoomiReorder?: (e: Event) => void;
    onLoomiTransfer?: (e: Event) => void;
  }
>;

export const Spinner: ForwardRefExoticComponent<JSX.IntrinsicElements["loomi-spinner"]> =
  createComponent("loomi-spinner", {}) as unknown as ForwardRefExoticComponent<
    JSX.IntrinsicElements["loomi-spinner"]
  >;

export const SplitButton: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-split-button"], "onLoomiSplitToggle"> & {
    onLoomiSplitToggle?: (e: Event) => void;
  }
> = createComponent("loomi-split-button", {
  "loomi-split-toggle": "onLoomiSplitToggle",
}) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-split-button"], "onLoomiSplitToggle"> & {
    onLoomiSplitToggle?: (e: Event) => void;
  }
>;

export const Statistic: ForwardRefExoticComponent<JSX.IntrinsicElements["loomi-statistic"]> =
  createComponent("loomi-statistic", {}) as unknown as ForwardRefExoticComponent<
    JSX.IntrinsicElements["loomi-statistic"]
  >;

export const Tab: ForwardRefExoticComponent<JSX.IntrinsicElements["loomi-tab"]> = createComponent(
  "loomi-tab",
  {},
) as unknown as ForwardRefExoticComponent<JSX.IntrinsicElements["loomi-tab"]>;

export const Table: ForwardRefExoticComponent<
  Omit<
    JSX.IntrinsicElements["loomi-table"],
    | "onLoomiSelectionChange"
    | "onLoomiActionCall"
    | "onLoomiAction"
    | "onLoomiRowClick"
    | "onLoomiEmptyAction"
    | "onLoomiPageChange"
  > & {
    onLoomiSelectionChange?: (e: Event) => void;
    onLoomiActionCall?: (e: Event) => void;
    onLoomiAction?: (e: Event) => void;
    onLoomiRowClick?: (e: Event) => void;
    onLoomiEmptyAction?: (e: Event) => void;
    onLoomiPageChange?: (e: Event) => void;
  }
> = createComponent("loomi-table", {
  "loomi-selection-change": "onLoomiSelectionChange",
  "loomi-action-call": "onLoomiActionCall",
  "loomi-action": "onLoomiAction",
  "loomi-row-click": "onLoomiRowClick",
  "loomi-empty-action": "onLoomiEmptyAction",
  "loomi-page-change": "onLoomiPageChange",
}) as unknown as ForwardRefExoticComponent<
  Omit<
    JSX.IntrinsicElements["loomi-table"],
    | "onLoomiSelectionChange"
    | "onLoomiActionCall"
    | "onLoomiAction"
    | "onLoomiRowClick"
    | "onLoomiEmptyAction"
    | "onLoomiPageChange"
  > & {
    onLoomiSelectionChange?: (e: Event) => void;
    onLoomiActionCall?: (e: Event) => void;
    onLoomiAction?: (e: Event) => void;
    onLoomiRowClick?: (e: Event) => void;
    onLoomiEmptyAction?: (e: Event) => void;
    onLoomiPageChange?: (e: Event) => void;
  }
>;

export const Tabs: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-tabs"], "onLoomiTabChange"> & {
    onLoomiTabChange?: (e: Event) => void;
  }
> = createComponent("loomi-tabs", {
  "loomi-tab-change": "onLoomiTabChange",
}) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-tabs"], "onLoomiTabChange"> & {
    onLoomiTabChange?: (e: Event) => void;
  }
>;

export const Tag: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-tag"], "onClose" | "onLoomiTagClick"> & {
    onClose?: (e: Event) => void;
    onLoomiTagClick?: (e: Event) => void;
  }
> = createComponent("loomi-tag", {
  close: "onClose",
  "loomi-tag-click": "onLoomiTagClick",
}) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-tag"], "onClose" | "onLoomiTagClick"> & {
    onClose?: (e: Event) => void;
    onLoomiTagClick?: (e: Event) => void;
  }
>;

export const TagInput: ForwardRefExoticComponent<
  Omit<
    JSX.IntrinsicElements["loomi-tag-input"],
    "onType" | "onLoomiAutocompleteSelect" | "onInput" | "onChange"
  > & {
    onType?: (e: Event) => void;
    onLoomiAutocompleteSelect?: (e: Event) => void;
    onInput?: (e: Event) => void;
    onChange?: (e: Event) => void;
  }
> = createComponent("loomi-tag-input", {
  type: "onType",
  "loomi-autocomplete-select": "onLoomiAutocompleteSelect",
  input: "onInput",
  change: "onChange",
}) as unknown as ForwardRefExoticComponent<
  Omit<
    JSX.IntrinsicElements["loomi-tag-input"],
    "onType" | "onLoomiAutocompleteSelect" | "onInput" | "onChange"
  > & {
    onType?: (e: Event) => void;
    onLoomiAutocompleteSelect?: (e: Event) => void;
    onInput?: (e: Event) => void;
    onChange?: (e: Event) => void;
  }
>;

export const Tags: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-tags"], "onChange"> & {
    onChange?: (e: Event) => void;
  }
> = createComponent("loomi-tags", { change: "onChange" }) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-tags"], "onChange"> & {
    onChange?: (e: Event) => void;
  }
>;

export const TextEditor: ForwardRefExoticComponent<
  Omit<
    JSX.IntrinsicElements["loomi-text-editor"],
    "onType" | "onLoomiAiGenerate" | "onInput" | "onChange"
  > & {
    onType?: (e: Event) => void;
    onLoomiAiGenerate?: (e: Event) => void;
    onInput?: (e: Event) => void;
    onChange?: (e: Event) => void;
  }
> = createComponent("loomi-text-editor", {
  type: "onType",
  "loomi-ai-generate": "onLoomiAiGenerate",
  input: "onInput",
  change: "onChange",
}) as unknown as ForwardRefExoticComponent<
  Omit<
    JSX.IntrinsicElements["loomi-text-editor"],
    "onType" | "onLoomiAiGenerate" | "onInput" | "onChange"
  > & {
    onType?: (e: Event) => void;
    onLoomiAiGenerate?: (e: Event) => void;
    onInput?: (e: Event) => void;
    onChange?: (e: Event) => void;
  }
>;

export const Textarea: ForwardRefExoticComponent<
  Omit<
    JSX.IntrinsicElements["loomi-textarea"],
    "onType" | "onLoomiMentionSearch" | "onLoomiMentionSelect" | "onInput" | "onChange"
  > & {
    onType?: (e: Event) => void;
    onLoomiMentionSearch?: (e: Event) => void;
    onLoomiMentionSelect?: (e: Event) => void;
    onInput?: (e: Event) => void;
    onChange?: (e: Event) => void;
  }
> = createComponent("loomi-textarea", {
  type: "onType",
  "loomi-mention-search": "onLoomiMentionSearch",
  "loomi-mention-select": "onLoomiMentionSelect",
  input: "onInput",
  change: "onChange",
}) as unknown as ForwardRefExoticComponent<
  Omit<
    JSX.IntrinsicElements["loomi-textarea"],
    "onType" | "onLoomiMentionSearch" | "onLoomiMentionSelect" | "onInput" | "onChange"
  > & {
    onType?: (e: Event) => void;
    onLoomiMentionSearch?: (e: Event) => void;
    onLoomiMentionSelect?: (e: Event) => void;
    onInput?: (e: Event) => void;
    onChange?: (e: Event) => void;
  }
>;

export const ThemeSwitcher: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-theme-switcher"], "onLoomiThemeChange"> & {
    onLoomiThemeChange?: (e: Event) => void;
  }
> = createComponent("loomi-theme-switcher", {
  "loomi-theme-change": "onLoomiThemeChange",
}) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-theme-switcher"], "onLoomiThemeChange"> & {
    onLoomiThemeChange?: (e: Event) => void;
  }
>;

export const Timeline: ForwardRefExoticComponent<JSX.IntrinsicElements["loomi-timeline"]> =
  createComponent("loomi-timeline", {}) as unknown as ForwardRefExoticComponent<
    JSX.IntrinsicElements["loomi-timeline"]
  >;

export const TimelineItem: ForwardRefExoticComponent<JSX.IntrinsicElements["loomi-timeline-item"]> =
  createComponent("loomi-timeline-item", {}) as unknown as ForwardRefExoticComponent<
    JSX.IntrinsicElements["loomi-timeline-item"]
  >;

export const Timepicker: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-timepicker"], "onChange"> & {
    onChange?: (e: Event) => void;
  }
> = createComponent("loomi-timepicker", {
  change: "onChange",
}) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-timepicker"], "onChange"> & {
    onChange?: (e: Event) => void;
  }
>;

export const Timer: ForwardRefExoticComponent<
  Omit<
    JSX.IntrinsicElements["loomi-timer"],
    | "onType"
    | "onLoomiTimerStart"
    | "onLoomiTimerPause"
    | "onLoomiTimerReset"
    | "onLoomiTimerTick"
    | "onLoomiTimerComplete"
  > & {
    onType?: (e: Event) => void;
    onLoomiTimerStart?: (e: Event) => void;
    onLoomiTimerPause?: (e: Event) => void;
    onLoomiTimerReset?: (e: Event) => void;
    onLoomiTimerTick?: (e: Event) => void;
    onLoomiTimerComplete?: (e: Event) => void;
  }
> = createComponent("loomi-timer", {
  type: "onType",
  "loomi-timer-start": "onLoomiTimerStart",
  "loomi-timer-pause": "onLoomiTimerPause",
  "loomi-timer-reset": "onLoomiTimerReset",
  "loomi-timer-tick": "onLoomiTimerTick",
  "loomi-timer-complete": "onLoomiTimerComplete",
}) as unknown as ForwardRefExoticComponent<
  Omit<
    JSX.IntrinsicElements["loomi-timer"],
    | "onType"
    | "onLoomiTimerStart"
    | "onLoomiTimerPause"
    | "onLoomiTimerReset"
    | "onLoomiTimerTick"
    | "onLoomiTimerComplete"
  > & {
    onType?: (e: Event) => void;
    onLoomiTimerStart?: (e: Event) => void;
    onLoomiTimerPause?: (e: Event) => void;
    onLoomiTimerReset?: (e: Event) => void;
    onLoomiTimerTick?: (e: Event) => void;
    onLoomiTimerComplete?: (e: Event) => void;
  }
>;

export const Timezonepicker: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-timezonepicker"], "onChange" | "onLoomiSelect"> & {
    onChange?: (e: Event) => void;
    onLoomiSelect?: (e: Event) => void;
  }
> = createComponent("loomi-timezonepicker", {
  change: "onChange",
  "loomi-select": "onLoomiSelect",
}) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-timezonepicker"], "onChange" | "onLoomiSelect"> & {
    onChange?: (e: Event) => void;
    onLoomiSelect?: (e: Event) => void;
  }
>;

export const Toggle: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-toggle"], "onChange"> & {
    onChange?: (e: Event) => void;
  }
> = createComponent("loomi-toggle", { change: "onChange" }) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-toggle"], "onChange"> & {
    onChange?: (e: Event) => void;
  }
>;

export const Tooltip: ForwardRefExoticComponent<JSX.IntrinsicElements["loomi-tooltip"]> =
  createComponent("loomi-tooltip", {}) as unknown as ForwardRefExoticComponent<
    JSX.IntrinsicElements["loomi-tooltip"]
  >;

export const Video: ForwardRefExoticComponent<
  Omit<
    JSX.IntrinsicElements["loomi-video"],
    | "onPlay"
    | "onPause"
    | "onEnded"
    | "onTimeupdate"
    | "onVolumechange"
    | "onFullscreenchange"
    | "onEnterpictureinpicture"
    | "onLoomiVideoError"
  > & {
    onPlay?: (e: Event) => void;
    onPause?: (e: Event) => void;
    onEnded?: (e: Event) => void;
    onTimeupdate?: (e: Event) => void;
    onVolumechange?: (e: Event) => void;
    onFullscreenchange?: (e: Event) => void;
    onEnterpictureinpicture?: (e: Event) => void;
    onLoomiVideoError?: (e: Event) => void;
  }
> = createComponent("loomi-video", {
  play: "onPlay",
  pause: "onPause",
  ended: "onEnded",
  timeupdate: "onTimeupdate",
  volumechange: "onVolumechange",
  fullscreenchange: "onFullscreenchange",
  enterpictureinpicture: "onEnterpictureinpicture",
  "loomi-video-error": "onLoomiVideoError",
}) as unknown as ForwardRefExoticComponent<
  Omit<
    JSX.IntrinsicElements["loomi-video"],
    | "onPlay"
    | "onPause"
    | "onEnded"
    | "onTimeupdate"
    | "onVolumechange"
    | "onFullscreenchange"
    | "onEnterpictureinpicture"
    | "onLoomiVideoError"
  > & {
    onPlay?: (e: Event) => void;
    onPause?: (e: Event) => void;
    onEnded?: (e: Event) => void;
    onTimeupdate?: (e: Event) => void;
    onVolumechange?: (e: Event) => void;
    onFullscreenchange?: (e: Event) => void;
    onEnterpictureinpicture?: (e: Event) => void;
    onLoomiVideoError?: (e: Event) => void;
  }
>;
