// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import { createComponent } from "../create-component.js";

import "@loomidev/components/accordion";

export const Accordion: ForwardRefExoticComponent<
  JSX.IntrinsicElements["loomi-accordion"] & {
    canOpenMultiple?: JSX.IntrinsicElements["loomi-accordion"]["can-open-multiple"];
  }
> = createComponent(
  "loomi-accordion",
  {},
  { canOpenMultiple: "can-open-multiple" },
) as unknown as ForwardRefExoticComponent<
  JSX.IntrinsicElements["loomi-accordion"] & {
    canOpenMultiple?: JSX.IntrinsicElements["loomi-accordion"]["can-open-multiple"];
  }
>;
