// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import { createComponent } from "../create-component.js";

import "@loomidev/components/accordion";

export const AccordionItem: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-accordion-item"], "onLoomiAccordionToggle"> & {
    onLoomiAccordionToggle?: (e: CustomEvent) => void;
    noPadding?: JSX.IntrinsicElements["loomi-accordion-item"]["no-padding"];
  }
> = createComponent(
  "loomi-accordion-item",
  { "loomi-accordion-toggle": "onLoomiAccordionToggle" },
  { noPadding: "no-padding" },
) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-accordion-item"], "onLoomiAccordionToggle"> & {
    onLoomiAccordionToggle?: (e: CustomEvent) => void;
    noPadding?: JSX.IntrinsicElements["loomi-accordion-item"]["no-padding"];
  }
>;
