// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import { createComponent } from "../create-component.js";

import "@loomidev/components/alert";

export const Alert: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-alert"], "onClose"> & {
    onClose?: (e: CustomEvent) => void;
    showIcon?: JSX.IntrinsicElements["loomi-alert"]["show-icon"];
    showCloseIcon?: JSX.IntrinsicElements["loomi-alert"]["show-close-icon"];
    iconPlacement?: JSX.IntrinsicElements["loomi-alert"]["icon-placement"];
    showRing?: JSX.IntrinsicElements["loomi-alert"]["show-ring"];
  }
> = createComponent(
  "loomi-alert",
  { close: "onClose" },
  {
    showIcon: "show-icon",
    showCloseIcon: "show-close-icon",
    iconPlacement: "icon-placement",
    showRing: "show-ring",
  },
) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-alert"], "onClose"> & {
    onClose?: (e: CustomEvent) => void;
    showIcon?: JSX.IntrinsicElements["loomi-alert"]["show-icon"];
    showCloseIcon?: JSX.IntrinsicElements["loomi-alert"]["show-close-icon"];
    iconPlacement?: JSX.IntrinsicElements["loomi-alert"]["icon-placement"];
    showRing?: JSX.IntrinsicElements["loomi-alert"]["show-ring"];
  }
>;
