// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import { createComponent } from "../create-component.js";

import "@loomidev/components/arc-meter";

export const ArcMeter: ForwardRefExoticComponent<
  JSX.IntrinsicElements["loomi-arc-meter"] & {
    activeMarker?: JSX.IntrinsicElements["loomi-arc-meter"]["active-marker"];
    markerColor?: JSX.IntrinsicElements["loomi-arc-meter"]["marker-color"];
  }
> = createComponent(
  "loomi-arc-meter",
  {},
  { activeMarker: "active-marker", markerColor: "marker-color" },
) as unknown as ForwardRefExoticComponent<
  JSX.IntrinsicElements["loomi-arc-meter"] & {
    activeMarker?: JSX.IntrinsicElements["loomi-arc-meter"]["active-marker"];
    markerColor?: JSX.IntrinsicElements["loomi-arc-meter"]["marker-color"];
  }
>;
