// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import type { LoomiAutocompleteEventMap } from "@loomidev/components";
import { createComponent } from "../create-component.js";

import "@loomidev/components/autocomplete";

export const Autocomplete: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-autocomplete"], "onInput" | "onChange" | "onLoomiSelect"> & {
    onInput?: (e: Event) => void;
    onChange?: (e: Event) => void;
    onLoomiSelect?: (e: LoomiAutocompleteEventMap["loomi-select"]) => void;
    labelPosition?: JSX.IntrinsicElements["loomi-autocomplete"]["label-position"];
    selectedValue?: JSX.IntrinsicElements["loomi-autocomplete"]["selected-value"];
    labelKey?: JSX.IntrinsicElements["loomi-autocomplete"]["label-key"];
    valueKey?: JSX.IntrinsicElements["loomi-autocomplete"]["value-key"];
    descriptionKey?: JSX.IntrinsicElements["loomi-autocomplete"]["description-key"];
    imageKey?: JSX.IntrinsicElements["loomi-autocomplete"]["image-key"];
    showFocusRing?: JSX.IntrinsicElements["loomi-autocomplete"]["show-focus-ring"];
  }
> = createComponent(
  "loomi-autocomplete",
  { input: "onInput", change: "onChange", "loomi-select": "onLoomiSelect" },
  {
    labelPosition: "label-position",
    selectedValue: "selected-value",
    labelKey: "label-key",
    valueKey: "value-key",
    descriptionKey: "description-key",
    imageKey: "image-key",
    showFocusRing: "show-focus-ring",
  },
) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-autocomplete"], "onInput" | "onChange" | "onLoomiSelect"> & {
    onInput?: (e: Event) => void;
    onChange?: (e: Event) => void;
    onLoomiSelect?: (e: LoomiAutocompleteEventMap["loomi-select"]) => void;
    labelPosition?: JSX.IntrinsicElements["loomi-autocomplete"]["label-position"];
    selectedValue?: JSX.IntrinsicElements["loomi-autocomplete"]["selected-value"];
    labelKey?: JSX.IntrinsicElements["loomi-autocomplete"]["label-key"];
    valueKey?: JSX.IntrinsicElements["loomi-autocomplete"]["value-key"];
    descriptionKey?: JSX.IntrinsicElements["loomi-autocomplete"]["description-key"];
    imageKey?: JSX.IntrinsicElements["loomi-autocomplete"]["image-key"];
    showFocusRing?: JSX.IntrinsicElements["loomi-autocomplete"]["show-focus-ring"];
  }
>;
