// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import { createComponent } from "../create-component.js";

import "@loomidev/components/avatar";

export const Avatars: ForwardRefExoticComponent<
  JSX.IntrinsicElements["loomi-avatars"] & {
    pulseDot?: JSX.IntrinsicElements["loomi-avatars"]["pulse-dot"];
    dotColor?: JSX.IntrinsicElements["loomi-avatars"]["dot-color"];
    dotPosition?: JSX.IntrinsicElements["loomi-avatars"]["dot-position"];
    stackSpace?: JSX.IntrinsicElements["loomi-avatars"]["stack-space"];
  }
> = createComponent(
  "loomi-avatars",
  {},
  {
    pulseDot: "pulse-dot",
    dotColor: "dot-color",
    dotPosition: "dot-position",
    stackSpace: "stack-space",
  },
) as unknown as ForwardRefExoticComponent<
  JSX.IntrinsicElements["loomi-avatars"] & {
    pulseDot?: JSX.IntrinsicElements["loomi-avatars"]["pulse-dot"];
    dotColor?: JSX.IntrinsicElements["loomi-avatars"]["dot-color"];
    dotPosition?: JSX.IntrinsicElements["loomi-avatars"]["dot-position"];
    stackSpace?: JSX.IntrinsicElements["loomi-avatars"]["stack-space"];
  }
>;
