// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import { createComponent } from "../create-component.js";

import "@loomidev/components/avatar";

export const Avatar: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-avatar"], "onChange"> & {
    onChange?: (e: CustomEvent) => void;
    pulseDot?: JSX.IntrinsicElements["loomi-avatar"]["pulse-dot"];
    dotColor?: JSX.IntrinsicElements["loomi-avatar"]["dot-color"];
    dotPosition?: JSX.IntrinsicElements["loomi-avatar"]["dot-position"];
    bgColor?: JSX.IntrinsicElements["loomi-avatar"]["bg-color"];
    showRing?: JSX.IntrinsicElements["loomi-avatar"]["show-ring"];
    editLabel?: JSX.IntrinsicElements["loomi-avatar"]["edit-label"];
  }
> = createComponent(
  "loomi-avatar",
  { change: "onChange" },
  {
    pulseDot: "pulse-dot",
    dotColor: "dot-color",
    dotPosition: "dot-position",
    bgColor: "bg-color",
    showRing: "show-ring",
    editLabel: "edit-label",
  },
) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-avatar"], "onChange"> & {
    onChange?: (e: CustomEvent) => void;
    pulseDot?: JSX.IntrinsicElements["loomi-avatar"]["pulse-dot"];
    dotColor?: JSX.IntrinsicElements["loomi-avatar"]["dot-color"];
    dotPosition?: JSX.IntrinsicElements["loomi-avatar"]["dot-position"];
    bgColor?: JSX.IntrinsicElements["loomi-avatar"]["bg-color"];
    showRing?: JSX.IntrinsicElements["loomi-avatar"]["show-ring"];
    editLabel?: JSX.IntrinsicElements["loomi-avatar"]["edit-label"];
  }
>;
