// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import { createComponent } from "../create-component.js";

import "@loomidev/components/bell";

export const Bell: ForwardRefExoticComponent<
  JSX.IntrinsicElements["loomi-bell"] & {
    showDot?: JSX.IntrinsicElements["loomi-bell"]["show-dot"];
    animateDot?: JSX.IntrinsicElements["loomi-bell"]["animate-dot"];
  }
> = createComponent(
  "loomi-bell",
  {},
  { showDot: "show-dot", animateDot: "animate-dot" },
) as unknown as ForwardRefExoticComponent<
  JSX.IntrinsicElements["loomi-bell"] & {
    showDot?: JSX.IntrinsicElements["loomi-bell"]["show-dot"];
    animateDot?: JSX.IntrinsicElements["loomi-bell"]["animate-dot"];
  }
>;
