// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import { createComponent } from "../create-component.js";

import "@loomidev/components/bottom-nav";

export const BottomNavItem: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-bottom-nav-item"], "onLoomiChange"> & {
    onLoomiChange?: (e: CustomEvent) => void;
    iconSource?: JSX.IntrinsicElements["loomi-bottom-nav-item"]["icon-source"];
    preventDefault?: JSX.IntrinsicElements["loomi-bottom-nav-item"]["prevent-default"];
    activeStyle?: JSX.IntrinsicElements["loomi-bottom-nav-item"]["active-style"];
  }
> = createComponent(
  "loomi-bottom-nav-item",
  { "loomi-change": "onLoomiChange" },
  { iconSource: "icon-source", preventDefault: "prevent-default", activeStyle: "active-style" },
) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-bottom-nav-item"], "onLoomiChange"> & {
    onLoomiChange?: (e: CustomEvent) => void;
    iconSource?: JSX.IntrinsicElements["loomi-bottom-nav-item"]["icon-source"];
    preventDefault?: JSX.IntrinsicElements["loomi-bottom-nav-item"]["prevent-default"];
    activeStyle?: JSX.IntrinsicElements["loomi-bottom-nav-item"]["active-style"];
  }
>;
