// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import { createComponent } from "../create-component.js";

import "@loomidev/components/bottom-nav";

export const BottomNav: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-bottom-nav"], "onLoomiChange"> & {
    onLoomiChange?: (e: CustomEvent) => void;
    activeStyle?: JSX.IntrinsicElements["loomi-bottom-nav"]["active-style"];
    iconSource?: JSX.IntrinsicElements["loomi-bottom-nav"]["icon-source"];
    mobileOnly?: JSX.IntrinsicElements["loomi-bottom-nav"]["mobile-only"];
  }
> = createComponent(
  "loomi-bottom-nav",
  { "loomi-change": "onLoomiChange" },
  { activeStyle: "active-style", iconSource: "icon-source", mobileOnly: "mobile-only" },
) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-bottom-nav"], "onLoomiChange"> & {
    onLoomiChange?: (e: CustomEvent) => void;
    activeStyle?: JSX.IntrinsicElements["loomi-bottom-nav"]["active-style"];
    iconSource?: JSX.IntrinsicElements["loomi-bottom-nav"]["icon-source"];
    mobileOnly?: JSX.IntrinsicElements["loomi-bottom-nav"]["mobile-only"];
  }
>;
