// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import { createComponent } from "../create-component.js";

import "@loomidev/components/breadcrumb";

export const BreadcrumbItem: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-breadcrumb-item"], "onLoomiBreadcrumbItemClick"> & {
    onLoomiBreadcrumbItemClick?: (e: CustomEvent) => void;
  }
> = createComponent(
  "loomi-breadcrumb-item",
  { "loomi-breadcrumb-item-click": "onLoomiBreadcrumbItemClick" },
  {},
) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-breadcrumb-item"], "onLoomiBreadcrumbItemClick"> & {
    onLoomiBreadcrumbItemClick?: (e: CustomEvent) => void;
  }
>;
