// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import { createComponent } from "../create-component.js";

import "@loomidev/components/button";

export const Button: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-button"], "onClick"> & {
    onClick?: (e: CustomEvent) => void;
    borderWidth?: JSX.IntrinsicElements["loomi-button"]["border-width"];
    iconRight?: JSX.IntrinsicElements["loomi-button"]["icon-right"];
    hasSpinner?: JSX.IntrinsicElements["loomi-button"]["has-spinner"];
    showSpinner?: JSX.IntrinsicElements["loomi-button"]["show-spinner"];
    canSubmit?: JSX.IntrinsicElements["loomi-button"]["can-submit"];
    showFocusRing?: JSX.IntrinsicElements["loomi-button"]["show-focus-ring"];
  }
> = createComponent(
  "loomi-button",
  { click: "onClick" },
  {
    borderWidth: "border-width",
    iconRight: "icon-right",
    hasSpinner: "has-spinner",
    showSpinner: "show-spinner",
    canSubmit: "can-submit",
    showFocusRing: "show-focus-ring",
  },
) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-button"], "onClick"> & {
    onClick?: (e: CustomEvent) => void;
    borderWidth?: JSX.IntrinsicElements["loomi-button"]["border-width"];
    iconRight?: JSX.IntrinsicElements["loomi-button"]["icon-right"];
    hasSpinner?: JSX.IntrinsicElements["loomi-button"]["has-spinner"];
    showSpinner?: JSX.IntrinsicElements["loomi-button"]["show-spinner"];
    canSubmit?: JSX.IntrinsicElements["loomi-button"]["can-submit"];
    showFocusRing?: JSX.IntrinsicElements["loomi-button"]["show-focus-ring"];
  }
>;
