// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import { createComponent } from "../create-component.js";

import "@loomidev/components/button-group";

export const ButtonGroup: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-button-group"], "onLoomiButtonGroupChange"> & {
    onLoomiButtonGroupChange?: (e: CustomEvent) => void;
    iconOnly?: JSX.IntrinsicElements["loomi-button-group"]["icon-only"];
    ariaLabel?: JSX.IntrinsicElements["loomi-button-group"]["aria-label"];
  }
> = createComponent(
  "loomi-button-group",
  { "loomi-button-group-change": "onLoomiButtonGroupChange" },
  { iconOnly: "icon-only", ariaLabel: "aria-label" },
) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-button-group"], "onLoomiButtonGroupChange"> & {
    onLoomiButtonGroupChange?: (e: CustomEvent) => void;
    iconOnly?: JSX.IntrinsicElements["loomi-button-group"]["icon-only"];
    ariaLabel?: JSX.IntrinsicElements["loomi-button-group"]["aria-label"];
  }
>;
