// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import { createComponent } from "../create-component.js";

import "@loomidev/components/button-group";

export const ButtonGroupItem: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-button-group-item"], "onLoomiBgClick"> & {
    onLoomiBgClick?: (e: CustomEvent) => void;
    iconRight?: JSX.IntrinsicElements["loomi-button-group-item"]["icon-right"];
    iconOnly?: JSX.IntrinsicElements["loomi-button-group-item"]["icon-only"];
    ariaLabel?: JSX.IntrinsicElements["loomi-button-group-item"]["aria-label"];
  }
> = createComponent(
  "loomi-button-group-item",
  { "loomi-bg-click": "onLoomiBgClick" },
  { iconRight: "icon-right", iconOnly: "icon-only", ariaLabel: "aria-label" },
) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-button-group-item"], "onLoomiBgClick"> & {
    onLoomiBgClick?: (e: CustomEvent) => void;
    iconRight?: JSX.IntrinsicElements["loomi-button-group-item"]["icon-right"];
    iconOnly?: JSX.IntrinsicElements["loomi-button-group-item"]["icon-only"];
    ariaLabel?: JSX.IntrinsicElements["loomi-button-group-item"]["aria-label"];
  }
>;
