// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import type { LoomiCalendarEventMap } from "@loomidev/components";
import { createComponent } from "../create-component.js";

import "@loomidev/components/calendar";

export const Calendar: ForwardRefExoticComponent<
  Omit<
    JSX.IntrinsicElements["loomi-calendar"],
    | "onLoomiEventChange"
    | "onLoomiSlotSelect"
    | "onLoomiEventClick"
    | "onLoomiReminderClick"
    | "onLoomiViewChange"
    | "onLoomiDateChange"
    | "onLoomiSidebarToggle"
    | "onLoomiEventCreate"
    | "onLoomiEventDelete"
    | "onLoomiReminderChange"
    | "onLoomiReminderDelete"
    | "onLoomiEventDuplicate"
    | "onLoomiReminderCreate"
  > & {
    onLoomiEventChange?: (e: LoomiCalendarEventMap["loomi-event-change"]) => void;
    onLoomiSlotSelect?: (e: LoomiCalendarEventMap["loomi-slot-select"]) => void;
    onLoomiEventClick?: (e: LoomiCalendarEventMap["loomi-event-click"]) => void;
    onLoomiReminderClick?: (e: LoomiCalendarEventMap["loomi-reminder-click"]) => void;
    onLoomiViewChange?: (e: LoomiCalendarEventMap["loomi-view-change"]) => void;
    onLoomiDateChange?: (e: LoomiCalendarEventMap["loomi-date-change"]) => void;
    onLoomiSidebarToggle?: (e: LoomiCalendarEventMap["loomi-sidebar-toggle"]) => void;
    onLoomiEventCreate?: (e: LoomiCalendarEventMap["loomi-event-create"]) => void;
    onLoomiEventDelete?: (e: LoomiCalendarEventMap["loomi-event-delete"]) => void;
    onLoomiReminderChange?: (e: LoomiCalendarEventMap["loomi-reminder-change"]) => void;
    onLoomiReminderDelete?: (e: LoomiCalendarEventMap["loomi-reminder-delete"]) => void;
    onLoomiEventDuplicate?: (e: LoomiCalendarEventMap["loomi-event-duplicate"]) => void;
    onLoomiReminderCreate?: (e: LoomiCalendarEventMap["loomi-reminder-create"]) => void;
    weekStarts?: JSX.IntrinsicElements["loomi-calendar"]["week-starts"];
    showTimezone?: JSX.IntrinsicElements["loomi-calendar"]["show-timezone"];
    showWeekends?: JSX.IntrinsicElements["loomi-calendar"]["show-weekends"];
    startHour?: JSX.IntrinsicElements["loomi-calendar"]["start-hour"];
    endHour?: JSX.IntrinsicElements["loomi-calendar"]["end-hour"];
    slotMinutes?: JSX.IntrinsicElements["loomi-calendar"]["slot-minutes"];
    showSidebar?: JSX.IntrinsicElements["loomi-calendar"]["show-sidebar"];
    sidebarOpen?: JSX.IntrinsicElements["loomi-calendar"]["sidebar-open"];
  }
> = createComponent(
  "loomi-calendar",
  {
    "loomi-event-change": "onLoomiEventChange",
    "loomi-slot-select": "onLoomiSlotSelect",
    "loomi-event-click": "onLoomiEventClick",
    "loomi-reminder-click": "onLoomiReminderClick",
    "loomi-view-change": "onLoomiViewChange",
    "loomi-date-change": "onLoomiDateChange",
    "loomi-sidebar-toggle": "onLoomiSidebarToggle",
    "loomi-event-create": "onLoomiEventCreate",
    "loomi-event-delete": "onLoomiEventDelete",
    "loomi-reminder-change": "onLoomiReminderChange",
    "loomi-reminder-delete": "onLoomiReminderDelete",
    "loomi-event-duplicate": "onLoomiEventDuplicate",
    "loomi-reminder-create": "onLoomiReminderCreate",
  },
  {
    weekStarts: "week-starts",
    showTimezone: "show-timezone",
    showWeekends: "show-weekends",
    startHour: "start-hour",
    endHour: "end-hour",
    slotMinutes: "slot-minutes",
    showSidebar: "show-sidebar",
    sidebarOpen: "sidebar-open",
  },
) as unknown as ForwardRefExoticComponent<
  Omit<
    JSX.IntrinsicElements["loomi-calendar"],
    | "onLoomiEventChange"
    | "onLoomiSlotSelect"
    | "onLoomiEventClick"
    | "onLoomiReminderClick"
    | "onLoomiViewChange"
    | "onLoomiDateChange"
    | "onLoomiSidebarToggle"
    | "onLoomiEventCreate"
    | "onLoomiEventDelete"
    | "onLoomiReminderChange"
    | "onLoomiReminderDelete"
    | "onLoomiEventDuplicate"
    | "onLoomiReminderCreate"
  > & {
    onLoomiEventChange?: (e: LoomiCalendarEventMap["loomi-event-change"]) => void;
    onLoomiSlotSelect?: (e: LoomiCalendarEventMap["loomi-slot-select"]) => void;
    onLoomiEventClick?: (e: LoomiCalendarEventMap["loomi-event-click"]) => void;
    onLoomiReminderClick?: (e: LoomiCalendarEventMap["loomi-reminder-click"]) => void;
    onLoomiViewChange?: (e: LoomiCalendarEventMap["loomi-view-change"]) => void;
    onLoomiDateChange?: (e: LoomiCalendarEventMap["loomi-date-change"]) => void;
    onLoomiSidebarToggle?: (e: LoomiCalendarEventMap["loomi-sidebar-toggle"]) => void;
    onLoomiEventCreate?: (e: LoomiCalendarEventMap["loomi-event-create"]) => void;
    onLoomiEventDelete?: (e: LoomiCalendarEventMap["loomi-event-delete"]) => void;
    onLoomiReminderChange?: (e: LoomiCalendarEventMap["loomi-reminder-change"]) => void;
    onLoomiReminderDelete?: (e: LoomiCalendarEventMap["loomi-reminder-delete"]) => void;
    onLoomiEventDuplicate?: (e: LoomiCalendarEventMap["loomi-event-duplicate"]) => void;
    onLoomiReminderCreate?: (e: LoomiCalendarEventMap["loomi-reminder-create"]) => void;
    weekStarts?: JSX.IntrinsicElements["loomi-calendar"]["week-starts"];
    showTimezone?: JSX.IntrinsicElements["loomi-calendar"]["show-timezone"];
    showWeekends?: JSX.IntrinsicElements["loomi-calendar"]["show-weekends"];
    startHour?: JSX.IntrinsicElements["loomi-calendar"]["start-hour"];
    endHour?: JSX.IntrinsicElements["loomi-calendar"]["end-hour"];
    slotMinutes?: JSX.IntrinsicElements["loomi-calendar"]["slot-minutes"];
    showSidebar?: JSX.IntrinsicElements["loomi-calendar"]["show-sidebar"];
    sidebarOpen?: JSX.IntrinsicElements["loomi-calendar"]["sidebar-open"];
  }
>;
