// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import { createComponent } from "../create-component.js";

import "@loomidev/components/card";

export const CardContent: ForwardRefExoticComponent<JSX.IntrinsicElements["loomi-card-content"]> =
  createComponent("loomi-card-content", {}, {}) as unknown as ForwardRefExoticComponent<
    JSX.IntrinsicElements["loomi-card-content"]
  >;
