// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import { createComponent } from "../create-component.js";

import "@loomidev/components/card";

export const Card: ForwardRefExoticComponent<
  JSX.IntrinsicElements["loomi-card"] & {
    hasHover?: JSX.IntrinsicElements["loomi-card"]["has-hover"];
    hasShadow?: JSX.IntrinsicElements["loomi-card"]["has-shadow"];
    hasBorder?: JSX.IntrinsicElements["loomi-card"]["has-border"];
  }
> = createComponent(
  "loomi-card",
  {},
  { hasHover: "has-hover", hasShadow: "has-shadow", hasBorder: "has-border" },
) as unknown as ForwardRefExoticComponent<
  JSX.IntrinsicElements["loomi-card"] & {
    hasHover?: JSX.IntrinsicElements["loomi-card"]["has-hover"];
    hasShadow?: JSX.IntrinsicElements["loomi-card"]["has-shadow"];
    hasBorder?: JSX.IntrinsicElements["loomi-card"]["has-border"];
  }
>;
