// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import { createComponent } from "../create-component.js";

import "@loomidev/components/card";

export const CardFooter: ForwardRefExoticComponent<JSX.IntrinsicElements["loomi-card-footer"]> =
  createComponent("loomi-card-footer", {}, {}) as unknown as ForwardRefExoticComponent<
    JSX.IntrinsicElements["loomi-card-footer"]
  >;
