// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import { createComponent } from "../create-component.js";

import "@loomidev/components/centered-content";

export const CenteredContent: ForwardRefExoticComponent<
  JSX.IntrinsicElements["loomi-centered-content"] & {
    minHeight?: JSX.IntrinsicElements["loomi-centered-content"]["min-height"];
    maxWidth?: JSX.IntrinsicElements["loomi-centered-content"]["max-width"];
  }
> = createComponent(
  "loomi-centered-content",
  {},
  { minHeight: "min-height", maxWidth: "max-width" },
) as unknown as ForwardRefExoticComponent<
  JSX.IntrinsicElements["loomi-centered-content"] & {
    minHeight?: JSX.IntrinsicElements["loomi-centered-content"]["min-height"];
    maxWidth?: JSX.IntrinsicElements["loomi-centered-content"]["max-width"];
  }
>;
