// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import { createComponent } from "../create-component.js";

import "@loomidev/components/chart";

export const Chart: ForwardRefExoticComponent<
  JSX.IntrinsicElements["loomi-chart"] & {
    seriesLabel?: JSX.IntrinsicElements["loomi-chart"]["series-label"];
    series2Label?: JSX.IntrinsicElements["loomi-chart"]["series2-label"];
    series3Label?: JSX.IntrinsicElements["loomi-chart"]["series3-label"];
    series2Type?: JSX.IntrinsicElements["loomi-chart"]["series2-type"];
    showLegend?: JSX.IntrinsicElements["loomi-chart"]["show-legend"];
    legendPosition?: JSX.IntrinsicElements["loomi-chart"]["legend-position"];
    donutRadius?: JSX.IntrinsicElements["loomi-chart"]["donut-radius"];
    showBorder?: JSX.IntrinsicElements["loomi-chart"]["show-border"];
    showYAxis?: JSX.IntrinsicElements["loomi-chart"]["show-y-axis"];
    showGrid?: JSX.IntrinsicElements["loomi-chart"]["show-grid"];
    showTooltip?: JSX.IntrinsicElements["loomi-chart"]["show-tooltip"];
    withGap?: JSX.IntrinsicElements["loomi-chart"]["with-gap"];
  }
> = createComponent(
  "loomi-chart",
  {},
  {
    seriesLabel: "series-label",
    series2Label: "series2-label",
    series3Label: "series3-label",
    series2Type: "series2-type",
    showLegend: "show-legend",
    legendPosition: "legend-position",
    donutRadius: "donut-radius",
    showBorder: "show-border",
    showYAxis: "show-y-axis",
    showGrid: "show-grid",
    showTooltip: "show-tooltip",
    withGap: "with-gap",
  },
) as unknown as ForwardRefExoticComponent<
  JSX.IntrinsicElements["loomi-chart"] & {
    seriesLabel?: JSX.IntrinsicElements["loomi-chart"]["series-label"];
    series2Label?: JSX.IntrinsicElements["loomi-chart"]["series2-label"];
    series3Label?: JSX.IntrinsicElements["loomi-chart"]["series3-label"];
    series2Type?: JSX.IntrinsicElements["loomi-chart"]["series2-type"];
    showLegend?: JSX.IntrinsicElements["loomi-chart"]["show-legend"];
    legendPosition?: JSX.IntrinsicElements["loomi-chart"]["legend-position"];
    donutRadius?: JSX.IntrinsicElements["loomi-chart"]["donut-radius"];
    showBorder?: JSX.IntrinsicElements["loomi-chart"]["show-border"];
    showYAxis?: JSX.IntrinsicElements["loomi-chart"]["show-y-axis"];
    showGrid?: JSX.IntrinsicElements["loomi-chart"]["show-grid"];
    showTooltip?: JSX.IntrinsicElements["loomi-chart"]["show-tooltip"];
    withGap?: JSX.IntrinsicElements["loomi-chart"]["with-gap"];
  }
>;
