// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import { createComponent } from "../create-component.js";

import "@loomidev/components/chat";

export const ChatMessage: ForwardRefExoticComponent<
  JSX.IntrinsicElements["loomi-chat-message"] & {
    senderId?: JSX.IntrinsicElements["loomi-chat-message"]["sender-id"];
    avatarLabel?: JSX.IntrinsicElements["loomi-chat-message"]["avatar-label"];
    bubbleColor?: JSX.IntrinsicElements["loomi-chat-message"]["bubble-color"];
    showAvatar?: JSX.IntrinsicElements["loomi-chat-message"]["show-avatar"];
    showSender?: JSX.IntrinsicElements["loomi-chat-message"]["show-sender"];
  }
> = createComponent(
  "loomi-chat-message",
  {},
  {
    senderId: "sender-id",
    avatarLabel: "avatar-label",
    bubbleColor: "bubble-color",
    showAvatar: "show-avatar",
    showSender: "show-sender",
  },
) as unknown as ForwardRefExoticComponent<
  JSX.IntrinsicElements["loomi-chat-message"] & {
    senderId?: JSX.IntrinsicElements["loomi-chat-message"]["sender-id"];
    avatarLabel?: JSX.IntrinsicElements["loomi-chat-message"]["avatar-label"];
    bubbleColor?: JSX.IntrinsicElements["loomi-chat-message"]["bubble-color"];
    showAvatar?: JSX.IntrinsicElements["loomi-chat-message"]["show-avatar"];
    showSender?: JSX.IntrinsicElements["loomi-chat-message"]["show-sender"];
  }
>;
