// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import { createComponent } from "../create-component.js";

import "@loomidev/components/chat";

export const ChatWindow: ForwardRefExoticComponent<
  Omit<
    JSX.IntrinsicElements["loomi-chat-window"],
    | "onLoomiReset"
    | "onLoomiAddUser"
    | "onLoomiConversationSelect"
    | "onLoomiSend"
    | "onLoomiAttachFile"
    | "onLoomiAttachPicture"
    | "onLoomiRecord"
    | "onLoomiRecordError"
  > & {
    onLoomiReset?: (e: CustomEvent) => void;
    onLoomiAddUser?: (e: CustomEvent) => void;
    onLoomiConversationSelect?: (e: CustomEvent) => void;
    onLoomiSend?: (e: CustomEvent) => void;
    onLoomiAttachFile?: (e: CustomEvent) => void;
    onLoomiAttachPicture?: (e: CustomEvent) => void;
    onLoomiRecord?: (e: CustomEvent) => void;
    onLoomiRecordError?: (e: CustomEvent) => void;
    emptyTitle?: JSX.IntrinsicElements["loomi-chat-window"]["empty-title"];
    emptyDescription?: JSX.IntrinsicElements["loomi-chat-window"]["empty-description"];
    inputPlaceholder?: JSX.IntrinsicElements["loomi-chat-window"]["input-placeholder"];
    footerNote?: JSX.IntrinsicElements["loomi-chat-window"]["footer-note"];
    windowHeight?: JSX.IntrinsicElements["loomi-chat-window"]["window-height"];
    currentUserId?: JSX.IntrinsicElements["loomi-chat-window"]["current-user-id"];
    inputRows?: JSX.IntrinsicElements["loomi-chat-window"]["input-rows"];
    inputMaxRows?: JSX.IntrinsicElements["loomi-chat-window"]["input-max-rows"];
    loadingText?: JSX.IntrinsicElements["loomi-chat-window"]["loading-text"];
    loadingIcon?: JSX.IntrinsicElements["loomi-chat-window"]["loading-icon"];
    autoScroll?: JSX.IntrinsicElements["loomi-chat-window"]["auto-scroll"];
    showReset?: JSX.IntrinsicElements["loomi-chat-window"]["show-reset"];
    showAvatars?: JSX.IntrinsicElements["loomi-chat-window"]["show-avatars"];
    showHeaderAvatars?: JSX.IntrinsicElements["loomi-chat-window"]["show-header-avatars"];
    readOnly?: JSX.IntrinsicElements["loomi-chat-window"]["read-only"];
    activeConversationId?: JSX.IntrinsicElements["loomi-chat-window"]["active-conversation-id"];
    showConversations?: JSX.IntrinsicElements["loomi-chat-window"]["show-conversations"];
    conversationsAvatarsOnly?: JSX.IntrinsicElements["loomi-chat-window"]["conversations-avatars-only"];
  }
> = createComponent(
  "loomi-chat-window",
  {
    "loomi-reset": "onLoomiReset",
    "loomi-add-user": "onLoomiAddUser",
    "loomi-conversation-select": "onLoomiConversationSelect",
    "loomi-send": "onLoomiSend",
    "loomi-attach-file": "onLoomiAttachFile",
    "loomi-attach-picture": "onLoomiAttachPicture",
    "loomi-record": "onLoomiRecord",
    "loomi-record-error": "onLoomiRecordError",
  },
  {
    emptyTitle: "empty-title",
    emptyDescription: "empty-description",
    inputPlaceholder: "input-placeholder",
    footerNote: "footer-note",
    windowHeight: "window-height",
    currentUserId: "current-user-id",
    inputRows: "input-rows",
    inputMaxRows: "input-max-rows",
    loadingText: "loading-text",
    loadingIcon: "loading-icon",
    autoScroll: "auto-scroll",
    showReset: "show-reset",
    showAvatars: "show-avatars",
    showHeaderAvatars: "show-header-avatars",
    readOnly: "read-only",
    activeConversationId: "active-conversation-id",
    showConversations: "show-conversations",
    conversationsAvatarsOnly: "conversations-avatars-only",
  },
) as unknown as ForwardRefExoticComponent<
  Omit<
    JSX.IntrinsicElements["loomi-chat-window"],
    | "onLoomiReset"
    | "onLoomiAddUser"
    | "onLoomiConversationSelect"
    | "onLoomiSend"
    | "onLoomiAttachFile"
    | "onLoomiAttachPicture"
    | "onLoomiRecord"
    | "onLoomiRecordError"
  > & {
    onLoomiReset?: (e: CustomEvent) => void;
    onLoomiAddUser?: (e: CustomEvent) => void;
    onLoomiConversationSelect?: (e: CustomEvent) => void;
    onLoomiSend?: (e: CustomEvent) => void;
    onLoomiAttachFile?: (e: CustomEvent) => void;
    onLoomiAttachPicture?: (e: CustomEvent) => void;
    onLoomiRecord?: (e: CustomEvent) => void;
    onLoomiRecordError?: (e: CustomEvent) => void;
    emptyTitle?: JSX.IntrinsicElements["loomi-chat-window"]["empty-title"];
    emptyDescription?: JSX.IntrinsicElements["loomi-chat-window"]["empty-description"];
    inputPlaceholder?: JSX.IntrinsicElements["loomi-chat-window"]["input-placeholder"];
    footerNote?: JSX.IntrinsicElements["loomi-chat-window"]["footer-note"];
    windowHeight?: JSX.IntrinsicElements["loomi-chat-window"]["window-height"];
    currentUserId?: JSX.IntrinsicElements["loomi-chat-window"]["current-user-id"];
    inputRows?: JSX.IntrinsicElements["loomi-chat-window"]["input-rows"];
    inputMaxRows?: JSX.IntrinsicElements["loomi-chat-window"]["input-max-rows"];
    loadingText?: JSX.IntrinsicElements["loomi-chat-window"]["loading-text"];
    loadingIcon?: JSX.IntrinsicElements["loomi-chat-window"]["loading-icon"];
    autoScroll?: JSX.IntrinsicElements["loomi-chat-window"]["auto-scroll"];
    showReset?: JSX.IntrinsicElements["loomi-chat-window"]["show-reset"];
    showAvatars?: JSX.IntrinsicElements["loomi-chat-window"]["show-avatars"];
    showHeaderAvatars?: JSX.IntrinsicElements["loomi-chat-window"]["show-header-avatars"];
    readOnly?: JSX.IntrinsicElements["loomi-chat-window"]["read-only"];
    activeConversationId?: JSX.IntrinsicElements["loomi-chat-window"]["active-conversation-id"];
    showConversations?: JSX.IntrinsicElements["loomi-chat-window"]["show-conversations"];
    conversationsAvatarsOnly?: JSX.IntrinsicElements["loomi-chat-window"]["conversations-avatars-only"];
  }
>;
