// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import { createComponent } from "../create-component.js";

import "@loomidev/components/checkcards";

export const Checkcards: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-checkcards"], "onChange"> & {
    onChange?: (e: CustomEvent) => void;
    borderColor?: JSX.IntrinsicElements["loomi-checkcards"]["border-color"];
    borderWidth?: JSX.IntrinsicElements["loomi-checkcards"]["border-width"];
    selectedValue?: JSX.IntrinsicElements["loomi-checkcards"]["selected-value"];
    autoSelectNew?: JSX.IntrinsicElements["loomi-checkcards"]["auto-select-new"];
    alignItems?: JSX.IntrinsicElements["loomi-checkcards"]["align-items"];
  }
> = createComponent(
  "loomi-checkcards",
  { change: "onChange" },
  {
    borderColor: "border-color",
    borderWidth: "border-width",
    selectedValue: "selected-value",
    autoSelectNew: "auto-select-new",
    alignItems: "align-items",
  },
) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-checkcards"], "onChange"> & {
    onChange?: (e: CustomEvent) => void;
    borderColor?: JSX.IntrinsicElements["loomi-checkcards"]["border-color"];
    borderWidth?: JSX.IntrinsicElements["loomi-checkcards"]["border-width"];
    selectedValue?: JSX.IntrinsicElements["loomi-checkcards"]["selected-value"];
    autoSelectNew?: JSX.IntrinsicElements["loomi-checkcards"]["auto-select-new"];
    alignItems?: JSX.IntrinsicElements["loomi-checkcards"]["align-items"];
  }
>;
