// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import type { LoomiCheckboxEventMap } from "@loomidev/components";
import { createComponent } from "../create-component.js";

import "@loomidev/components/checkbox";

export const Checkbox: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-checkbox"], "onChange"> & {
    onChange?: (e: LoomiCheckboxEventMap["change"]) => void;
  }
> = createComponent(
  "loomi-checkbox",
  { change: "onChange" },
  {},
) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-checkbox"], "onChange"> & {
    onChange?: (e: LoomiCheckboxEventMap["change"]) => void;
  }
>;
