// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import { createComponent } from "../create-component.js";

import "@loomidev/components/checkcards";

export const Checkcard: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-checkcard"], "onLoomiCheckcardClick"> & {
    onLoomiCheckcardClick?: (e: CustomEvent) => void;
    alignItems?: JSX.IntrinsicElements["loomi-checkcard"]["align-items"];
  }
> = createComponent(
  "loomi-checkcard",
  { "loomi-checkcard-click": "onLoomiCheckcardClick" },
  { alignItems: "align-items" },
) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-checkcard"], "onLoomiCheckcardClick"> & {
    onLoomiCheckcardClick?: (e: CustomEvent) => void;
    alignItems?: JSX.IntrinsicElements["loomi-checkcard"]["align-items"];
  }
>;
