// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import { createComponent } from "../create-component.js";

import "@loomidev/components/clipboard";

export const Clipboard: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-clipboard"], "onLoomiCopied" | "onLoomiCopyError"> & {
    onLoomiCopied?: (e: CustomEvent) => void;
    onLoomiCopyError?: (e: CustomEvent) => void;
    copyLabel?: JSX.IntrinsicElements["loomi-clipboard"]["copy-label"];
    copiedLabel?: JSX.IntrinsicElements["loomi-clipboard"]["copied-label"];
  }
> = createComponent(
  "loomi-clipboard",
  { "loomi-copied": "onLoomiCopied", "loomi-copy-error": "onLoomiCopyError" },
  { copyLabel: "copy-label", copiedLabel: "copied-label" },
) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-clipboard"], "onLoomiCopied" | "onLoomiCopyError"> & {
    onLoomiCopied?: (e: CustomEvent) => void;
    onLoomiCopyError?: (e: CustomEvent) => void;
    copyLabel?: JSX.IntrinsicElements["loomi-clipboard"]["copy-label"];
    copiedLabel?: JSX.IntrinsicElements["loomi-clipboard"]["copied-label"];
  }
>;
