// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import type { LoomiColorpickerEventMap } from "@loomidev/components";
import { createComponent } from "../create-component.js";

import "@loomidev/components/colorpicker";

export const Colorpicker: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-colorpicker"], "onChange"> & {
    onChange?: (e: LoomiColorpickerEventMap["change"]) => void;
    selectedValue?: JSX.IntrinsicElements["loomi-colorpicker"]["selected-value"];
    showValue?: JSX.IntrinsicElements["loomi-colorpicker"]["show-value"];
  }
> = createComponent(
  "loomi-colorpicker",
  { change: "onChange" },
  { selectedValue: "selected-value", showValue: "show-value" },
) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-colorpicker"], "onChange"> & {
    onChange?: (e: LoomiColorpickerEventMap["change"]) => void;
    selectedValue?: JSX.IntrinsicElements["loomi-colorpicker"]["selected-value"];
    showValue?: JSX.IntrinsicElements["loomi-colorpicker"]["show-value"];
  }
>;
