// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import { createComponent } from "../create-component.js";

import "@loomidev/components/command-palette";

export const CommandPalette: ForwardRefExoticComponent<
  Omit<
    JSX.IntrinsicElements["loomi-command-palette"],
    "onLoomiCommandSelect" | "onLoomiCommandOpenChange" | "onLoomiCommandQueryChange"
  > & {
    onLoomiCommandSelect?: (e: CustomEvent) => void;
    onLoomiCommandOpenChange?: (e: CustomEvent) => void;
    onLoomiCommandQueryChange?: (e: CustomEvent) => void;
    emptyTitle?: JSX.IntrinsicElements["loomi-command-palette"]["empty-title"];
    emptyDescription?: JSX.IntrinsicElements["loomi-command-palette"]["empty-description"];
  }
> = createComponent(
  "loomi-command-palette",
  {
    "loomi-command-select": "onLoomiCommandSelect",
    "loomi-command-open-change": "onLoomiCommandOpenChange",
    "loomi-command-query-change": "onLoomiCommandQueryChange",
  },
  { emptyTitle: "empty-title", emptyDescription: "empty-description" },
) as unknown as ForwardRefExoticComponent<
  Omit<
    JSX.IntrinsicElements["loomi-command-palette"],
    "onLoomiCommandSelect" | "onLoomiCommandOpenChange" | "onLoomiCommandQueryChange"
  > & {
    onLoomiCommandSelect?: (e: CustomEvent) => void;
    onLoomiCommandOpenChange?: (e: CustomEvent) => void;
    onLoomiCommandQueryChange?: (e: CustomEvent) => void;
    emptyTitle?: JSX.IntrinsicElements["loomi-command-palette"]["empty-title"];
    emptyDescription?: JSX.IntrinsicElements["loomi-command-palette"]["empty-description"];
  }
>;
