// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import { createComponent } from "../create-component.js";

import "@loomidev/components/contact-card";

export const ContactCard: ForwardRefExoticComponent<
  JSX.IntrinsicElements["loomi-contact-card"] & {
    hasShadow?: JSX.IntrinsicElements["loomi-contact-card"]["has-shadow"];
    hasHover?: JSX.IntrinsicElements["loomi-contact-card"]["has-hover"];
    noPadding?: JSX.IntrinsicElements["loomi-contact-card"]["no-padding"];
  }
> = createComponent(
  "loomi-contact-card",
  {},
  { hasShadow: "has-shadow", hasHover: "has-hover", noPadding: "no-padding" },
) as unknown as ForwardRefExoticComponent<
  JSX.IntrinsicElements["loomi-contact-card"] & {
    hasShadow?: JSX.IntrinsicElements["loomi-contact-card"]["has-shadow"];
    hasHover?: JSX.IntrinsicElements["loomi-contact-card"]["has-hover"];
    noPadding?: JSX.IntrinsicElements["loomi-contact-card"]["no-padding"];
  }
>;
