// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import { createComponent } from "../create-component.js";

import "@loomidev/components/context-menu";

export const ContextMenuItem: ForwardRefExoticComponent<
  JSX.IntrinsicElements["loomi-context-menu-item"] & {
    iconRight?: JSX.IntrinsicElements["loomi-context-menu-item"]["icon-right"];
  }
> = createComponent(
  "loomi-context-menu-item",
  {},
  { iconRight: "icon-right" },
) as unknown as ForwardRefExoticComponent<
  JSX.IntrinsicElements["loomi-context-menu-item"] & {
    iconRight?: JSX.IntrinsicElements["loomi-context-menu-item"]["icon-right"];
  }
>;
