// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import { createComponent } from "../create-component.js";

import "@loomidev/components/context-menu";

export const ContextMenu: ForwardRefExoticComponent<
  JSX.IntrinsicElements["loomi-context-menu"] & {
    hideAfterClick?: JSX.IntrinsicElements["loomi-context-menu"]["hide-after-click"];
    iconRight?: JSX.IntrinsicElements["loomi-context-menu"]["icon-right"];
  }
> = createComponent(
  "loomi-context-menu",
  {},
  { hideAfterClick: "hide-after-click", iconRight: "icon-right" },
) as unknown as ForwardRefExoticComponent<
  JSX.IntrinsicElements["loomi-context-menu"] & {
    hideAfterClick?: JSX.IntrinsicElements["loomi-context-menu"]["hide-after-click"];
    iconRight?: JSX.IntrinsicElements["loomi-context-menu"]["icon-right"];
  }
>;
