// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import type { LoomiCountriesEventMap } from "@loomidev/components";
import { createComponent } from "../create-component.js";

import "@loomidev/components/countries";

export const Countries: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-countries"], "onChange" | "onLoomiSelect" | "onInput"> & {
    onChange?: (e: Event) => void;
    onLoomiSelect?: (e: LoomiCountriesEventMap["loomi-select"]) => void;
    onInput?: (e: CustomEvent) => void;
    labelPosition?: JSX.IntrinsicElements["loomi-countries"]["label-position"];
    emptyPlaceholder?: JSX.IntrinsicElements["loomi-countries"]["empty-placeholder"];
  }
> = createComponent(
  "loomi-countries",
  { change: "onChange", "loomi-select": "onLoomiSelect", input: "onInput" },
  { labelPosition: "label-position", emptyPlaceholder: "empty-placeholder" },
) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-countries"], "onChange" | "onLoomiSelect" | "onInput"> & {
    onChange?: (e: Event) => void;
    onLoomiSelect?: (e: LoomiCountriesEventMap["loomi-select"]) => void;
    onInput?: (e: CustomEvent) => void;
    labelPosition?: JSX.IntrinsicElements["loomi-countries"]["label-position"];
    emptyPlaceholder?: JSX.IntrinsicElements["loomi-countries"]["empty-placeholder"];
  }
>;
