// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import { createComponent } from "../create-component.js";

import "@loomidev/components/creditcard";

export const Creditcard: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-creditcard"], "onLoomiFlip" | "onInput" | "onChange"> & {
    onLoomiFlip?: (e: CustomEvent) => void;
    onInput?: (e: CustomEvent) => void;
    onChange?: (e: CustomEvent) => void;
    cardholderName?: JSX.IntrinsicElements["loomi-creditcard"]["cardholder-name"];
    expiryMonth?: JSX.IntrinsicElements["loomi-creditcard"]["expiry-month"];
    expiryYear?: JSX.IntrinsicElements["loomi-creditcard"]["expiry-year"];
    errorMessage?: JSX.IntrinsicElements["loomi-creditcard"]["error-message"];
    showErrorInline?: JSX.IntrinsicElements["loomi-creditcard"]["show-error-inline"];
  }
> = createComponent(
  "loomi-creditcard",
  { "loomi-flip": "onLoomiFlip", input: "onInput", change: "onChange" },
  {
    cardholderName: "cardholder-name",
    expiryMonth: "expiry-month",
    expiryYear: "expiry-year",
    errorMessage: "error-message",
    showErrorInline: "show-error-inline",
  },
) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-creditcard"], "onLoomiFlip" | "onInput" | "onChange"> & {
    onLoomiFlip?: (e: CustomEvent) => void;
    onInput?: (e: CustomEvent) => void;
    onChange?: (e: CustomEvent) => void;
    cardholderName?: JSX.IntrinsicElements["loomi-creditcard"]["cardholder-name"];
    expiryMonth?: JSX.IntrinsicElements["loomi-creditcard"]["expiry-month"];
    expiryYear?: JSX.IntrinsicElements["loomi-creditcard"]["expiry-year"];
    errorMessage?: JSX.IntrinsicElements["loomi-creditcard"]["error-message"];
    showErrorInline?: JSX.IntrinsicElements["loomi-creditcard"]["show-error-inline"];
  }
>;
