// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import type { DataGridEventMap } from "@loomidev/components";
import { createComponent } from "../create-component.js";

import "@loomidev/components/data-grid";

export const DataGrid: ForwardRefExoticComponent<
  Omit<
    JSX.IntrinsicElements["loomi-data-grid"],
    | "onLoomiPageChange"
    | "onLoomiSortChange"
    | "onLoomiSelectionChange"
    | "onLoomiRowAction"
    | "onLoomiCellEdit"
    | "onLoomiColumnResize"
    | "onLoomiSavedViewChange"
    | "onLoomiGridToggleRow"
    | "onLoomiExportRequest"
  > & {
    onLoomiPageChange?: (e: DataGridEventMap["loomi-page-change"]) => void;
    onLoomiSortChange?: (e: DataGridEventMap["loomi-sort-change"]) => void;
    onLoomiSelectionChange?: (e: DataGridEventMap["loomi-selection-change"]) => void;
    onLoomiRowAction?: (e: DataGridEventMap["loomi-row-action"]) => void;
    onLoomiCellEdit?: (e: DataGridEventMap["loomi-cell-edit"]) => void;
    onLoomiColumnResize?: (e: DataGridEventMap["loomi-column-resize"]) => void;
    onLoomiSavedViewChange?: (e: DataGridEventMap["loomi-saved-view-change"]) => void;
    onLoomiGridToggleRow?: (e: DataGridEventMap["loomi-grid-toggle-row"]) => void;
    onLoomiExportRequest?: (e: DataGridEventMap["loomi-export-request"]) => void;
    rowKey?: JSX.IntrinsicElements["loomi-data-grid"]["row-key"];
    emptyTitle?: JSX.IntrinsicElements["loomi-data-grid"]["empty-title"];
    emptyDescription?: JSX.IntrinsicElements["loomi-data-grid"]["empty-description"];
    maxHeight?: JSX.IntrinsicElements["loomi-data-grid"]["max-height"];
    pageSize?: JSX.IntrinsicElements["loomi-data-grid"]["page-size"];
    totalRows?: JSX.IntrinsicElements["loomi-data-grid"]["total-rows"];
    serverSide?: JSX.IntrinsicElements["loomi-data-grid"]["server-side"];
    stickyHeader?: JSX.IntrinsicElements["loomi-data-grid"]["sticky-header"];
  }
> = createComponent(
  "loomi-data-grid",
  {
    "loomi-page-change": "onLoomiPageChange",
    "loomi-sort-change": "onLoomiSortChange",
    "loomi-selection-change": "onLoomiSelectionChange",
    "loomi-row-action": "onLoomiRowAction",
    "loomi-cell-edit": "onLoomiCellEdit",
    "loomi-column-resize": "onLoomiColumnResize",
    "loomi-saved-view-change": "onLoomiSavedViewChange",
    "loomi-grid-toggle-row": "onLoomiGridToggleRow",
    "loomi-export-request": "onLoomiExportRequest",
  },
  {
    rowKey: "row-key",
    emptyTitle: "empty-title",
    emptyDescription: "empty-description",
    maxHeight: "max-height",
    pageSize: "page-size",
    totalRows: "total-rows",
    serverSide: "server-side",
    stickyHeader: "sticky-header",
  },
) as unknown as ForwardRefExoticComponent<
  Omit<
    JSX.IntrinsicElements["loomi-data-grid"],
    | "onLoomiPageChange"
    | "onLoomiSortChange"
    | "onLoomiSelectionChange"
    | "onLoomiRowAction"
    | "onLoomiCellEdit"
    | "onLoomiColumnResize"
    | "onLoomiSavedViewChange"
    | "onLoomiGridToggleRow"
    | "onLoomiExportRequest"
  > & {
    onLoomiPageChange?: (e: DataGridEventMap["loomi-page-change"]) => void;
    onLoomiSortChange?: (e: DataGridEventMap["loomi-sort-change"]) => void;
    onLoomiSelectionChange?: (e: DataGridEventMap["loomi-selection-change"]) => void;
    onLoomiRowAction?: (e: DataGridEventMap["loomi-row-action"]) => void;
    onLoomiCellEdit?: (e: DataGridEventMap["loomi-cell-edit"]) => void;
    onLoomiColumnResize?: (e: DataGridEventMap["loomi-column-resize"]) => void;
    onLoomiSavedViewChange?: (e: DataGridEventMap["loomi-saved-view-change"]) => void;
    onLoomiGridToggleRow?: (e: DataGridEventMap["loomi-grid-toggle-row"]) => void;
    onLoomiExportRequest?: (e: DataGridEventMap["loomi-export-request"]) => void;
    rowKey?: JSX.IntrinsicElements["loomi-data-grid"]["row-key"];
    emptyTitle?: JSX.IntrinsicElements["loomi-data-grid"]["empty-title"];
    emptyDescription?: JSX.IntrinsicElements["loomi-data-grid"]["empty-description"];
    maxHeight?: JSX.IntrinsicElements["loomi-data-grid"]["max-height"];
    pageSize?: JSX.IntrinsicElements["loomi-data-grid"]["page-size"];
    totalRows?: JSX.IntrinsicElements["loomi-data-grid"]["total-rows"];
    serverSide?: JSX.IntrinsicElements["loomi-data-grid"]["server-side"];
    stickyHeader?: JSX.IntrinsicElements["loomi-data-grid"]["sticky-header"];
  }
>;
