// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import type { LoomiDatepickerEventMap } from "@loomidev/components";
import { createComponent } from "../create-component.js";

import "@loomidev/components/datepicker";

export const Datepicker: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-datepicker"], "onChange"> & {
    onChange?: (e: LoomiDatepickerEventMap["change"]) => void;
    dpStyle?: JSX.IntrinsicElements["loomi-datepicker"]["dp-style"];
    selectedValue?: JSX.IntrinsicElements["loomi-datepicker"]["selected-value"];
    minDate?: JSX.IntrinsicElements["loomi-datepicker"]["min-date"];
    maxDate?: JSX.IntrinsicElements["loomi-datepicker"]["max-date"];
    labelPosition?: JSX.IntrinsicElements["loomi-datepicker"]["label-position"];
    weekStarts?: JSX.IntrinsicElements["loomi-datepicker"]["week-starts"];
  }
> = createComponent(
  "loomi-datepicker",
  { change: "onChange" },
  {
    dpStyle: "dp-style",
    selectedValue: "selected-value",
    minDate: "min-date",
    maxDate: "max-date",
    labelPosition: "label-position",
    weekStarts: "week-starts",
  },
) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-datepicker"], "onChange"> & {
    onChange?: (e: LoomiDatepickerEventMap["change"]) => void;
    dpStyle?: JSX.IntrinsicElements["loomi-datepicker"]["dp-style"];
    selectedValue?: JSX.IntrinsicElements["loomi-datepicker"]["selected-value"];
    minDate?: JSX.IntrinsicElements["loomi-datepicker"]["min-date"];
    maxDate?: JSX.IntrinsicElements["loomi-datepicker"]["max-date"];
    labelPosition?: JSX.IntrinsicElements["loomi-datepicker"]["label-position"];
    weekStarts?: JSX.IntrinsicElements["loomi-datepicker"]["week-starts"];
  }
>;
