// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import { createComponent } from "../create-component.js";

import "@loomidev/components/date-range-picker";

export const DateRangePicker: ForwardRefExoticComponent<
  Omit<
    JSX.IntrinsicElements["loomi-date-range-picker"],
    "onLoomiDateRangeChange" | "onLoomiDateRangeApply" | "onLoomiDateRangeOpenChange"
  > & {
    onLoomiDateRangeChange?: (e: CustomEvent) => void;
    onLoomiDateRangeApply?: (e: CustomEvent) => void;
    onLoomiDateRangeOpenChange?: (e: CustomEvent) => void;
    startDate?: JSX.IntrinsicElements["loomi-date-range-picker"]["start-date"];
    endDate?: JSX.IntrinsicElements["loomi-date-range-picker"]["end-date"];
    compareStartDate?: JSX.IntrinsicElements["loomi-date-range-picker"]["compare-start-date"];
    compareEndDate?: JSX.IntrinsicElements["loomi-date-range-picker"]["compare-end-date"];
    presetId?: JSX.IntrinsicElements["loomi-date-range-picker"]["preset-id"];
    showPresets?: JSX.IntrinsicElements["loomi-date-range-picker"]["show-presets"];
  }
> = createComponent(
  "loomi-date-range-picker",
  {
    "loomi-date-range-change": "onLoomiDateRangeChange",
    "loomi-date-range-apply": "onLoomiDateRangeApply",
    "loomi-date-range-open-change": "onLoomiDateRangeOpenChange",
  },
  {
    startDate: "start-date",
    endDate: "end-date",
    compareStartDate: "compare-start-date",
    compareEndDate: "compare-end-date",
    presetId: "preset-id",
    showPresets: "show-presets",
  },
) as unknown as ForwardRefExoticComponent<
  Omit<
    JSX.IntrinsicElements["loomi-date-range-picker"],
    "onLoomiDateRangeChange" | "onLoomiDateRangeApply" | "onLoomiDateRangeOpenChange"
  > & {
    onLoomiDateRangeChange?: (e: CustomEvent) => void;
    onLoomiDateRangeApply?: (e: CustomEvent) => void;
    onLoomiDateRangeOpenChange?: (e: CustomEvent) => void;
    startDate?: JSX.IntrinsicElements["loomi-date-range-picker"]["start-date"];
    endDate?: JSX.IntrinsicElements["loomi-date-range-picker"]["end-date"];
    compareStartDate?: JSX.IntrinsicElements["loomi-date-range-picker"]["compare-start-date"];
    compareEndDate?: JSX.IntrinsicElements["loomi-date-range-picker"]["compare-end-date"];
    presetId?: JSX.IntrinsicElements["loomi-date-range-picker"]["preset-id"];
    showPresets?: JSX.IntrinsicElements["loomi-date-range-picker"]["show-presets"];
  }
>;
