// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import type { LoomiDrawerEventMap } from "@loomidev/components";
import { createComponent } from "../create-component.js";

import "@loomidev/components/drawer";

export const Drawer: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-drawer"], "onOpen" | "onClose"> & {
    onOpen?: (e: LoomiDrawerEventMap["open"]) => void;
    onClose?: (e: LoomiDrawerEventMap["close"]) => void;
    showCloseIcon?: JSX.IntrinsicElements["loomi-drawer"]["show-close-icon"];
    closeOnOutsideClick?: JSX.IntrinsicElements["loomi-drawer"]["close-on-outside-click"];
    preventScroll?: JSX.IntrinsicElements["loomi-drawer"]["prevent-scroll"];
  }
> = createComponent(
  "loomi-drawer",
  { open: "onOpen", close: "onClose" },
  {
    showCloseIcon: "show-close-icon",
    closeOnOutsideClick: "close-on-outside-click",
    preventScroll: "prevent-scroll",
  },
) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-drawer"], "onOpen" | "onClose"> & {
    onOpen?: (e: LoomiDrawerEventMap["open"]) => void;
    onClose?: (e: LoomiDrawerEventMap["close"]) => void;
    showCloseIcon?: JSX.IntrinsicElements["loomi-drawer"]["show-close-icon"];
    closeOnOutsideClick?: JSX.IntrinsicElements["loomi-drawer"]["close-on-outside-click"];
    preventScroll?: JSX.IntrinsicElements["loomi-drawer"]["prevent-scroll"];
  }
>;
