// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import { createComponent } from "../create-component.js";

import "@loomidev/components/dropmenu";

export const Dropmenu: ForwardRefExoticComponent<
  JSX.IntrinsicElements["loomi-dropmenu"] & {
    triggerOn?: JSX.IntrinsicElements["loomi-dropmenu"]["trigger-on"];
    hideAfterClick?: JSX.IntrinsicElements["loomi-dropmenu"]["hide-after-click"];
    iconRight?: JSX.IntrinsicElements["loomi-dropmenu"]["icon-right"];
  }
> = createComponent(
  "loomi-dropmenu",
  {},
  { triggerOn: "trigger-on", hideAfterClick: "hide-after-click", iconRight: "icon-right" },
) as unknown as ForwardRefExoticComponent<
  JSX.IntrinsicElements["loomi-dropmenu"] & {
    triggerOn?: JSX.IntrinsicElements["loomi-dropmenu"]["trigger-on"];
    hideAfterClick?: JSX.IntrinsicElements["loomi-dropmenu"]["hide-after-click"];
    iconRight?: JSX.IntrinsicElements["loomi-dropmenu"]["icon-right"];
  }
>;
