// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import { createComponent } from "../create-component.js";

import "@loomidev/components/dropmenu";

export const DropmenuItem: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-dropmenu-item"], "onChange"> & {
    onChange?: (e: CustomEvent) => void;
    iconRight?: JSX.IntrinsicElements["loomi-dropmenu-item"]["icon-right"];
  }
> = createComponent(
  "loomi-dropmenu-item",
  { change: "onChange" },
  { iconRight: "icon-right" },
) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-dropmenu-item"], "onChange"> & {
    onChange?: (e: CustomEvent) => void;
    iconRight?: JSX.IntrinsicElements["loomi-dropmenu-item"]["icon-right"];
  }
>;
