// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import { createComponent } from "../create-component.js";

import "@loomidev/components/emoji-picker";

export const EmojiPicker: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-emoji-picker"], "onLoomiEmojiSelect" | "onChange"> & {
    onLoomiEmojiSelect?: (e: CustomEvent) => void;
    onChange?: (e: CustomEvent) => void;
    selectedValue?: JSX.IntrinsicElements["loomi-emoji-picker"]["selected-value"];
    emptyText?: JSX.IntrinsicElements["loomi-emoji-picker"]["empty-text"];
    showCategories?: JSX.IntrinsicElements["loomi-emoji-picker"]["show-categories"];
    showText?: JSX.IntrinsicElements["loomi-emoji-picker"]["show-text"];
  }
> = createComponent(
  "loomi-emoji-picker",
  { "loomi-emoji-select": "onLoomiEmojiSelect", change: "onChange" },
  {
    selectedValue: "selected-value",
    emptyText: "empty-text",
    showCategories: "show-categories",
    showText: "show-text",
  },
) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-emoji-picker"], "onLoomiEmojiSelect" | "onChange"> & {
    onLoomiEmojiSelect?: (e: CustomEvent) => void;
    onChange?: (e: CustomEvent) => void;
    selectedValue?: JSX.IntrinsicElements["loomi-emoji-picker"]["selected-value"];
    emptyText?: JSX.IntrinsicElements["loomi-emoji-picker"]["empty-text"];
    showCategories?: JSX.IntrinsicElements["loomi-emoji-picker"]["show-categories"];
    showText?: JSX.IntrinsicElements["loomi-emoji-picker"]["show-text"];
  }
>;
