// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import { createComponent } from "../create-component.js";

import "@loomidev/components/empty-state";

export const EmptyState: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-empty-state"], "onAction"> & {
    onAction?: (e: Event) => void;
    buttonLabel?: JSX.IntrinsicElements["loomi-empty-state"]["button-label"];
    showImage?: JSX.IntrinsicElements["loomi-empty-state"]["show-image"];
    imageSize?: JSX.IntrinsicElements["loomi-empty-state"]["image-size"];
  }
> = createComponent(
  "loomi-empty-state",
  { action: "onAction" },
  { buttonLabel: "button-label", showImage: "show-image", imageSize: "image-size" },
) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-empty-state"], "onAction"> & {
    onAction?: (e: Event) => void;
    buttonLabel?: JSX.IntrinsicElements["loomi-empty-state"]["button-label"];
    showImage?: JSX.IntrinsicElements["loomi-empty-state"]["show-image"];
    imageSize?: JSX.IntrinsicElements["loomi-empty-state"]["image-size"];
  }
>;
