// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import type { LoomiFabEventMap } from "@loomidev/components";
import { createComponent } from "../create-component.js";

import "@loomidev/components/fab";

export const FabItem: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-fab-item"], "onLoomiSelect"> & {
    onLoomiSelect?: (e: LoomiFabEventMap["loomi-select"]) => void;
    iconSource?: JSX.IntrinsicElements["loomi-fab-item"]["icon-source"];
  }
> = createComponent(
  "loomi-fab-item",
  { "loomi-select": "onLoomiSelect" },
  { iconSource: "icon-source" },
) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-fab-item"], "onLoomiSelect"> & {
    onLoomiSelect?: (e: LoomiFabEventMap["loomi-select"]) => void;
    iconSource?: JSX.IntrinsicElements["loomi-fab-item"]["icon-source"];
  }
>;
