// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import { createComponent } from "../create-component.js";

import "@loomidev/components/fab";

export const Fab: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-fab"], "onOpen" | "onClose"> & {
    onOpen?: (e: Event) => void;
    onClose?: (e: Event) => void;
    iconSource?: JSX.IntrinsicElements["loomi-fab"]["icon-source"];
    iconsOnly?: JSX.IntrinsicElements["loomi-fab"]["icons-only"];
    closeOnSelect?: JSX.IntrinsicElements["loomi-fab"]["close-on-select"];
  }
> = createComponent(
  "loomi-fab",
  { open: "onOpen", close: "onClose" },
  { iconSource: "icon-source", iconsOnly: "icons-only", closeOnSelect: "close-on-select" },
) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-fab"], "onOpen" | "onClose"> & {
    onOpen?: (e: Event) => void;
    onClose?: (e: Event) => void;
    iconSource?: JSX.IntrinsicElements["loomi-fab"]["icon-source"];
    iconsOnly?: JSX.IntrinsicElements["loomi-fab"]["icons-only"];
    closeOnSelect?: JSX.IntrinsicElements["loomi-fab"]["close-on-select"];
  }
>;
