// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import type { LoomiFilepickerEventMap } from "@loomidev/components";
import { createComponent } from "../create-component.js";

import "@loomidev/components/filepicker";

export const Filepicker: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-filepicker"], "onChange"> & {
    onChange?: (e: LoomiFilepickerEventMap["change"]) => void;
    acceptedFileTypes?: JSX.IntrinsicElements["loomi-filepicker"]["accepted-file-types"];
    placeholderLine1?: JSX.IntrinsicElements["loomi-filepicker"]["placeholder-line1"];
    placeholderLine2?: JSX.IntrinsicElements["loomi-filepicker"]["placeholder-line2"];
    maxFiles?: JSX.IntrinsicElements["loomi-filepicker"]["max-files"];
    maxFileSize?: JSX.IntrinsicElements["loomi-filepicker"]["max-file-size"];
    canBrowse?: JSX.IntrinsicElements["loomi-filepicker"]["can-browse"];
    canDrop?: JSX.IntrinsicElements["loomi-filepicker"]["can-drop"];
    showImagePreview?: JSX.IntrinsicElements["loomi-filepicker"]["show-image-preview"];
    cropAspectRatio?: JSX.IntrinsicElements["loomi-filepicker"]["crop-aspect-ratio"];
    resizeWidth?: JSX.IntrinsicElements["loomi-filepicker"]["resize-width"];
    resizeHeight?: JSX.IntrinsicElements["loomi-filepicker"]["resize-height"];
    hasBorder?: JSX.IntrinsicElements["loomi-filepicker"]["has-border"];
  }
> = createComponent(
  "loomi-filepicker",
  { change: "onChange" },
  {
    acceptedFileTypes: "accepted-file-types",
    placeholderLine1: "placeholder-line1",
    placeholderLine2: "placeholder-line2",
    maxFiles: "max-files",
    maxFileSize: "max-file-size",
    canBrowse: "can-browse",
    canDrop: "can-drop",
    showImagePreview: "show-image-preview",
    cropAspectRatio: "crop-aspect-ratio",
    resizeWidth: "resize-width",
    resizeHeight: "resize-height",
    hasBorder: "has-border",
  },
) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-filepicker"], "onChange"> & {
    onChange?: (e: LoomiFilepickerEventMap["change"]) => void;
    acceptedFileTypes?: JSX.IntrinsicElements["loomi-filepicker"]["accepted-file-types"];
    placeholderLine1?: JSX.IntrinsicElements["loomi-filepicker"]["placeholder-line1"];
    placeholderLine2?: JSX.IntrinsicElements["loomi-filepicker"]["placeholder-line2"];
    maxFiles?: JSX.IntrinsicElements["loomi-filepicker"]["max-files"];
    maxFileSize?: JSX.IntrinsicElements["loomi-filepicker"]["max-file-size"];
    canBrowse?: JSX.IntrinsicElements["loomi-filepicker"]["can-browse"];
    canDrop?: JSX.IntrinsicElements["loomi-filepicker"]["can-drop"];
    showImagePreview?: JSX.IntrinsicElements["loomi-filepicker"]["show-image-preview"];
    cropAspectRatio?: JSX.IntrinsicElements["loomi-filepicker"]["crop-aspect-ratio"];
    resizeWidth?: JSX.IntrinsicElements["loomi-filepicker"]["resize-width"];
    resizeHeight?: JSX.IntrinsicElements["loomi-filepicker"]["resize-height"];
    hasBorder?: JSX.IntrinsicElements["loomi-filepicker"]["has-border"];
  }
>;
