// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import { createComponent } from "../create-component.js";

import "@loomidev/components/filter-builder";

export const FilterBuilder: ForwardRefExoticComponent<
  Omit<
    JSX.IntrinsicElements["loomi-filter-builder"],
    "onLoomiFilterChange" | "onLoomiFilterApply"
  > & {
    onLoomiFilterChange?: (e: CustomEvent) => void;
    onLoomiFilterApply?: (e: CustomEvent) => void;
    addLabel?: JSX.IntrinsicElements["loomi-filter-builder"]["add-label"];
    applyLabel?: JSX.IntrinsicElements["loomi-filter-builder"]["apply-label"];
    emptyLabel?: JSX.IntrinsicElements["loomi-filter-builder"]["empty-label"];
    showApply?: JSX.IntrinsicElements["loomi-filter-builder"]["show-apply"];
  }
> = createComponent(
  "loomi-filter-builder",
  { "loomi-filter-change": "onLoomiFilterChange", "loomi-filter-apply": "onLoomiFilterApply" },
  {
    addLabel: "add-label",
    applyLabel: "apply-label",
    emptyLabel: "empty-label",
    showApply: "show-apply",
  },
) as unknown as ForwardRefExoticComponent<
  Omit<
    JSX.IntrinsicElements["loomi-filter-builder"],
    "onLoomiFilterChange" | "onLoomiFilterApply"
  > & {
    onLoomiFilterChange?: (e: CustomEvent) => void;
    onLoomiFilterApply?: (e: CustomEvent) => void;
    addLabel?: JSX.IntrinsicElements["loomi-filter-builder"]["add-label"];
    applyLabel?: JSX.IntrinsicElements["loomi-filter-builder"]["apply-label"];
    emptyLabel?: JSX.IntrinsicElements["loomi-filter-builder"]["empty-label"];
    showApply?: JSX.IntrinsicElements["loomi-filter-builder"]["show-apply"];
  }
>;
