// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import { createComponent } from "../create-component.js";

import "@loomidev/components/floating-panel";

export const FloatingPanel: ForwardRefExoticComponent<
  Omit<
    JSX.IntrinsicElements["loomi-floating-panel"],
    "onOpen" | "onClose" | "onLoomiDrag" | "onLoomiResize" | "onLoomiMinimize" | "onLoomiMaximize"
  > & {
    onOpen?: (e: Event) => void;
    onClose?: (e: Event) => void;
    onLoomiDrag?: (e: CustomEvent) => void;
    onLoomiResize?: (e: CustomEvent) => void;
    onLoomiMinimize?: (e: CustomEvent) => void;
    onLoomiMaximize?: (e: CustomEvent) => void;
    showCloseIcon?: JSX.IntrinsicElements["loomi-floating-panel"]["show-close-icon"];
    noDrag?: JSX.IntrinsicElements["loomi-floating-panel"]["no-drag"];
    dragHandle?: JSX.IntrinsicElements["loomi-floating-panel"]["drag-handle"];
    minWidth?: JSX.IntrinsicElements["loomi-floating-panel"]["min-width"];
    minHeight?: JSX.IntrinsicElements["loomi-floating-panel"]["min-height"];
    maxWidth?: JSX.IntrinsicElements["loomi-floating-panel"]["max-width"];
    maxHeight?: JSX.IntrinsicElements["loomi-floating-panel"]["max-height"];
    autoSaveId?: JSX.IntrinsicElements["loomi-floating-panel"]["auto-save-id"];
  }
> = createComponent(
  "loomi-floating-panel",
  {
    open: "onOpen",
    close: "onClose",
    "loomi-drag": "onLoomiDrag",
    "loomi-resize": "onLoomiResize",
    "loomi-minimize": "onLoomiMinimize",
    "loomi-maximize": "onLoomiMaximize",
  },
  {
    showCloseIcon: "show-close-icon",
    noDrag: "no-drag",
    dragHandle: "drag-handle",
    minWidth: "min-width",
    minHeight: "min-height",
    maxWidth: "max-width",
    maxHeight: "max-height",
    autoSaveId: "auto-save-id",
  },
) as unknown as ForwardRefExoticComponent<
  Omit<
    JSX.IntrinsicElements["loomi-floating-panel"],
    "onOpen" | "onClose" | "onLoomiDrag" | "onLoomiResize" | "onLoomiMinimize" | "onLoomiMaximize"
  > & {
    onOpen?: (e: Event) => void;
    onClose?: (e: Event) => void;
    onLoomiDrag?: (e: CustomEvent) => void;
    onLoomiResize?: (e: CustomEvent) => void;
    onLoomiMinimize?: (e: CustomEvent) => void;
    onLoomiMaximize?: (e: CustomEvent) => void;
    showCloseIcon?: JSX.IntrinsicElements["loomi-floating-panel"]["show-close-icon"];
    noDrag?: JSX.IntrinsicElements["loomi-floating-panel"]["no-drag"];
    dragHandle?: JSX.IntrinsicElements["loomi-floating-panel"]["drag-handle"];
    minWidth?: JSX.IntrinsicElements["loomi-floating-panel"]["min-width"];
    minHeight?: JSX.IntrinsicElements["loomi-floating-panel"]["min-height"];
    maxWidth?: JSX.IntrinsicElements["loomi-floating-panel"]["max-width"];
    maxHeight?: JSX.IntrinsicElements["loomi-floating-panel"]["max-height"];
    autoSaveId?: JSX.IntrinsicElements["loomi-floating-panel"]["auto-save-id"];
  }
>;
