// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import { createComponent } from "../create-component.js";

import "@loomidev/components/horizontal-line-graph";

export const HorizontalLineGraph: ForwardRefExoticComponent<
  JSX.IntrinsicElements["loomi-horizontal-line-graph"] & {
    showLegend?: JSX.IntrinsicElements["loomi-horizontal-line-graph"]["show-legend"];
    showValues?: JSX.IntrinsicElements["loomi-horizontal-line-graph"]["show-values"];
  }
> = createComponent(
  "loomi-horizontal-line-graph",
  {},
  { showLegend: "show-legend", showValues: "show-values" },
) as unknown as ForwardRefExoticComponent<
  JSX.IntrinsicElements["loomi-horizontal-line-graph"] & {
    showLegend?: JSX.IntrinsicElements["loomi-horizontal-line-graph"]["show-legend"];
    showValues?: JSX.IntrinsicElements["loomi-horizontal-line-graph"]["show-values"];
  }
>;
