// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import { createComponent } from "../create-component.js";

import "@loomidev/components/icon";

export const Icon: ForwardRefExoticComponent<
  JSX.IntrinsicElements["loomi-icon"] & {
    strokeWidth?: JSX.IntrinsicElements["loomi-icon"]["stroke-width"];
  }
> = createComponent(
  "loomi-icon",
  {},
  { strokeWidth: "stroke-width" },
) as unknown as ForwardRefExoticComponent<
  JSX.IntrinsicElements["loomi-icon"] & {
    strokeWidth?: JSX.IntrinsicElements["loomi-icon"]["stroke-width"];
  }
>;
