// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import { createComponent } from "../create-component.js";

import "@loomidev/components/input";

export const Input: ForwardRefExoticComponent<
  Omit<
    JSX.IntrinsicElements["loomi-input"],
    "onInput" | "onChange" | "onLoomiPrefixChange" | "onLoomiSuffixChange"
  > & {
    onInput?: (e: CustomEvent) => void;
    onChange?: (e: CustomEvent) => void;
    onLoomiPrefixChange?: (e: CustomEvent) => void;
    onLoomiSuffixChange?: (e: CustomEvent) => void;
    labelPosition?: JSX.IntrinsicElements["loomi-input"]["label-position"];
    withDots?: JSX.IntrinsicElements["loomi-input"]["with-dots"];
    dynamicMask?: JSX.IntrinsicElements["loomi-input"]["dynamic-mask"];
    prefixOptions?: JSX.IntrinsicElements["loomi-input"]["prefix-options"];
    suffixOptions?: JSX.IntrinsicElements["loomi-input"]["suffix-options"];
    prefixValue?: JSX.IntrinsicElements["loomi-input"]["prefix-value"];
    suffixValue?: JSX.IntrinsicElements["loomi-input"]["suffix-value"];
    prefixIcon?: JSX.IntrinsicElements["loomi-input"]["prefix-icon"];
    suffixIcon?: JSX.IntrinsicElements["loomi-input"]["suffix-icon"];
    transparentPrefix?: JSX.IntrinsicElements["loomi-input"]["transparent-prefix"];
    transparentSuffix?: JSX.IntrinsicElements["loomi-input"]["transparent-suffix"];
    errorMessage?: JSX.IntrinsicElements["loomi-input"]["error-message"];
    showErrorInline?: JSX.IntrinsicElements["loomi-input"]["show-error-inline"];
    showPlaceholderAlways?: JSX.IntrinsicElements["loomi-input"]["show-placeholder-always"];
    showFocusRing?: JSX.IntrinsicElements["loomi-input"]["show-focus-ring"];
  }
> = createComponent(
  "loomi-input",
  {
    input: "onInput",
    change: "onChange",
    "loomi-prefix-change": "onLoomiPrefixChange",
    "loomi-suffix-change": "onLoomiSuffixChange",
  },
  {
    labelPosition: "label-position",
    withDots: "with-dots",
    dynamicMask: "dynamic-mask",
    prefixOptions: "prefix-options",
    suffixOptions: "suffix-options",
    prefixValue: "prefix-value",
    suffixValue: "suffix-value",
    prefixIcon: "prefix-icon",
    suffixIcon: "suffix-icon",
    transparentPrefix: "transparent-prefix",
    transparentSuffix: "transparent-suffix",
    errorMessage: "error-message",
    showErrorInline: "show-error-inline",
    showPlaceholderAlways: "show-placeholder-always",
    showFocusRing: "show-focus-ring",
  },
) as unknown as ForwardRefExoticComponent<
  Omit<
    JSX.IntrinsicElements["loomi-input"],
    "onInput" | "onChange" | "onLoomiPrefixChange" | "onLoomiSuffixChange"
  > & {
    onInput?: (e: CustomEvent) => void;
    onChange?: (e: CustomEvent) => void;
    onLoomiPrefixChange?: (e: CustomEvent) => void;
    onLoomiSuffixChange?: (e: CustomEvent) => void;
    labelPosition?: JSX.IntrinsicElements["loomi-input"]["label-position"];
    withDots?: JSX.IntrinsicElements["loomi-input"]["with-dots"];
    dynamicMask?: JSX.IntrinsicElements["loomi-input"]["dynamic-mask"];
    prefixOptions?: JSX.IntrinsicElements["loomi-input"]["prefix-options"];
    suffixOptions?: JSX.IntrinsicElements["loomi-input"]["suffix-options"];
    prefixValue?: JSX.IntrinsicElements["loomi-input"]["prefix-value"];
    suffixValue?: JSX.IntrinsicElements["loomi-input"]["suffix-value"];
    prefixIcon?: JSX.IntrinsicElements["loomi-input"]["prefix-icon"];
    suffixIcon?: JSX.IntrinsicElements["loomi-input"]["suffix-icon"];
    transparentPrefix?: JSX.IntrinsicElements["loomi-input"]["transparent-prefix"];
    transparentSuffix?: JSX.IntrinsicElements["loomi-input"]["transparent-suffix"];
    errorMessage?: JSX.IntrinsicElements["loomi-input"]["error-message"];
    showErrorInline?: JSX.IntrinsicElements["loomi-input"]["show-error-inline"];
    showPlaceholderAlways?: JSX.IntrinsicElements["loomi-input"]["show-placeholder-always"];
    showFocusRing?: JSX.IntrinsicElements["loomi-input"]["show-focus-ring"];
  }
>;
