// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import { createComponent } from "../create-component.js";

import "@loomidev/components/lightbox";

export const LightboxImage: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-lightbox-image"], "onLoomiOpen" | "onLoomiClose"> & {
    onLoomiOpen?: (e: Event) => void;
    onLoomiClose?: (e: Event) => void;
  }
> = createComponent(
  "loomi-lightbox-image",
  { "loomi-open": "onLoomiOpen", "loomi-close": "onLoomiClose" },
  {},
) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-lightbox-image"], "onLoomiOpen" | "onLoomiClose"> & {
    onLoomiOpen?: (e: Event) => void;
    onLoomiClose?: (e: Event) => void;
  }
>;
