// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import { createComponent } from "../create-component.js";

import "@loomidev/components/listview";

export const ListviewItem: ForwardRefExoticComponent<
  JSX.IntrinsicElements["loomi-listview-item"] & {
    asFlex?: JSX.IntrinsicElements["loomi-listview-item"]["as-flex"];
  }
> = createComponent(
  "loomi-listview-item",
  {},
  { asFlex: "as-flex" },
) as unknown as ForwardRefExoticComponent<
  JSX.IntrinsicElements["loomi-listview-item"] & {
    asFlex?: JSX.IntrinsicElements["loomi-listview-item"]["as-flex"];
  }
>;
