// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import { createComponent } from "../create-component.js";

import "@loomidev/components/listview";

export const Listview: ForwardRefExoticComponent<JSX.IntrinsicElements["loomi-listview"]> =
  createComponent("loomi-listview", {}, {}) as unknown as ForwardRefExoticComponent<
    JSX.IntrinsicElements["loomi-listview"]
  >;
