// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import type { LoomiModalEventMap } from "@loomidev/components";
import { createComponent } from "../create-component.js";

import "@loomidev/components/modal";

export const Modal: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-modal"], "onOpen" | "onClose" | "onOk"> & {
    onOpen?: (e: LoomiModalEventMap["open"]) => void;
    onClose?: (e: LoomiModalEventMap["close"]) => void;
    onOk?: (e: LoomiModalEventMap["ok"]) => void;
    iconSource?: JSX.IntrinsicElements["loomi-modal"]["icon-source"];
    okButtonLabel?: JSX.IntrinsicElements["loomi-modal"]["ok-button-label"];
    cancelButtonLabel?: JSX.IntrinsicElements["loomi-modal"]["cancel-button-label"];
    showActionButtons?: JSX.IntrinsicElements["loomi-modal"]["show-action-buttons"];
    showCloseIcon?: JSX.IntrinsicElements["loomi-modal"]["show-close-icon"];
    backdropCanClose?: JSX.IntrinsicElements["loomi-modal"]["backdrop-can-close"];
    closeAfterAction?: JSX.IntrinsicElements["loomi-modal"]["close-after-action"];
    preventScroll?: JSX.IntrinsicElements["loomi-modal"]["prevent-scroll"];
    stretchActionButtons?: JSX.IntrinsicElements["loomi-modal"]["stretch-action-buttons"];
    alignButtons?: JSX.IntrinsicElements["loomi-modal"]["align-buttons"];
    blurSize?: JSX.IntrinsicElements["loomi-modal"]["blur-size"];
  }
> = createComponent(
  "loomi-modal",
  { open: "onOpen", close: "onClose", ok: "onOk" },
  {
    iconSource: "icon-source",
    okButtonLabel: "ok-button-label",
    cancelButtonLabel: "cancel-button-label",
    showActionButtons: "show-action-buttons",
    showCloseIcon: "show-close-icon",
    backdropCanClose: "backdrop-can-close",
    closeAfterAction: "close-after-action",
    preventScroll: "prevent-scroll",
    stretchActionButtons: "stretch-action-buttons",
    alignButtons: "align-buttons",
    blurSize: "blur-size",
  },
) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-modal"], "onOpen" | "onClose" | "onOk"> & {
    onOpen?: (e: LoomiModalEventMap["open"]) => void;
    onClose?: (e: LoomiModalEventMap["close"]) => void;
    onOk?: (e: LoomiModalEventMap["ok"]) => void;
    iconSource?: JSX.IntrinsicElements["loomi-modal"]["icon-source"];
    okButtonLabel?: JSX.IntrinsicElements["loomi-modal"]["ok-button-label"];
    cancelButtonLabel?: JSX.IntrinsicElements["loomi-modal"]["cancel-button-label"];
    showActionButtons?: JSX.IntrinsicElements["loomi-modal"]["show-action-buttons"];
    showCloseIcon?: JSX.IntrinsicElements["loomi-modal"]["show-close-icon"];
    backdropCanClose?: JSX.IntrinsicElements["loomi-modal"]["backdrop-can-close"];
    closeAfterAction?: JSX.IntrinsicElements["loomi-modal"]["close-after-action"];
    preventScroll?: JSX.IntrinsicElements["loomi-modal"]["prevent-scroll"];
    stretchActionButtons?: JSX.IntrinsicElements["loomi-modal"]["stretch-action-buttons"];
    alignButtons?: JSX.IntrinsicElements["loomi-modal"]["align-buttons"];
    blurSize?: JSX.IntrinsicElements["loomi-modal"]["blur-size"];
  }
>;
