// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import { createComponent } from "../create-component.js";

import "@loomidev/components/notification";

export const Notification: ForwardRefExoticComponent<
  JSX.IntrinsicElements["loomi-notification"] & {
    fullWidth?: JSX.IntrinsicElements["loomi-notification"]["full-width"];
  }
> = createComponent(
  "loomi-notification",
  {},
  { fullWidth: "full-width" },
) as unknown as ForwardRefExoticComponent<
  JSX.IntrinsicElements["loomi-notification"] & {
    fullWidth?: JSX.IntrinsicElements["loomi-notification"]["full-width"];
  }
>;
