// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import { createComponent } from "../create-component.js";

import "@loomidev/components/number";

export const Number: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-number"], "onInput" | "onChange"> & {
    onInput?: (e: Event) => void;
    onChange?: (e: Event) => void;
    labelPosition?: JSX.IntrinsicElements["loomi-number"]["label-position"];
    transparentIcons?: JSX.IntrinsicElements["loomi-number"]["transparent-icons"];
    withDots?: JSX.IntrinsicElements["loomi-number"]["with-dots"];
  }
> = createComponent(
  "loomi-number",
  { input: "onInput", change: "onChange" },
  { labelPosition: "label-position", transparentIcons: "transparent-icons", withDots: "with-dots" },
) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-number"], "onInput" | "onChange"> & {
    onInput?: (e: Event) => void;
    onChange?: (e: Event) => void;
    labelPosition?: JSX.IntrinsicElements["loomi-number"]["label-position"];
    transparentIcons?: JSX.IntrinsicElements["loomi-number"]["transparent-icons"];
    withDots?: JSX.IntrinsicElements["loomi-number"]["with-dots"];
  }
>;
