// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import type { LoomiPaginationEventMap } from "@loomidev/components";
import { createComponent } from "../create-component.js";

import "@loomidev/components/pagination";

export const Pagination: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-pagination"], "onLoomiPageChange"> & {
    onLoomiPageChange?: (e: LoomiPaginationEventMap["loomi-page-change"]) => void;
    pageSize?: JSX.IntrinsicElements["loomi-pagination"]["page-size"];
    paginationStyle?: JSX.IntrinsicElements["loomi-pagination"]["pagination-style"];
    showTotal?: JSX.IntrinsicElements["loomi-pagination"]["show-total"];
    showPageNumber?: JSX.IntrinsicElements["loomi-pagination"]["show-page-number"];
    showTotalPages?: JSX.IntrinsicElements["loomi-pagination"]["show-total-pages"];
    totalLabel?: JSX.IntrinsicElements["loomi-pagination"]["total-label"];
  }
> = createComponent(
  "loomi-pagination",
  { "loomi-page-change": "onLoomiPageChange" },
  {
    pageSize: "page-size",
    paginationStyle: "pagination-style",
    showTotal: "show-total",
    showPageNumber: "show-page-number",
    showTotalPages: "show-total-pages",
    totalLabel: "total-label",
  },
) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-pagination"], "onLoomiPageChange"> & {
    onLoomiPageChange?: (e: LoomiPaginationEventMap["loomi-page-change"]) => void;
    pageSize?: JSX.IntrinsicElements["loomi-pagination"]["page-size"];
    paginationStyle?: JSX.IntrinsicElements["loomi-pagination"]["pagination-style"];
    showTotal?: JSX.IntrinsicElements["loomi-pagination"]["show-total"];
    showPageNumber?: JSX.IntrinsicElements["loomi-pagination"]["show-page-number"];
    showTotalPages?: JSX.IntrinsicElements["loomi-pagination"]["show-total-pages"];
    totalLabel?: JSX.IntrinsicElements["loomi-pagination"]["total-label"];
  }
>;
