// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import { createComponent } from "../create-component.js";

import "@loomidev/components/password";

export const Password: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-password"], "onLoomiPrefixChange" | "onInput" | "onChange"> & {
    onLoomiPrefixChange?: (e: CustomEvent) => void;
    onInput?: (e: CustomEvent) => void;
    onChange?: (e: CustomEvent) => void;
    labelPosition?: JSX.IntrinsicElements["loomi-password"]["label-position"];
    prefixOptions?: JSX.IntrinsicElements["loomi-password"]["prefix-options"];
    prefixValue?: JSX.IntrinsicElements["loomi-password"]["prefix-value"];
    prefixIcon?: JSX.IntrinsicElements["loomi-password"]["prefix-icon"];
    transparentPrefix?: JSX.IntrinsicElements["loomi-password"]["transparent-prefix"];
    strengthColor?: JSX.IntrinsicElements["loomi-password"]["strength-color"];
    errorMessage?: JSX.IntrinsicElements["loomi-password"]["error-message"];
    showErrorInline?: JSX.IntrinsicElements["loomi-password"]["show-error-inline"];
    showPlaceholderAlways?: JSX.IntrinsicElements["loomi-password"]["show-placeholder-always"];
  }
> = createComponent(
  "loomi-password",
  { "loomi-prefix-change": "onLoomiPrefixChange", input: "onInput", change: "onChange" },
  {
    labelPosition: "label-position",
    prefixOptions: "prefix-options",
    prefixValue: "prefix-value",
    prefixIcon: "prefix-icon",
    transparentPrefix: "transparent-prefix",
    strengthColor: "strength-color",
    errorMessage: "error-message",
    showErrorInline: "show-error-inline",
    showPlaceholderAlways: "show-placeholder-always",
  },
) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-password"], "onLoomiPrefixChange" | "onInput" | "onChange"> & {
    onLoomiPrefixChange?: (e: CustomEvent) => void;
    onInput?: (e: CustomEvent) => void;
    onChange?: (e: CustomEvent) => void;
    labelPosition?: JSX.IntrinsicElements["loomi-password"]["label-position"];
    prefixOptions?: JSX.IntrinsicElements["loomi-password"]["prefix-options"];
    prefixValue?: JSX.IntrinsicElements["loomi-password"]["prefix-value"];
    prefixIcon?: JSX.IntrinsicElements["loomi-password"]["prefix-icon"];
    transparentPrefix?: JSX.IntrinsicElements["loomi-password"]["transparent-prefix"];
    strengthColor?: JSX.IntrinsicElements["loomi-password"]["strength-color"];
    errorMessage?: JSX.IntrinsicElements["loomi-password"]["error-message"];
    showErrorInline?: JSX.IntrinsicElements["loomi-password"]["show-error-inline"];
    showPlaceholderAlways?: JSX.IntrinsicElements["loomi-password"]["show-placeholder-always"];
  }
>;
