// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import { createComponent } from "../create-component.js";

import "@loomidev/components/photo-gallery";

export const PhotoGallery: ForwardRefExoticComponent<
  Omit<
    JSX.IntrinsicElements["loomi-photo-gallery"],
    | "onLoomiFavourite"
    | "onLoomiAlbumChange"
    | "onLoomiSlideshowStart"
    | "onLoomiSlideshowEnd"
    | "onLoomiPhotoOpen"
    | "onLoomiPhotoChange"
    | "onLoomiPhotoClose"
    | "onLoomiRotate"
    | "onLoomiShare"
  > & {
    onLoomiFavourite?: (e: CustomEvent) => void;
    onLoomiAlbumChange?: (e: CustomEvent) => void;
    onLoomiSlideshowStart?: (e: Event) => void;
    onLoomiSlideshowEnd?: (e: Event) => void;
    onLoomiPhotoOpen?: (e: CustomEvent) => void;
    onLoomiPhotoChange?: (e: CustomEvent) => void;
    onLoomiPhotoClose?: (e: CustomEvent) => void;
    onLoomiRotate?: (e: CustomEvent) => void;
    onLoomiShare?: (e: CustomEvent) => void;
    albumView?: JSX.IntrinsicElements["loomi-photo-gallery"]["album-view"];
    squareThumbnails?: JSX.IntrinsicElements["loomi-photo-gallery"]["square-thumbnails"];
    thumbSize?: JSX.IntrinsicElements["loomi-photo-gallery"]["thumb-size"];
    slideshowInterval?: JSX.IntrinsicElements["loomi-photo-gallery"]["slideshow-interval"];
    albumPanelOpen?: JSX.IntrinsicElements["loomi-photo-gallery"]["album-panel-open"];
    showAlbumToggle?: JSX.IntrinsicElements["loomi-photo-gallery"]["show-album-toggle"];
    showZoomIn?: JSX.IntrinsicElements["loomi-photo-gallery"]["show-zoom-in"];
    showZoomOut?: JSX.IntrinsicElements["loomi-photo-gallery"]["show-zoom-out"];
    showSquareToggle?: JSX.IntrinsicElements["loomi-photo-gallery"]["show-square-toggle"];
    showSlideshow?: JSX.IntrinsicElements["loomi-photo-gallery"]["show-slideshow"];
    lightboxShowZoomIn?: JSX.IntrinsicElements["loomi-photo-gallery"]["lightbox-show-zoom-in"];
    lightboxShowZoomOut?: JSX.IntrinsicElements["loomi-photo-gallery"]["lightbox-show-zoom-out"];
    lightboxShowFavourite?: JSX.IntrinsicElements["loomi-photo-gallery"]["lightbox-show-favourite"];
    lightboxShowRotate?: JSX.IntrinsicElements["loomi-photo-gallery"]["lightbox-show-rotate"];
    lightboxShowShare?: JSX.IntrinsicElements["loomi-photo-gallery"]["lightbox-show-share"];
    lightboxShowClose?: JSX.IntrinsicElements["loomi-photo-gallery"]["lightbox-show-close"];
  }
> = createComponent(
  "loomi-photo-gallery",
  {
    "loomi-favourite": "onLoomiFavourite",
    "loomi-album-change": "onLoomiAlbumChange",
    "loomi-slideshow-start": "onLoomiSlideshowStart",
    "loomi-slideshow-end": "onLoomiSlideshowEnd",
    "loomi-photo-open": "onLoomiPhotoOpen",
    "loomi-photo-change": "onLoomiPhotoChange",
    "loomi-photo-close": "onLoomiPhotoClose",
    "loomi-rotate": "onLoomiRotate",
    "loomi-share": "onLoomiShare",
  },
  {
    albumView: "album-view",
    squareThumbnails: "square-thumbnails",
    thumbSize: "thumb-size",
    slideshowInterval: "slideshow-interval",
    albumPanelOpen: "album-panel-open",
    showAlbumToggle: "show-album-toggle",
    showZoomIn: "show-zoom-in",
    showZoomOut: "show-zoom-out",
    showSquareToggle: "show-square-toggle",
    showSlideshow: "show-slideshow",
    lightboxShowZoomIn: "lightbox-show-zoom-in",
    lightboxShowZoomOut: "lightbox-show-zoom-out",
    lightboxShowFavourite: "lightbox-show-favourite",
    lightboxShowRotate: "lightbox-show-rotate",
    lightboxShowShare: "lightbox-show-share",
    lightboxShowClose: "lightbox-show-close",
  },
) as unknown as ForwardRefExoticComponent<
  Omit<
    JSX.IntrinsicElements["loomi-photo-gallery"],
    | "onLoomiFavourite"
    | "onLoomiAlbumChange"
    | "onLoomiSlideshowStart"
    | "onLoomiSlideshowEnd"
    | "onLoomiPhotoOpen"
    | "onLoomiPhotoChange"
    | "onLoomiPhotoClose"
    | "onLoomiRotate"
    | "onLoomiShare"
  > & {
    onLoomiFavourite?: (e: CustomEvent) => void;
    onLoomiAlbumChange?: (e: CustomEvent) => void;
    onLoomiSlideshowStart?: (e: Event) => void;
    onLoomiSlideshowEnd?: (e: Event) => void;
    onLoomiPhotoOpen?: (e: CustomEvent) => void;
    onLoomiPhotoChange?: (e: CustomEvent) => void;
    onLoomiPhotoClose?: (e: CustomEvent) => void;
    onLoomiRotate?: (e: CustomEvent) => void;
    onLoomiShare?: (e: CustomEvent) => void;
    albumView?: JSX.IntrinsicElements["loomi-photo-gallery"]["album-view"];
    squareThumbnails?: JSX.IntrinsicElements["loomi-photo-gallery"]["square-thumbnails"];
    thumbSize?: JSX.IntrinsicElements["loomi-photo-gallery"]["thumb-size"];
    slideshowInterval?: JSX.IntrinsicElements["loomi-photo-gallery"]["slideshow-interval"];
    albumPanelOpen?: JSX.IntrinsicElements["loomi-photo-gallery"]["album-panel-open"];
    showAlbumToggle?: JSX.IntrinsicElements["loomi-photo-gallery"]["show-album-toggle"];
    showZoomIn?: JSX.IntrinsicElements["loomi-photo-gallery"]["show-zoom-in"];
    showZoomOut?: JSX.IntrinsicElements["loomi-photo-gallery"]["show-zoom-out"];
    showSquareToggle?: JSX.IntrinsicElements["loomi-photo-gallery"]["show-square-toggle"];
    showSlideshow?: JSX.IntrinsicElements["loomi-photo-gallery"]["show-slideshow"];
    lightboxShowZoomIn?: JSX.IntrinsicElements["loomi-photo-gallery"]["lightbox-show-zoom-in"];
    lightboxShowZoomOut?: JSX.IntrinsicElements["loomi-photo-gallery"]["lightbox-show-zoom-out"];
    lightboxShowFavourite?: JSX.IntrinsicElements["loomi-photo-gallery"]["lightbox-show-favourite"];
    lightboxShowRotate?: JSX.IntrinsicElements["loomi-photo-gallery"]["lightbox-show-rotate"];
    lightboxShowShare?: JSX.IntrinsicElements["loomi-photo-gallery"]["lightbox-show-share"];
    lightboxShowClose?: JSX.IntrinsicElements["loomi-photo-gallery"]["lightbox-show-close"];
  }
>;
