// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import { createComponent } from "../create-component.js";

import "@loomidev/components/photo-gallery";

export const PhotoGalleryItem: ForwardRefExoticComponent<
  JSX.IntrinsicElements["loomi-photo-gallery-item"]
> = createComponent("loomi-photo-gallery-item", {}, {}) as unknown as ForwardRefExoticComponent<
  JSX.IntrinsicElements["loomi-photo-gallery-item"]
>;
