// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import { createComponent } from "../create-component.js";

import "@loomidev/components/popover";

export const Popover: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-popover"], "onLoomiToggle"> & {
    onLoomiToggle?: (e: CustomEvent) => void;
    triggerOn?: JSX.IntrinsicElements["loomi-popover"]["trigger-on"];
  }
> = createComponent(
  "loomi-popover",
  { "loomi-toggle": "onLoomiToggle" },
  { triggerOn: "trigger-on" },
) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-popover"], "onLoomiToggle"> & {
    onLoomiToggle?: (e: CustomEvent) => void;
    triggerOn?: JSX.IntrinsicElements["loomi-popover"]["trigger-on"];
  }
>;
