// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import { createComponent } from "../create-component.js";

import "@loomidev/components/processing";

export const Processing: ForwardRefExoticComponent<JSX.IntrinsicElements["loomi-processing"]> =
  createComponent("loomi-processing", {}, {}) as unknown as ForwardRefExoticComponent<
    JSX.IntrinsicElements["loomi-processing"]
  >;
