// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import { createComponent } from "../create-component.js";

import "@loomidev/components/profile-menu";

export const ProfileMenu: ForwardRefExoticComponent<
  JSX.IntrinsicElements["loomi-profile-menu"] & {
    avatarLabel?: JSX.IntrinsicElements["loomi-profile-menu"]["avatar-label"];
    avatarAlt?: JSX.IntrinsicElements["loomi-profile-menu"]["avatar-alt"];
    avatarSize?: JSX.IntrinsicElements["loomi-profile-menu"]["avatar-size"];
    avatarBgColor?: JSX.IntrinsicElements["loomi-profile-menu"]["avatar-bg-color"];
    avatarPosition?: JSX.IntrinsicElements["loomi-profile-menu"]["avatar-position"];
    pulseDot?: JSX.IntrinsicElements["loomi-profile-menu"]["pulse-dot"];
    dotColor?: JSX.IntrinsicElements["loomi-profile-menu"]["dot-color"];
    dotPosition?: JSX.IntrinsicElements["loomi-profile-menu"]["dot-position"];
    hasHover?: JSX.IntrinsicElements["loomi-profile-menu"]["has-hover"];
    triggerLabel?: JSX.IntrinsicElements["loomi-profile-menu"]["trigger-label"];
    hideAfterClick?: JSX.IntrinsicElements["loomi-profile-menu"]["hide-after-click"];
  }
> = createComponent(
  "loomi-profile-menu",
  {},
  {
    avatarLabel: "avatar-label",
    avatarAlt: "avatar-alt",
    avatarSize: "avatar-size",
    avatarBgColor: "avatar-bg-color",
    avatarPosition: "avatar-position",
    pulseDot: "pulse-dot",
    dotColor: "dot-color",
    dotPosition: "dot-position",
    hasHover: "has-hover",
    triggerLabel: "trigger-label",
    hideAfterClick: "hide-after-click",
  },
) as unknown as ForwardRefExoticComponent<
  JSX.IntrinsicElements["loomi-profile-menu"] & {
    avatarLabel?: JSX.IntrinsicElements["loomi-profile-menu"]["avatar-label"];
    avatarAlt?: JSX.IntrinsicElements["loomi-profile-menu"]["avatar-alt"];
    avatarSize?: JSX.IntrinsicElements["loomi-profile-menu"]["avatar-size"];
    avatarBgColor?: JSX.IntrinsicElements["loomi-profile-menu"]["avatar-bg-color"];
    avatarPosition?: JSX.IntrinsicElements["loomi-profile-menu"]["avatar-position"];
    pulseDot?: JSX.IntrinsicElements["loomi-profile-menu"]["pulse-dot"];
    dotColor?: JSX.IntrinsicElements["loomi-profile-menu"]["dot-color"];
    dotPosition?: JSX.IntrinsicElements["loomi-profile-menu"]["dot-position"];
    hasHover?: JSX.IntrinsicElements["loomi-profile-menu"]["has-hover"];
    triggerLabel?: JSX.IntrinsicElements["loomi-profile-menu"]["trigger-label"];
    hideAfterClick?: JSX.IntrinsicElements["loomi-profile-menu"]["hide-after-click"];
  }
>;
