// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import { createComponent } from "../create-component.js";

import "@loomidev/components/progress";

export const ProgressCircle: ForwardRefExoticComponent<
  JSX.IntrinsicElements["loomi-progress-circle"] & {
    showLabel?: JSX.IntrinsicElements["loomi-progress-circle"]["show-label"];
    showPercent?: JSX.IntrinsicElements["loomi-progress-circle"]["show-percent"];
    circleWidth?: JSX.IntrinsicElements["loomi-progress-circle"]["circle-width"];
  }
> = createComponent(
  "loomi-progress-circle",
  {},
  { showLabel: "show-label", showPercent: "show-percent", circleWidth: "circle-width" },
) as unknown as ForwardRefExoticComponent<
  JSX.IntrinsicElements["loomi-progress-circle"] & {
    showLabel?: JSX.IntrinsicElements["loomi-progress-circle"]["show-label"];
    showPercent?: JSX.IntrinsicElements["loomi-progress-circle"]["show-percent"];
    circleWidth?: JSX.IntrinsicElements["loomi-progress-circle"]["circle-width"];
  }
>;
