// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import { createComponent } from "../create-component.js";

import "@loomidev/components/progress";

export const ProgressBar: ForwardRefExoticComponent<
  JSX.IntrinsicElements["loomi-progress-bar"] & {
    showPercentageLabel?: JSX.IntrinsicElements["loomi-progress-bar"]["show-percentage-label"];
    showPercentageTooltip?: JSX.IntrinsicElements["loomi-progress-bar"]["show-percentage-tooltip"];
    showPercentageLabelInline?: JSX.IntrinsicElements["loomi-progress-bar"]["show-percentage-label-inline"];
    percentageLabelPosition?: JSX.IntrinsicElements["loomi-progress-bar"]["percentage-label-position"];
    percentagePrefix?: JSX.IntrinsicElements["loomi-progress-bar"]["percentage-prefix"];
    percentageSuffix?: JSX.IntrinsicElements["loomi-progress-bar"]["percentage-suffix"];
  }
> = createComponent(
  "loomi-progress-bar",
  {},
  {
    showPercentageLabel: "show-percentage-label",
    showPercentageTooltip: "show-percentage-tooltip",
    showPercentageLabelInline: "show-percentage-label-inline",
    percentageLabelPosition: "percentage-label-position",
    percentagePrefix: "percentage-prefix",
    percentageSuffix: "percentage-suffix",
  },
) as unknown as ForwardRefExoticComponent<
  JSX.IntrinsicElements["loomi-progress-bar"] & {
    showPercentageLabel?: JSX.IntrinsicElements["loomi-progress-bar"]["show-percentage-label"];
    showPercentageTooltip?: JSX.IntrinsicElements["loomi-progress-bar"]["show-percentage-tooltip"];
    showPercentageLabelInline?: JSX.IntrinsicElements["loomi-progress-bar"]["show-percentage-label-inline"];
    percentageLabelPosition?: JSX.IntrinsicElements["loomi-progress-bar"]["percentage-label-position"];
    percentagePrefix?: JSX.IntrinsicElements["loomi-progress-bar"]["percentage-prefix"];
    percentageSuffix?: JSX.IntrinsicElements["loomi-progress-bar"]["percentage-suffix"];
  }
>;
