// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import { createComponent } from "../create-component.js";

import "@loomidev/components/progress";

export const ProgressArc: ForwardRefExoticComponent<
  JSX.IntrinsicElements["loomi-progress-arc"] & {
    showPercent?: JSX.IntrinsicElements["loomi-progress-arc"]["show-percent"];
  }
> = createComponent(
  "loomi-progress-arc",
  {},
  { showPercent: "show-percent" },
) as unknown as ForwardRefExoticComponent<
  JSX.IntrinsicElements["loomi-progress-arc"] & {
    showPercent?: JSX.IntrinsicElements["loomi-progress-arc"]["show-percent"];
  }
>;
