// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import { createComponent } from "../create-component.js";

import "@loomidev/components/progress";

export const ProgressSteps: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-progress-steps"], "onLoomiProgressStepsChange"> & {
    onLoomiProgressStepsChange?: (e: CustomEvent) => void;
  }
> = createComponent(
  "loomi-progress-steps",
  { "loomi-progress-steps-change": "onLoomiProgressStepsChange" },
  {},
) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-progress-steps"], "onLoomiProgressStepsChange"> & {
    onLoomiProgressStepsChange?: (e: CustomEvent) => void;
  }
>;
