// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import { createComponent } from "../create-component.js";

import "@loomidev/components/qrcode";

export const Qrcode: ForwardRefExoticComponent<
  JSX.IntrinsicElements["loomi-qrcode"] & {
    errorCorrection?: JSX.IntrinsicElements["loomi-qrcode"]["error-correction"];
    quietZone?: JSX.IntrinsicElements["loomi-qrcode"]["quiet-zone"];
    gradientFrom?: JSX.IntrinsicElements["loomi-qrcode"]["gradient-from"];
    gradientTo?: JSX.IntrinsicElements["loomi-qrcode"]["gradient-to"];
    moduleRadius?: JSX.IntrinsicElements["loomi-qrcode"]["module-radius"];
    cornerBorders?: JSX.IntrinsicElements["loomi-qrcode"]["corner-borders"];
    cornerBorderColor?: JSX.IntrinsicElements["loomi-qrcode"]["corner-border-color"];
    cornerBorderWidth?: JSX.IntrinsicElements["loomi-qrcode"]["corner-border-width"];
    cornerBorderLength?: JSX.IntrinsicElements["loomi-qrcode"]["corner-border-length"];
    gradientScan?: JSX.IntrinsicElements["loomi-qrcode"]["gradient-scan"];
    scanColor?: JSX.IntrinsicElements["loomi-qrcode"]["scan-color"];
    scanDuration?: JSX.IntrinsicElements["loomi-qrcode"]["scan-duration"];
    scanCount?: JSX.IntrinsicElements["loomi-qrcode"]["scan-count"];
    ariaLabel?: JSX.IntrinsicElements["loomi-qrcode"]["aria-label"];
  }
> = createComponent(
  "loomi-qrcode",
  {},
  {
    errorCorrection: "error-correction",
    quietZone: "quiet-zone",
    gradientFrom: "gradient-from",
    gradientTo: "gradient-to",
    moduleRadius: "module-radius",
    cornerBorders: "corner-borders",
    cornerBorderColor: "corner-border-color",
    cornerBorderWidth: "corner-border-width",
    cornerBorderLength: "corner-border-length",
    gradientScan: "gradient-scan",
    scanColor: "scan-color",
    scanDuration: "scan-duration",
    scanCount: "scan-count",
    ariaLabel: "aria-label",
  },
) as unknown as ForwardRefExoticComponent<
  JSX.IntrinsicElements["loomi-qrcode"] & {
    errorCorrection?: JSX.IntrinsicElements["loomi-qrcode"]["error-correction"];
    quietZone?: JSX.IntrinsicElements["loomi-qrcode"]["quiet-zone"];
    gradientFrom?: JSX.IntrinsicElements["loomi-qrcode"]["gradient-from"];
    gradientTo?: JSX.IntrinsicElements["loomi-qrcode"]["gradient-to"];
    moduleRadius?: JSX.IntrinsicElements["loomi-qrcode"]["module-radius"];
    cornerBorders?: JSX.IntrinsicElements["loomi-qrcode"]["corner-borders"];
    cornerBorderColor?: JSX.IntrinsicElements["loomi-qrcode"]["corner-border-color"];
    cornerBorderWidth?: JSX.IntrinsicElements["loomi-qrcode"]["corner-border-width"];
    cornerBorderLength?: JSX.IntrinsicElements["loomi-qrcode"]["corner-border-length"];
    gradientScan?: JSX.IntrinsicElements["loomi-qrcode"]["gradient-scan"];
    scanColor?: JSX.IntrinsicElements["loomi-qrcode"]["scan-color"];
    scanDuration?: JSX.IntrinsicElements["loomi-qrcode"]["scan-duration"];
    scanCount?: JSX.IntrinsicElements["loomi-qrcode"]["scan-count"];
    ariaLabel?: JSX.IntrinsicElements["loomi-qrcode"]["aria-label"];
  }
>;
