// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import type { LoomiRadioEventMap } from "@loomidev/components";
import { createComponent } from "../create-component.js";

import "@loomidev/components/radio";

export const Radio: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-radio"], "onChange"> & {
    onChange?: (e: LoomiRadioEventMap["change"]) => void;
  }
> = createComponent(
  "loomi-radio",
  { change: "onChange" },
  {},
) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-radio"], "onChange"> & {
    onChange?: (e: LoomiRadioEventMap["change"]) => void;
  }
>;
