// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import type { LoomiRatingEventMap } from "@loomidev/components";
import { createComponent } from "../create-component.js";

import "@loomidev/components/rating";

export const Rating: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-rating"], "onChange"> & {
    onChange?: (e: LoomiRatingEventMap["change"]) => void;
  }
> = createComponent(
  "loomi-rating",
  { change: "onChange" },
  {},
) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-rating"], "onChange"> & {
    onChange?: (e: LoomiRatingEventMap["change"]) => void;
  }
>;
