// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import { createComponent } from "../create-component.js";

import "@loomidev/components/resizable";

export const ResizablePanelGroup: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-resizable-panel-group"], "onLoomiLayoutChange"> & {
    onLoomiLayoutChange?: (e: CustomEvent) => void;
    autoSaveId?: JSX.IntrinsicElements["loomi-resizable-panel-group"]["auto-save-id"];
  }
> = createComponent(
  "loomi-resizable-panel-group",
  { "loomi-layout-change": "onLoomiLayoutChange" },
  { autoSaveId: "auto-save-id" },
) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-resizable-panel-group"], "onLoomiLayoutChange"> & {
    onLoomiLayoutChange?: (e: CustomEvent) => void;
    autoSaveId?: JSX.IntrinsicElements["loomi-resizable-panel-group"]["auto-save-id"];
  }
>;
