// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import { createComponent } from "../create-component.js";

import "@loomidev/components/resizable";

export const ResizablePanel: ForwardRefExoticComponent<
  JSX.IntrinsicElements["loomi-resizable-panel"] & {
    panelId?: JSX.IntrinsicElements["loomi-resizable-panel"]["panel-id"];
    defaultSize?: JSX.IntrinsicElements["loomi-resizable-panel"]["default-size"];
    minSize?: JSX.IntrinsicElements["loomi-resizable-panel"]["min-size"];
    maxSize?: JSX.IntrinsicElements["loomi-resizable-panel"]["max-size"];
    collapsedSize?: JSX.IntrinsicElements["loomi-resizable-panel"]["collapsed-size"];
  }
> = createComponent(
  "loomi-resizable-panel",
  {},
  {
    panelId: "panel-id",
    defaultSize: "default-size",
    minSize: "min-size",
    maxSize: "max-size",
    collapsedSize: "collapsed-size",
  },
) as unknown as ForwardRefExoticComponent<
  JSX.IntrinsicElements["loomi-resizable-panel"] & {
    panelId?: JSX.IntrinsicElements["loomi-resizable-panel"]["panel-id"];
    defaultSize?: JSX.IntrinsicElements["loomi-resizable-panel"]["default-size"];
    minSize?: JSX.IntrinsicElements["loomi-resizable-panel"]["min-size"];
    maxSize?: JSX.IntrinsicElements["loomi-resizable-panel"]["max-size"];
    collapsedSize?: JSX.IntrinsicElements["loomi-resizable-panel"]["collapsed-size"];
  }
>;
