// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import { createComponent } from "../create-component.js";

import "@loomidev/components/resizable";

export const ResizableHandle: ForwardRefExoticComponent<
  JSX.IntrinsicElements["loomi-resizable-handle"] & {
    withHandle?: JSX.IntrinsicElements["loomi-resizable-handle"]["with-handle"];
  }
> = createComponent(
  "loomi-resizable-handle",
  {},
  { withHandle: "with-handle" },
) as unknown as ForwardRefExoticComponent<
  JSX.IntrinsicElements["loomi-resizable-handle"] & {
    withHandle?: JSX.IntrinsicElements["loomi-resizable-handle"]["with-handle"];
  }
>;
