// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import { createComponent } from "../create-component.js";

import "@loomidev/components/scroller";

export const Scroller: ForwardRefExoticComponent<
  Omit<
    JSX.IntrinsicElements["loomi-scroller"],
    "onLoomiScrollerItemClick" | "onLoomiScrollComplete"
  > & {
    onLoomiScrollerItemClick?: (e: CustomEvent) => void;
    onLoomiScrollComplete?: (e: CustomEvent) => void;
    pauseOnHover?: JSX.IntrinsicElements["loomi-scroller"]["pause-on-hover"];
    scrollCount?: JSX.IntrinsicElements["loomi-scroller"]["scroll-count"];
    blurredEdges?: JSX.IntrinsicElements["loomi-scroller"]["blurred-edges"];
    edgeSize?: JSX.IntrinsicElements["loomi-scroller"]["edge-size"];
  }
> = createComponent(
  "loomi-scroller",
  {
    "loomi-scroller-item-click": "onLoomiScrollerItemClick",
    "loomi-scroll-complete": "onLoomiScrollComplete",
  },
  {
    pauseOnHover: "pause-on-hover",
    scrollCount: "scroll-count",
    blurredEdges: "blurred-edges",
    edgeSize: "edge-size",
  },
) as unknown as ForwardRefExoticComponent<
  Omit<
    JSX.IntrinsicElements["loomi-scroller"],
    "onLoomiScrollerItemClick" | "onLoomiScrollComplete"
  > & {
    onLoomiScrollerItemClick?: (e: CustomEvent) => void;
    onLoomiScrollComplete?: (e: CustomEvent) => void;
    pauseOnHover?: JSX.IntrinsicElements["loomi-scroller"]["pause-on-hover"];
    scrollCount?: JSX.IntrinsicElements["loomi-scroller"]["scroll-count"];
    blurredEdges?: JSX.IntrinsicElements["loomi-scroller"]["blurred-edges"];
    edgeSize?: JSX.IntrinsicElements["loomi-scroller"]["edge-size"];
  }
>;
