// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import type { LoomiSelectEventMap } from "@loomidev/components";
import { createComponent } from "../create-component.js";

import "@loomidev/components/select";

export const Select: ForwardRefExoticComponent<
  Omit<
    JSX.IntrinsicElements["loomi-select"],
    "onChange" | "onLoomiSelect" | "onLoomiEmptyAction"
  > & {
    onChange?: (e: Event) => void;
    onLoomiSelect?: (e: LoomiSelectEventMap["loomi-select"]) => void;
    onLoomiEmptyAction?: (e: LoomiSelectEventMap["loomi-empty-action"]) => void;
    labelPosition?: JSX.IntrinsicElements["loomi-select"]["label-position"];
    labelKey?: JSX.IntrinsicElements["loomi-select"]["label-key"];
    valueKey?: JSX.IntrinsicElements["loomi-select"]["value-key"];
    imageKey?: JSX.IntrinsicElements["loomi-select"]["image-key"];
    selectedValue?: JSX.IntrinsicElements["loomi-select"]["selected-value"];
    maxSelectable?: JSX.IntrinsicElements["loomi-select"]["max-selectable"];
    emptyPlaceholder?: JSX.IntrinsicElements["loomi-select"]["empty-placeholder"];
    emptyActionLabel?: JSX.IntrinsicElements["loomi-select"]["empty-action-label"];
    emptyActionUrl?: JSX.IntrinsicElements["loomi-select"]["empty-action-url"];
    showFocusRing?: JSX.IntrinsicElements["loomi-select"]["show-focus-ring"];
  }
> = createComponent(
  "loomi-select",
  {
    change: "onChange",
    "loomi-select": "onLoomiSelect",
    "loomi-empty-action": "onLoomiEmptyAction",
  },
  {
    labelPosition: "label-position",
    labelKey: "label-key",
    valueKey: "value-key",
    imageKey: "image-key",
    selectedValue: "selected-value",
    maxSelectable: "max-selectable",
    emptyPlaceholder: "empty-placeholder",
    emptyActionLabel: "empty-action-label",
    emptyActionUrl: "empty-action-url",
    showFocusRing: "show-focus-ring",
  },
) as unknown as ForwardRefExoticComponent<
  Omit<
    JSX.IntrinsicElements["loomi-select"],
    "onChange" | "onLoomiSelect" | "onLoomiEmptyAction"
  > & {
    onChange?: (e: Event) => void;
    onLoomiSelect?: (e: LoomiSelectEventMap["loomi-select"]) => void;
    onLoomiEmptyAction?: (e: LoomiSelectEventMap["loomi-empty-action"]) => void;
    labelPosition?: JSX.IntrinsicElements["loomi-select"]["label-position"];
    labelKey?: JSX.IntrinsicElements["loomi-select"]["label-key"];
    valueKey?: JSX.IntrinsicElements["loomi-select"]["value-key"];
    imageKey?: JSX.IntrinsicElements["loomi-select"]["image-key"];
    selectedValue?: JSX.IntrinsicElements["loomi-select"]["selected-value"];
    maxSelectable?: JSX.IntrinsicElements["loomi-select"]["max-selectable"];
    emptyPlaceholder?: JSX.IntrinsicElements["loomi-select"]["empty-placeholder"];
    emptyActionLabel?: JSX.IntrinsicElements["loomi-select"]["empty-action-label"];
    emptyActionUrl?: JSX.IntrinsicElements["loomi-select"]["empty-action-url"];
    showFocusRing?: JSX.IntrinsicElements["loomi-select"]["show-focus-ring"];
  }
>;
