// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import { createComponent } from "../create-component.js";

import "@loomidev/components/side-nav";

export const SideNav: ForwardRefExoticComponent<
  JSX.IntrinsicElements["loomi-side-nav"] & {
    collapseMode?: JSX.IntrinsicElements["loomi-side-nav"]["collapse-mode"];
    iconSize?: JSX.IntrinsicElements["loomi-side-nav"]["icon-size"];
  }
> = createComponent(
  "loomi-side-nav",
  {},
  { collapseMode: "collapse-mode", iconSize: "icon-size" },
) as unknown as ForwardRefExoticComponent<
  JSX.IntrinsicElements["loomi-side-nav"] & {
    collapseMode?: JSX.IntrinsicElements["loomi-side-nav"]["collapse-mode"];
    iconSize?: JSX.IntrinsicElements["loomi-side-nav"]["icon-size"];
  }
>;
