// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import { createComponent } from "../create-component.js";

import "@loomidev/components/side-nav";

export const SideNavItem: ForwardRefExoticComponent<JSX.IntrinsicElements["loomi-side-nav-item"]> =
  createComponent("loomi-side-nav-item", {}, {}) as unknown as ForwardRefExoticComponent<
    JSX.IntrinsicElements["loomi-side-nav-item"]
  >;
