// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import type { LoomiSliderEventMap } from "@loomidev/components";
import { createComponent } from "../create-component.js";

import "@loomidev/components/slider";

export const Slider: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-slider"], "onInput" | "onChange"> & {
    onInput?: (e: LoomiSliderEventMap["input"]) => void;
    onChange?: (e: LoomiSliderEventMap["change"]) => void;
    selectedEnd?: JSX.IntrinsicElements["loomi-slider"]["selected-end"];
    handleWidth?: JSX.IntrinsicElements["loomi-slider"]["handle-width"];
    trackRadius?: JSX.IntrinsicElements["loomi-slider"]["track-radius"];
    handleVariant?: JSX.IntrinsicElements["loomi-slider"]["handle-variant"];
    valueTarget?: JSX.IntrinsicElements["loomi-slider"]["value-target"];
    showTooltip?: JSX.IntrinsicElements["loomi-slider"]["show-tooltip"];
    showValues?: JSX.IntrinsicElements["loomi-slider"]["show-values"];
  }
> = createComponent(
  "loomi-slider",
  { input: "onInput", change: "onChange" },
  {
    selectedEnd: "selected-end",
    handleWidth: "handle-width",
    trackRadius: "track-radius",
    handleVariant: "handle-variant",
    valueTarget: "value-target",
    showTooltip: "show-tooltip",
    showValues: "show-values",
  },
) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-slider"], "onInput" | "onChange"> & {
    onInput?: (e: LoomiSliderEventMap["input"]) => void;
    onChange?: (e: LoomiSliderEventMap["change"]) => void;
    selectedEnd?: JSX.IntrinsicElements["loomi-slider"]["selected-end"];
    handleWidth?: JSX.IntrinsicElements["loomi-slider"]["handle-width"];
    trackRadius?: JSX.IntrinsicElements["loomi-slider"]["track-radius"];
    handleVariant?: JSX.IntrinsicElements["loomi-slider"]["handle-variant"];
    valueTarget?: JSX.IntrinsicElements["loomi-slider"]["value-target"];
    showTooltip?: JSX.IntrinsicElements["loomi-slider"]["show-tooltip"];
    showValues?: JSX.IntrinsicElements["loomi-slider"]["show-values"];
  }
>;
