// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import type { LoomiSortableEventMap } from "@loomidev/components";
import { createComponent } from "../create-component.js";

import "@loomidev/components/sortable";

export const Sortable: ForwardRefExoticComponent<
  Omit<
    JSX.IntrinsicElements["loomi-sortable"],
    "onLoomiFilter" | "onLoomiItemClick" | "onLoomiReorder" | "onLoomiTransfer"
  > & {
    onLoomiFilter?: (e: LoomiSortableEventMap["loomi-filter"]) => void;
    onLoomiItemClick?: (e: LoomiSortableEventMap["loomi-item-click"]) => void;
    onLoomiReorder?: (e: LoomiSortableEventMap["loomi-reorder"]) => void;
    onLoomiTransfer?: (e: LoomiSortableEventMap["loomi-transfer"]) => void;
    hasHandle?: JSX.IntrinsicElements["loomi-sortable"]["has-handle"];
    handleIcon?: JSX.IntrinsicElements["loomi-sortable"]["handle-icon"];
    multiDrag?: JSX.IntrinsicElements["loomi-sortable"]["multi-drag"];
    selectedClass?: JSX.IntrinsicElements["loomi-sortable"]["selected-class"];
    swapClass?: JSX.IntrinsicElements["loomi-sortable"]["swap-class"];
  }
> = createComponent(
  "loomi-sortable",
  {
    "loomi-filter": "onLoomiFilter",
    "loomi-item-click": "onLoomiItemClick",
    "loomi-reorder": "onLoomiReorder",
    "loomi-transfer": "onLoomiTransfer",
  },
  {
    hasHandle: "has-handle",
    handleIcon: "handle-icon",
    multiDrag: "multi-drag",
    selectedClass: "selected-class",
    swapClass: "swap-class",
  },
) as unknown as ForwardRefExoticComponent<
  Omit<
    JSX.IntrinsicElements["loomi-sortable"],
    "onLoomiFilter" | "onLoomiItemClick" | "onLoomiReorder" | "onLoomiTransfer"
  > & {
    onLoomiFilter?: (e: LoomiSortableEventMap["loomi-filter"]) => void;
    onLoomiItemClick?: (e: LoomiSortableEventMap["loomi-item-click"]) => void;
    onLoomiReorder?: (e: LoomiSortableEventMap["loomi-reorder"]) => void;
    onLoomiTransfer?: (e: LoomiSortableEventMap["loomi-transfer"]) => void;
    hasHandle?: JSX.IntrinsicElements["loomi-sortable"]["has-handle"];
    handleIcon?: JSX.IntrinsicElements["loomi-sortable"]["handle-icon"];
    multiDrag?: JSX.IntrinsicElements["loomi-sortable"]["multi-drag"];
    selectedClass?: JSX.IntrinsicElements["loomi-sortable"]["selected-class"];
    swapClass?: JSX.IntrinsicElements["loomi-sortable"]["swap-class"];
  }
>;
