// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import { createComponent } from "../create-component.js";

import "@loomidev/components/spinner";

export const Spinner: ForwardRefExoticComponent<JSX.IntrinsicElements["loomi-spinner"]> =
  createComponent("loomi-spinner", {}, {}) as unknown as ForwardRefExoticComponent<
    JSX.IntrinsicElements["loomi-spinner"]
  >;
