// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import { createComponent } from "../create-component.js";

import "@loomidev/components/split-button";

export const SplitButton: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-split-button"], "onLoomiSplitToggle"> & {
    onLoomiSplitToggle?: (e: CustomEvent) => void;
    borderWidth?: JSX.IntrinsicElements["loomi-split-button"]["border-width"];
    iconRight?: JSX.IntrinsicElements["loomi-split-button"]["icon-right"];
    canSubmit?: JSX.IntrinsicElements["loomi-split-button"]["can-submit"];
    hasSpinner?: JSX.IntrinsicElements["loomi-split-button"]["has-spinner"];
    showSpinner?: JSX.IntrinsicElements["loomi-split-button"]["show-spinner"];
    hideAfterClick?: JSX.IntrinsicElements["loomi-split-button"]["hide-after-click"];
    menuLabel?: JSX.IntrinsicElements["loomi-split-button"]["menu-label"];
    menuDisabled?: JSX.IntrinsicElements["loomi-split-button"]["menu-disabled"];
  }
> = createComponent(
  "loomi-split-button",
  { "loomi-split-toggle": "onLoomiSplitToggle" },
  {
    borderWidth: "border-width",
    iconRight: "icon-right",
    canSubmit: "can-submit",
    hasSpinner: "has-spinner",
    showSpinner: "show-spinner",
    hideAfterClick: "hide-after-click",
    menuLabel: "menu-label",
    menuDisabled: "menu-disabled",
  },
) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-split-button"], "onLoomiSplitToggle"> & {
    onLoomiSplitToggle?: (e: CustomEvent) => void;
    borderWidth?: JSX.IntrinsicElements["loomi-split-button"]["border-width"];
    iconRight?: JSX.IntrinsicElements["loomi-split-button"]["icon-right"];
    canSubmit?: JSX.IntrinsicElements["loomi-split-button"]["can-submit"];
    hasSpinner?: JSX.IntrinsicElements["loomi-split-button"]["has-spinner"];
    showSpinner?: JSX.IntrinsicElements["loomi-split-button"]["show-spinner"];
    hideAfterClick?: JSX.IntrinsicElements["loomi-split-button"]["hide-after-click"];
    menuLabel?: JSX.IntrinsicElements["loomi-split-button"]["menu-label"];
    menuDisabled?: JSX.IntrinsicElements["loomi-split-button"]["menu-disabled"];
  }
>;
