// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import { createComponent } from "../create-component.js";

import "@loomidev/components/statistic";

export const Statistic: ForwardRefExoticComponent<
  JSX.IntrinsicElements["loomi-statistic"] & {
    labelPosition?: JSX.IntrinsicElements["loomi-statistic"]["label-position"];
    currencyPosition?: JSX.IntrinsicElements["loomi-statistic"]["currency-position"];
    iconPosition?: JSX.IntrinsicElements["loomi-statistic"]["icon-position"];
    hasShadow?: JSX.IntrinsicElements["loomi-statistic"]["has-shadow"];
    hasBorder?: JSX.IntrinsicElements["loomi-statistic"]["has-border"];
    showSpinner?: JSX.IntrinsicElements["loomi-statistic"]["show-spinner"];
    iconColor?: JSX.IntrinsicElements["loomi-statistic"]["icon-color"];
    iconSize?: JSX.IntrinsicElements["loomi-statistic"]["icon-size"];
  }
> = createComponent(
  "loomi-statistic",
  {},
  {
    labelPosition: "label-position",
    currencyPosition: "currency-position",
    iconPosition: "icon-position",
    hasShadow: "has-shadow",
    hasBorder: "has-border",
    showSpinner: "show-spinner",
    iconColor: "icon-color",
    iconSize: "icon-size",
  },
) as unknown as ForwardRefExoticComponent<
  JSX.IntrinsicElements["loomi-statistic"] & {
    labelPosition?: JSX.IntrinsicElements["loomi-statistic"]["label-position"];
    currencyPosition?: JSX.IntrinsicElements["loomi-statistic"]["currency-position"];
    iconPosition?: JSX.IntrinsicElements["loomi-statistic"]["icon-position"];
    hasShadow?: JSX.IntrinsicElements["loomi-statistic"]["has-shadow"];
    hasBorder?: JSX.IntrinsicElements["loomi-statistic"]["has-border"];
    showSpinner?: JSX.IntrinsicElements["loomi-statistic"]["show-spinner"];
    iconColor?: JSX.IntrinsicElements["loomi-statistic"]["icon-color"];
    iconSize?: JSX.IntrinsicElements["loomi-statistic"]["icon-size"];
  }
>;
