// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import { createComponent } from "../create-component.js";

import "@loomidev/components/tab";

export const Tab: ForwardRefExoticComponent<
  JSX.IntrinsicElements["loomi-tab"] & {
    iconSource?: JSX.IntrinsicElements["loomi-tab"]["icon-source"];
    iconVariant?: JSX.IntrinsicElements["loomi-tab"]["icon-variant"];
  }
> = createComponent(
  "loomi-tab",
  {},
  { iconSource: "icon-source", iconVariant: "icon-variant" },
) as unknown as ForwardRefExoticComponent<
  JSX.IntrinsicElements["loomi-tab"] & {
    iconSource?: JSX.IntrinsicElements["loomi-tab"]["icon-source"];
    iconVariant?: JSX.IntrinsicElements["loomi-tab"]["icon-variant"];
  }
>;
