// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import type { LoomiTableEventMap } from "@loomidev/components";
import { createComponent } from "../create-component.js";

import "@loomidev/components/table";

export const Table: ForwardRefExoticComponent<
  Omit<
    JSX.IntrinsicElements["loomi-table"],
    | "onLoomiSelectionChange"
    | "onLoomiActionCall"
    | "onLoomiAction"
    | "onLoomiRowClick"
    | "onLoomiEmptyAction"
    | "onLoomiPageChange"
  > & {
    onLoomiSelectionChange?: (e: LoomiTableEventMap["loomi-selection-change"]) => void;
    onLoomiActionCall?: (e: LoomiTableEventMap["loomi-action-call"]) => void;
    onLoomiAction?: (e: LoomiTableEventMap["loomi-action"]) => void;
    onLoomiRowClick?: (e: LoomiTableEventMap["loomi-row-click"]) => void;
    onLoomiEmptyAction?: (e: LoomiTableEventMap["loomi-empty-action"]) => void;
    onLoomiPageChange?: (e: LoomiTableEventMap["loomi-page-change"]) => void;
    excludeColumns?: JSX.IntrinsicElements["loomi-table"]["exclude-columns"];
    includeColumns?: JSX.IntrinsicElements["loomi-table"]["include-columns"];
    columnAliases?: JSX.IntrinsicElements["loomi-table"]["column-aliases"];
    rowTemplate?: JSX.IntrinsicElements["loomi-table"]["row-template"];
    hasHover?: JSX.IntrinsicElements["loomi-table"]["has-hover"];
    hasShadow?: JSX.IntrinsicElements["loomi-table"]["has-shadow"];
    hasBorder?: JSX.IntrinsicElements["loomi-table"]["has-border"];
    searchContainer?: JSX.IntrinsicElements["loomi-table"]["search-container"];
    searchPlaceholder?: JSX.IntrinsicElements["loomi-table"]["search-placeholder"];
    sortableColumns?: JSX.IntrinsicElements["loomi-table"]["sortable-columns"];
    pageSize?: JSX.IntrinsicElements["loomi-table"]["page-size"];
    paginationStyle?: JSX.IntrinsicElements["loomi-table"]["pagination-style"];
    showRowNumbers?: JSX.IntrinsicElements["loomi-table"]["show-row-numbers"];
    showTotal?: JSX.IntrinsicElements["loomi-table"]["show-total"];
    showPageNumber?: JSX.IntrinsicElements["loomi-table"]["show-page-number"];
    showTotalPages?: JSX.IntrinsicElements["loomi-table"]["show-total-pages"];
    defaultPage?: JSX.IntrinsicElements["loomi-table"]["default-page"];
    totalLabel?: JSX.IntrinsicElements["loomi-table"]["total-label"];
    idKey?: JSX.IntrinsicElements["loomi-table"]["id-key"];
    selectedValue?: JSX.IntrinsicElements["loomi-table"]["selected-value"];
    actionIcons?: JSX.IntrinsicElements["loomi-table"]["action-icons"];
    actionsTitle?: JSX.IntrinsicElements["loomi-table"]["actions-title"];
    noDataMessage?: JSX.IntrinsicElements["loomi-table"]["no-data-message"];
    messageAsEmptyState?: JSX.IntrinsicElements["loomi-table"]["message-as-empty-state"];
    buttonLabel?: JSX.IntrinsicElements["loomi-table"]["button-label"];
    showImage?: JSX.IntrinsicElements["loomi-table"]["show-image"];
    groupBy?: JSX.IntrinsicElements["loomi-table"]["group-by"];
  }
> = createComponent(
  "loomi-table",
  {
    "loomi-selection-change": "onLoomiSelectionChange",
    "loomi-action-call": "onLoomiActionCall",
    "loomi-action": "onLoomiAction",
    "loomi-row-click": "onLoomiRowClick",
    "loomi-empty-action": "onLoomiEmptyAction",
    "loomi-page-change": "onLoomiPageChange",
  },
  {
    excludeColumns: "exclude-columns",
    includeColumns: "include-columns",
    columnAliases: "column-aliases",
    rowTemplate: "row-template",
    hasHover: "has-hover",
    hasShadow: "has-shadow",
    hasBorder: "has-border",
    searchContainer: "search-container",
    searchPlaceholder: "search-placeholder",
    sortableColumns: "sortable-columns",
    pageSize: "page-size",
    paginationStyle: "pagination-style",
    showRowNumbers: "show-row-numbers",
    showTotal: "show-total",
    showPageNumber: "show-page-number",
    showTotalPages: "show-total-pages",
    defaultPage: "default-page",
    totalLabel: "total-label",
    idKey: "id-key",
    selectedValue: "selected-value",
    actionIcons: "action-icons",
    actionsTitle: "actions-title",
    noDataMessage: "no-data-message",
    messageAsEmptyState: "message-as-empty-state",
    buttonLabel: "button-label",
    showImage: "show-image",
    groupBy: "group-by",
  },
) as unknown as ForwardRefExoticComponent<
  Omit<
    JSX.IntrinsicElements["loomi-table"],
    | "onLoomiSelectionChange"
    | "onLoomiActionCall"
    | "onLoomiAction"
    | "onLoomiRowClick"
    | "onLoomiEmptyAction"
    | "onLoomiPageChange"
  > & {
    onLoomiSelectionChange?: (e: LoomiTableEventMap["loomi-selection-change"]) => void;
    onLoomiActionCall?: (e: LoomiTableEventMap["loomi-action-call"]) => void;
    onLoomiAction?: (e: LoomiTableEventMap["loomi-action"]) => void;
    onLoomiRowClick?: (e: LoomiTableEventMap["loomi-row-click"]) => void;
    onLoomiEmptyAction?: (e: LoomiTableEventMap["loomi-empty-action"]) => void;
    onLoomiPageChange?: (e: LoomiTableEventMap["loomi-page-change"]) => void;
    excludeColumns?: JSX.IntrinsicElements["loomi-table"]["exclude-columns"];
    includeColumns?: JSX.IntrinsicElements["loomi-table"]["include-columns"];
    columnAliases?: JSX.IntrinsicElements["loomi-table"]["column-aliases"];
    rowTemplate?: JSX.IntrinsicElements["loomi-table"]["row-template"];
    hasHover?: JSX.IntrinsicElements["loomi-table"]["has-hover"];
    hasShadow?: JSX.IntrinsicElements["loomi-table"]["has-shadow"];
    hasBorder?: JSX.IntrinsicElements["loomi-table"]["has-border"];
    searchContainer?: JSX.IntrinsicElements["loomi-table"]["search-container"];
    searchPlaceholder?: JSX.IntrinsicElements["loomi-table"]["search-placeholder"];
    sortableColumns?: JSX.IntrinsicElements["loomi-table"]["sortable-columns"];
    pageSize?: JSX.IntrinsicElements["loomi-table"]["page-size"];
    paginationStyle?: JSX.IntrinsicElements["loomi-table"]["pagination-style"];
    showRowNumbers?: JSX.IntrinsicElements["loomi-table"]["show-row-numbers"];
    showTotal?: JSX.IntrinsicElements["loomi-table"]["show-total"];
    showPageNumber?: JSX.IntrinsicElements["loomi-table"]["show-page-number"];
    showTotalPages?: JSX.IntrinsicElements["loomi-table"]["show-total-pages"];
    defaultPage?: JSX.IntrinsicElements["loomi-table"]["default-page"];
    totalLabel?: JSX.IntrinsicElements["loomi-table"]["total-label"];
    idKey?: JSX.IntrinsicElements["loomi-table"]["id-key"];
    selectedValue?: JSX.IntrinsicElements["loomi-table"]["selected-value"];
    actionIcons?: JSX.IntrinsicElements["loomi-table"]["action-icons"];
    actionsTitle?: JSX.IntrinsicElements["loomi-table"]["actions-title"];
    noDataMessage?: JSX.IntrinsicElements["loomi-table"]["no-data-message"];
    messageAsEmptyState?: JSX.IntrinsicElements["loomi-table"]["message-as-empty-state"];
    buttonLabel?: JSX.IntrinsicElements["loomi-table"]["button-label"];
    showImage?: JSX.IntrinsicElements["loomi-table"]["show-image"];
    groupBy?: JSX.IntrinsicElements["loomi-table"]["group-by"];
  }
>;
