// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import { createComponent } from "../create-component.js";

import "@loomidev/components/tab";

export const Tabs: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-tabs"], "onLoomiTabChange"> & {
    onLoomiTabChange?: (e: CustomEvent) => void;
    tabStyle?: JSX.IntrinsicElements["loomi-tabs"]["tab-style"];
  }
> = createComponent(
  "loomi-tabs",
  { "loomi-tab-change": "onLoomiTabChange" },
  { tabStyle: "tab-style" },
) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-tabs"], "onLoomiTabChange"> & {
    onLoomiTabChange?: (e: CustomEvent) => void;
    tabStyle?: JSX.IntrinsicElements["loomi-tabs"]["tab-style"];
  }
>;
