// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import { createComponent } from "../create-component.js";

import "@loomidev/components/tag-input";

export const TagInput: ForwardRefExoticComponent<
  Omit<
    JSX.IntrinsicElements["loomi-tag-input"],
    "onLoomiAutocompleteSelect" | "onInput" | "onChange"
  > & {
    onLoomiAutocompleteSelect?: (e: CustomEvent) => void;
    onInput?: (e: CustomEvent) => void;
    onChange?: (e: CustomEvent) => void;
    labelPosition?: JSX.IntrinsicElements["loomi-tag-input"]["label-position"];
    suffixIcon?: JSX.IntrinsicElements["loomi-tag-input"]["suffix-icon"];
    errorMessage?: JSX.IntrinsicElements["loomi-tag-input"]["error-message"];
    showErrorInline?: JSX.IntrinsicElements["loomi-tag-input"]["show-error-inline"];
    showFocusRing?: JSX.IntrinsicElements["loomi-tag-input"]["show-focus-ring"];
    autocompleteData?: JSX.IntrinsicElements["loomi-tag-input"]["autocomplete-data"];
    autocompleteLabelKey?: JSX.IntrinsicElements["loomi-tag-input"]["autocomplete-label-key"];
    autocompleteValueKey?: JSX.IntrinsicElements["loomi-tag-input"]["autocomplete-value-key"];
    autocompleteDescriptionKey?: JSX.IntrinsicElements["loomi-tag-input"]["autocomplete-description-key"];
    autocompleteImageKey?: JSX.IntrinsicElements["loomi-tag-input"]["autocomplete-image-key"];
  }
> = createComponent(
  "loomi-tag-input",
  {
    "loomi-autocomplete-select": "onLoomiAutocompleteSelect",
    input: "onInput",
    change: "onChange",
  },
  {
    labelPosition: "label-position",
    suffixIcon: "suffix-icon",
    errorMessage: "error-message",
    showErrorInline: "show-error-inline",
    showFocusRing: "show-focus-ring",
    autocompleteData: "autocomplete-data",
    autocompleteLabelKey: "autocomplete-label-key",
    autocompleteValueKey: "autocomplete-value-key",
    autocompleteDescriptionKey: "autocomplete-description-key",
    autocompleteImageKey: "autocomplete-image-key",
  },
) as unknown as ForwardRefExoticComponent<
  Omit<
    JSX.IntrinsicElements["loomi-tag-input"],
    "onLoomiAutocompleteSelect" | "onInput" | "onChange"
  > & {
    onLoomiAutocompleteSelect?: (e: CustomEvent) => void;
    onInput?: (e: CustomEvent) => void;
    onChange?: (e: CustomEvent) => void;
    labelPosition?: JSX.IntrinsicElements["loomi-tag-input"]["label-position"];
    suffixIcon?: JSX.IntrinsicElements["loomi-tag-input"]["suffix-icon"];
    errorMessage?: JSX.IntrinsicElements["loomi-tag-input"]["error-message"];
    showErrorInline?: JSX.IntrinsicElements["loomi-tag-input"]["show-error-inline"];
    showFocusRing?: JSX.IntrinsicElements["loomi-tag-input"]["show-focus-ring"];
    autocompleteData?: JSX.IntrinsicElements["loomi-tag-input"]["autocomplete-data"];
    autocompleteLabelKey?: JSX.IntrinsicElements["loomi-tag-input"]["autocomplete-label-key"];
    autocompleteValueKey?: JSX.IntrinsicElements["loomi-tag-input"]["autocomplete-value-key"];
    autocompleteDescriptionKey?: JSX.IntrinsicElements["loomi-tag-input"]["autocomplete-description-key"];
    autocompleteImageKey?: JSX.IntrinsicElements["loomi-tag-input"]["autocomplete-image-key"];
  }
>;
