// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import type { LoomiTagEventMap } from "@loomidev/components";
import { createComponent } from "../create-component.js";

import "@loomidev/components/tag";

export const Tag: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-tag"], "onClose" | "onLoomiTagClick"> & {
    onClose?: (e: LoomiTagEventMap["close"]) => void;
    onLoomiTagClick?: (e: LoomiTagEventMap["loomi-tag-click"]) => void;
    canClose?: JSX.IntrinsicElements["loomi-tag"]["can-close"];
    iconPosition?: JSX.IntrinsicElements["loomi-tag"]["icon-position"];
  }
> = createComponent(
  "loomi-tag",
  { close: "onClose", "loomi-tag-click": "onLoomiTagClick" },
  { canClose: "can-close", iconPosition: "icon-position" },
) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-tag"], "onClose" | "onLoomiTagClick"> & {
    onClose?: (e: LoomiTagEventMap["close"]) => void;
    onLoomiTagClick?: (e: LoomiTagEventMap["loomi-tag-click"]) => void;
    canClose?: JSX.IntrinsicElements["loomi-tag"]["can-close"];
    iconPosition?: JSX.IntrinsicElements["loomi-tag"]["icon-position"];
  }
>;
