// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import type { LoomiTagEventMap } from "@loomidev/components";
import { createComponent } from "../create-component.js";

import "@loomidev/components/tag";

export const Tags: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-tags"], "onChange"> & {
    onChange?: (e: LoomiTagEventMap["change"]) => void;
    selectedValue?: JSX.IntrinsicElements["loomi-tags"]["selected-value"];
  }
> = createComponent(
  "loomi-tags",
  { change: "onChange" },
  { selectedValue: "selected-value" },
) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-tags"], "onChange"> & {
    onChange?: (e: LoomiTagEventMap["change"]) => void;
    selectedValue?: JSX.IntrinsicElements["loomi-tags"]["selected-value"];
  }
>;
