// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import { createComponent } from "../create-component.js";

import "@loomidev/components/text-editor";

export const TextEditor: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-text-editor"], "onLoomiAiGenerate" | "onInput" | "onChange"> & {
    onLoomiAiGenerate?: (e: CustomEvent) => void;
    onInput?: (e: CustomEvent) => void;
    onChange?: (e: CustomEvent) => void;
    labelPosition?: JSX.IntrinsicElements["loomi-text-editor"]["label-position"];
    errorMessage?: JSX.IntrinsicElements["loomi-text-editor"]["error-message"];
    showErrorInline?: JSX.IntrinsicElements["loomi-text-editor"]["show-error-inline"];
    noFileUpload?: JSX.IntrinsicElements["loomi-text-editor"]["no-file-upload"];
  }
> = createComponent(
  "loomi-text-editor",
  { "loomi-ai-generate": "onLoomiAiGenerate", input: "onInput", change: "onChange" },
  {
    labelPosition: "label-position",
    errorMessage: "error-message",
    showErrorInline: "show-error-inline",
    noFileUpload: "no-file-upload",
  },
) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-text-editor"], "onLoomiAiGenerate" | "onInput" | "onChange"> & {
    onLoomiAiGenerate?: (e: CustomEvent) => void;
    onInput?: (e: CustomEvent) => void;
    onChange?: (e: CustomEvent) => void;
    labelPosition?: JSX.IntrinsicElements["loomi-text-editor"]["label-position"];
    errorMessage?: JSX.IntrinsicElements["loomi-text-editor"]["error-message"];
    showErrorInline?: JSX.IntrinsicElements["loomi-text-editor"]["show-error-inline"];
    noFileUpload?: JSX.IntrinsicElements["loomi-text-editor"]["no-file-upload"];
  }
>;
