// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import { createComponent } from "../create-component.js";

import "@loomidev/components/textarea";

export const Textarea: ForwardRefExoticComponent<
  Omit<
    JSX.IntrinsicElements["loomi-textarea"],
    "onLoomiMentionSearch" | "onLoomiMentionSelect" | "onInput" | "onChange"
  > & {
    onLoomiMentionSearch?: (e: CustomEvent) => void;
    onLoomiMentionSelect?: (e: CustomEvent) => void;
    onInput?: (e: CustomEvent) => void;
    onChange?: (e: CustomEvent) => void;
    labelPosition?: JSX.IntrinsicElements["loomi-textarea"]["label-position"];
    errorMessage?: JSX.IntrinsicElements["loomi-textarea"]["error-message"];
    showErrorInline?: JSX.IntrinsicElements["loomi-textarea"]["show-error-inline"];
    showFocusRing?: JSX.IntrinsicElements["loomi-textarea"]["show-focus-ring"];
    mentionTriggers?: JSX.IntrinsicElements["loomi-textarea"]["mention-triggers"];
    mentionData?: JSX.IntrinsicElements["loomi-textarea"]["mention-data"];
  }
> = createComponent(
  "loomi-textarea",
  {
    "loomi-mention-search": "onLoomiMentionSearch",
    "loomi-mention-select": "onLoomiMentionSelect",
    input: "onInput",
    change: "onChange",
  },
  {
    labelPosition: "label-position",
    errorMessage: "error-message",
    showErrorInline: "show-error-inline",
    showFocusRing: "show-focus-ring",
    mentionTriggers: "mention-triggers",
    mentionData: "mention-data",
  },
) as unknown as ForwardRefExoticComponent<
  Omit<
    JSX.IntrinsicElements["loomi-textarea"],
    "onLoomiMentionSearch" | "onLoomiMentionSelect" | "onInput" | "onChange"
  > & {
    onLoomiMentionSearch?: (e: CustomEvent) => void;
    onLoomiMentionSelect?: (e: CustomEvent) => void;
    onInput?: (e: CustomEvent) => void;
    onChange?: (e: CustomEvent) => void;
    labelPosition?: JSX.IntrinsicElements["loomi-textarea"]["label-position"];
    errorMessage?: JSX.IntrinsicElements["loomi-textarea"]["error-message"];
    showErrorInline?: JSX.IntrinsicElements["loomi-textarea"]["show-error-inline"];
    showFocusRing?: JSX.IntrinsicElements["loomi-textarea"]["show-focus-ring"];
    mentionTriggers?: JSX.IntrinsicElements["loomi-textarea"]["mention-triggers"];
    mentionData?: JSX.IntrinsicElements["loomi-textarea"]["mention-data"];
  }
>;
