// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import { createComponent } from "../create-component.js";

import "@loomidev/components/theme-switcher";

export const ThemeSwitcher: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-theme-switcher"], "onLoomiThemeChange"> & {
    onLoomiThemeChange?: (e: CustomEvent) => void;
    lightText?: JSX.IntrinsicElements["loomi-theme-switcher"]["light-text"];
    darkText?: JSX.IntrinsicElements["loomi-theme-switcher"]["dark-text"];
    systemText?: JSX.IntrinsicElements["loomi-theme-switcher"]["system-text"];
    lightIcon?: JSX.IntrinsicElements["loomi-theme-switcher"]["light-icon"];
    darkIcon?: JSX.IntrinsicElements["loomi-theme-switcher"]["dark-icon"];
    systemIcon?: JSX.IntrinsicElements["loomi-theme-switcher"]["system-icon"];
    iconRight?: JSX.IntrinsicElements["loomi-theme-switcher"]["icon-right"];
    showLabels?: JSX.IntrinsicElements["loomi-theme-switcher"]["show-labels"];
  }
> = createComponent(
  "loomi-theme-switcher",
  { "loomi-theme-change": "onLoomiThemeChange" },
  {
    lightText: "light-text",
    darkText: "dark-text",
    systemText: "system-text",
    lightIcon: "light-icon",
    darkIcon: "dark-icon",
    systemIcon: "system-icon",
    iconRight: "icon-right",
    showLabels: "show-labels",
  },
) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-theme-switcher"], "onLoomiThemeChange"> & {
    onLoomiThemeChange?: (e: CustomEvent) => void;
    lightText?: JSX.IntrinsicElements["loomi-theme-switcher"]["light-text"];
    darkText?: JSX.IntrinsicElements["loomi-theme-switcher"]["dark-text"];
    systemText?: JSX.IntrinsicElements["loomi-theme-switcher"]["system-text"];
    lightIcon?: JSX.IntrinsicElements["loomi-theme-switcher"]["light-icon"];
    darkIcon?: JSX.IntrinsicElements["loomi-theme-switcher"]["dark-icon"];
    systemIcon?: JSX.IntrinsicElements["loomi-theme-switcher"]["system-icon"];
    iconRight?: JSX.IntrinsicElements["loomi-theme-switcher"]["icon-right"];
    showLabels?: JSX.IntrinsicElements["loomi-theme-switcher"]["show-labels"];
  }
>;
