// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import { createComponent } from "../create-component.js";

import "@loomidev/components/timeline";

export const Timeline: ForwardRefExoticComponent<JSX.IntrinsicElements["loomi-timeline"]> =
  createComponent("loomi-timeline", {}, {}) as unknown as ForwardRefExoticComponent<
    JSX.IntrinsicElements["loomi-timeline"]
  >;
