// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import { createComponent } from "../create-component.js";

import "@loomidev/components/timeline";

export const TimelineItem: ForwardRefExoticComponent<JSX.IntrinsicElements["loomi-timeline-item"]> =
  createComponent("loomi-timeline-item", {}, {}) as unknown as ForwardRefExoticComponent<
    JSX.IntrinsicElements["loomi-timeline-item"]
  >;
