// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import type { LoomiTimepickerEventMap } from "@loomidev/components";
import { createComponent } from "../create-component.js";

import "@loomidev/components/timepicker";

export const Timepicker: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-timepicker"], "onChange"> & {
    onChange?: (e: LoomiTimepickerEventMap["change"]) => void;
    tpStyle?: JSX.IntrinsicElements["loomi-timepicker"]["tp-style"];
    selectedValue?: JSX.IntrinsicElements["loomi-timepicker"]["selected-value"];
    labelPosition?: JSX.IntrinsicElements["loomi-timepicker"]["label-position"];
    showFocusRing?: JSX.IntrinsicElements["loomi-timepicker"]["show-focus-ring"];
  }
> = createComponent(
  "loomi-timepicker",
  { change: "onChange" },
  {
    tpStyle: "tp-style",
    selectedValue: "selected-value",
    labelPosition: "label-position",
    showFocusRing: "show-focus-ring",
  },
) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-timepicker"], "onChange"> & {
    onChange?: (e: LoomiTimepickerEventMap["change"]) => void;
    tpStyle?: JSX.IntrinsicElements["loomi-timepicker"]["tp-style"];
    selectedValue?: JSX.IntrinsicElements["loomi-timepicker"]["selected-value"];
    labelPosition?: JSX.IntrinsicElements["loomi-timepicker"]["label-position"];
    showFocusRing?: JSX.IntrinsicElements["loomi-timepicker"]["show-focus-ring"];
  }
>;
