// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import { createComponent } from "../create-component.js";

import "@loomidev/components/timer";

export const Timer: ForwardRefExoticComponent<
  Omit<
    JSX.IntrinsicElements["loomi-timer"],
    | "onLoomiTimerStart"
    | "onLoomiTimerPause"
    | "onLoomiTimerReset"
    | "onLoomiTimerTick"
    | "onLoomiTimerComplete"
  > & {
    onLoomiTimerStart?: (e: CustomEvent) => void;
    onLoomiTimerPause?: (e: CustomEvent) => void;
    onLoomiTimerReset?: (e: CustomEvent) => void;
    onLoomiTimerTick?: (e: CustomEvent) => void;
    onLoomiTimerComplete?: (e: CustomEvent) => void;
    startValue?: JSX.IntrinsicElements["loomi-timer"]["start-value"];
    autoStart?: JSX.IntrinsicElements["loomi-timer"]["auto-start"];
    showControls?: JSX.IntrinsicElements["loomi-timer"]["show-controls"];
    showBorder?: JSX.IntrinsicElements["loomi-timer"]["show-border"];
  }
> = createComponent(
  "loomi-timer",
  {
    "loomi-timer-start": "onLoomiTimerStart",
    "loomi-timer-pause": "onLoomiTimerPause",
    "loomi-timer-reset": "onLoomiTimerReset",
    "loomi-timer-tick": "onLoomiTimerTick",
    "loomi-timer-complete": "onLoomiTimerComplete",
  },
  {
    startValue: "start-value",
    autoStart: "auto-start",
    showControls: "show-controls",
    showBorder: "show-border",
  },
) as unknown as ForwardRefExoticComponent<
  Omit<
    JSX.IntrinsicElements["loomi-timer"],
    | "onLoomiTimerStart"
    | "onLoomiTimerPause"
    | "onLoomiTimerReset"
    | "onLoomiTimerTick"
    | "onLoomiTimerComplete"
  > & {
    onLoomiTimerStart?: (e: CustomEvent) => void;
    onLoomiTimerPause?: (e: CustomEvent) => void;
    onLoomiTimerReset?: (e: CustomEvent) => void;
    onLoomiTimerTick?: (e: CustomEvent) => void;
    onLoomiTimerComplete?: (e: CustomEvent) => void;
    startValue?: JSX.IntrinsicElements["loomi-timer"]["start-value"];
    autoStart?: JSX.IntrinsicElements["loomi-timer"]["auto-start"];
    showControls?: JSX.IntrinsicElements["loomi-timer"]["show-controls"];
    showBorder?: JSX.IntrinsicElements["loomi-timer"]["show-border"];
  }
>;
