// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import type { LoomiTimezonepickerEventMap } from "@loomidev/components";
import { createComponent } from "../create-component.js";

import "@loomidev/components/timezonepicker";

export const Timezonepicker: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-timezonepicker"], "onChange" | "onLoomiSelect"> & {
    onChange?: (e: Event) => void;
    onLoomiSelect?: (e: LoomiTimezonepickerEventMap["loomi-select"]) => void;
    ariaLabel?: JSX.IntrinsicElements["loomi-timezonepicker"]["aria-label"];
    labelPosition?: JSX.IntrinsicElements["loomi-timezonepicker"]["label-position"];
    emptyPlaceholder?: JSX.IntrinsicElements["loomi-timezonepicker"]["empty-placeholder"];
  }
> = createComponent(
  "loomi-timezonepicker",
  { change: "onChange", "loomi-select": "onLoomiSelect" },
  {
    ariaLabel: "aria-label",
    labelPosition: "label-position",
    emptyPlaceholder: "empty-placeholder",
  },
) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-timezonepicker"], "onChange" | "onLoomiSelect"> & {
    onChange?: (e: Event) => void;
    onLoomiSelect?: (e: LoomiTimezonepickerEventMap["loomi-select"]) => void;
    ariaLabel?: JSX.IntrinsicElements["loomi-timezonepicker"]["aria-label"];
    labelPosition?: JSX.IntrinsicElements["loomi-timezonepicker"]["label-position"];
    emptyPlaceholder?: JSX.IntrinsicElements["loomi-timezonepicker"]["empty-placeholder"];
  }
>;
