// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import type { LoomiToggleEventMap } from "@loomidev/components";
import { createComponent } from "../create-component.js";

import "@loomidev/components/toggle";

export const Toggle: ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-toggle"], "onChange"> & {
    onChange?: (e: LoomiToggleEventMap["change"]) => void;
    labelPosition?: JSX.IntrinsicElements["loomi-toggle"]["label-position"];
  }
> = createComponent(
  "loomi-toggle",
  { change: "onChange" },
  { labelPosition: "label-position" },
) as unknown as ForwardRefExoticComponent<
  Omit<JSX.IntrinsicElements["loomi-toggle"], "onChange"> & {
    onChange?: (e: LoomiToggleEventMap["change"]) => void;
    labelPosition?: JSX.IntrinsicElements["loomi-toggle"]["label-position"];
  }
>;
