// Generated by scripts/generate-react-wrappers.mjs. Do not edit directly.
import { type ForwardRefExoticComponent } from "react";
import type {} from "@loomidev/react-types";
import { createComponent } from "../create-component.js";

import "@loomidev/components/video";

export const Video: ForwardRefExoticComponent<
  Omit<
    JSX.IntrinsicElements["loomi-video"],
    | "onPlay"
    | "onPause"
    | "onEnded"
    | "onTimeupdate"
    | "onVolumechange"
    | "onFullscreenchange"
    | "onEnterpictureinpicture"
    | "onLoomiVideoError"
  > & {
    onPlay?: (e: CustomEvent) => void;
    onPause?: (e: CustomEvent) => void;
    onEnded?: (e: CustomEvent) => void;
    onTimeupdate?: (e: CustomEvent) => void;
    onVolumechange?: (e: CustomEvent) => void;
    onFullscreenchange?: (e: CustomEvent) => void;
    onEnterpictureinpicture?: (e: CustomEvent) => void;
    onLoomiVideoError?: (e: CustomEvent) => void;
    aspectRatio?: JSX.IntrinsicElements["loomi-video"]["aspect-ratio"];
    autohideControls?: JSX.IntrinsicElements["loomi-video"]["autohide-controls"];
    disablePip?: JSX.IntrinsicElements["loomi-video"]["disable-pip"];
    disableFullscreen?: JSX.IntrinsicElements["loomi-video"]["disable-fullscreen"];
  }
> = createComponent(
  "loomi-video",
  {
    play: "onPlay",
    pause: "onPause",
    ended: "onEnded",
    timeupdate: "onTimeupdate",
    volumechange: "onVolumechange",
    fullscreenchange: "onFullscreenchange",
    enterpictureinpicture: "onEnterpictureinpicture",
    "loomi-video-error": "onLoomiVideoError",
  },
  {
    aspectRatio: "aspect-ratio",
    autohideControls: "autohide-controls",
    disablePip: "disable-pip",
    disableFullscreen: "disable-fullscreen",
  },
) as unknown as ForwardRefExoticComponent<
  Omit<
    JSX.IntrinsicElements["loomi-video"],
    | "onPlay"
    | "onPause"
    | "onEnded"
    | "onTimeupdate"
    | "onVolumechange"
    | "onFullscreenchange"
    | "onEnterpictureinpicture"
    | "onLoomiVideoError"
  > & {
    onPlay?: (e: CustomEvent) => void;
    onPause?: (e: CustomEvent) => void;
    onEnded?: (e: CustomEvent) => void;
    onTimeupdate?: (e: CustomEvent) => void;
    onVolumechange?: (e: CustomEvent) => void;
    onFullscreenchange?: (e: CustomEvent) => void;
    onEnterpictureinpicture?: (e: CustomEvent) => void;
    onLoomiVideoError?: (e: CustomEvent) => void;
    aspectRatio?: JSX.IntrinsicElements["loomi-video"]["aspect-ratio"];
    autohideControls?: JSX.IntrinsicElements["loomi-video"]["autohide-controls"];
    disablePip?: JSX.IntrinsicElements["loomi-video"]["disable-pip"];
    disableFullscreen?: JSX.IntrinsicElements["loomi-video"]["disable-fullscreen"];
  }
>;
