// Compiles this component's Tailwind utilities ONCE at build time and inlines the
// result into `src/generated/styles.css.ts` (a Lit CSSResult). Published packages
// therefore contain zero Tailwind runtime coupling and no global CSS — every class
// lives inside the component's Shadow DOM.
//
// The color utilities resolve through `var(--loomi-*)` (never hardcoded hex), because
// we feed Tailwind a `@theme inline` mapping built from @loomi/theme's palette.json.
// Runtime-interpolated class names like `bg-${color}-600` are emitted via a safelist
// (`@source inline(...)`) since Tailwind's scanner can't see string interpolation.

import { createRequire } from "node:module";
import { spawnSync } from "node:child_process";
import {
  readFileSync,
  writeFileSync,
  mkdirSync,
  rmSync,
  existsSync,
} from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const require = createRequire(import.meta.url);
const __dirname = dirname(fileURLToPath(import.meta.url));
const pkgRoot = resolve(__dirname, "..");

// --- palette (single source of truth, from @loomi/theme) ---
const palette = JSON.parse(
  readFileSync(require.resolve("@loomi/theme/palette.json"), "utf8"),
);
const { colors, shades } = palette;
const prefix = palette.prefix ?? "loomi";

// --- 1. color mapping: Tailwind utilities -> overridable --<prefix>-* slots (no hex) ---
const colorMap = [];
for (const color of colors) {
  for (const shade of shades) {
    // Public override slot first, private default (declared on :host by @loomi/theme)
    // as the fallback. Declaring the public slot on :host would block :root overrides,
    // so it is referenced — never declared — here.
    colorMap.push(
      `  --color-${color}-${shade}: var(--${prefix}-${color}-${shade}, var(--_${prefix}-${color}-${shade}-default));`,
    );
  }
}

// --- 2. safelist: every color/shade for the props a button can apply at runtime ---
const variants = ["", "hover:", "focus-visible:"];
const props = ["bg", "text", "border", "ring"];
const safeShades = [50, 100, 200, 300, 400, 500, 600, 700, 800];
const colorList = colors.join(",");
const shadeList = safeShades.join(",");
const variantList = variants.join(",");
const propList = props.join(",");
const safelist = `@source inline("{${variantList}}{${propList}}-{${colorList}}-{${shadeList}}");`;

// --- assemble the Tailwind input ---
const passthrough = readFileSync(resolve(pkgRoot, "src/styles.css"), "utf8");

const input = `@layer theme, base, components, utilities;
@import "tailwindcss/theme.css" layer(theme);
@import "tailwindcss/utilities.css" layer(utilities);

@theme inline {
${colorMap.join("\n")}
}

/* Safelist for runtime-interpolated class names (bg-\${color}-600, etc.). */
${safelist}

/* Scan only authored sources for statically-used utilities. */
@source "./src/loomi-button.ts";
@source "./src/icons.ts";

/* ---- component-scoped plain CSS (passed through untouched) ---- */
${passthrough}
`;

const inputPath = resolve(pkgRoot, ".loomi-tw-input.css");
const outputPath = resolve(pkgRoot, ".loomi-tw-output.css");
writeFileSync(inputPath, input);

// --- resolve the Tailwind CLI entry and run it ---
const cliPkgJson = require.resolve("@tailwindcss/cli/package.json");
const cliDir = dirname(cliPkgJson);
const cliManifest = JSON.parse(readFileSync(cliPkgJson, "utf8"));
const binRel =
  typeof cliManifest.bin === "string"
    ? cliManifest.bin
    : cliManifest.bin.tailwindcss;
const cliEntry = resolve(cliDir, binRel);

const result = spawnSync(
  process.execPath,
  [cliEntry, "--input", inputPath, "--output", outputPath, "--minify"],
  { cwd: pkgRoot, stdio: ["ignore", "inherit", "inherit"] },
);

if (result.status !== 0) {
  rmSync(inputPath, { force: true });
  throw new Error(`Tailwind CLI failed with exit code ${result.status}`);
}

const compiled = readFileSync(outputPath, "utf8").trim();

// --- emit the Lit CSSResult ---
const generated = `// Generated by @loomi/button — do not edit by hand. Run \`pnpm build\` to regenerate.
import { unsafeCSS } from "lit";

/** Compiled, Shadow-DOM-scoped styles for <loomi-button>. Colors resolve via \`var(--loomi-*)\`. */
export const buttonStyles = unsafeCSS(${JSON.stringify(compiled)});
`;

mkdirSync(resolve(pkgRoot, "src/generated"), { recursive: true });
writeFileSync(resolve(pkgRoot, "src/generated/styles.css.ts"), generated);

// --- cleanup temp artifacts ---
rmSync(inputPath, { force: true });
if (existsSync(outputPath)) rmSync(outputPath, { force: true });

console.log(
  `[@loomi/button] compiled styles (${(compiled.length / 1024).toFixed(1)} kB) ` +
    `with ${colors.length} colors safelisted.`,
);
