// Generates the loomi design tokens.
//
//   1. src/generated/tokens.css.ts  -> `themeStyles` (a Lit CSSResult) containing the
//      `:host` block that declares every `--loomi-<color>-<shade>` slot with a sensible
//      default, plus a small base reset. This is what every component pulls in so the
//      `var(--loomi-*)` references in compiled utilities resolve inside the Shadow DOM.
//
//   2. src/tailwind-colors.css -> a `@theme inline { --color-*: var(--loomi-*) }` block
//      for authoring components against Tailwind. It contains NO hex values; it only maps
//      Tailwind color utilities onto the overridable `--loomi-*` slots.
//
// Default color VALUES are read straight from Tailwind's own default ramps so we never
// hand-type hex/oklch and never drift from a recognised palette.

import { createRequire } from "node:module";
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const require = createRequire(import.meta.url);
const __dirname = dirname(fileURLToPath(import.meta.url));
const pkgRoot = resolve(__dirname, "..");

const palette = JSON.parse(
  readFileSync(resolve(pkgRoot, "palette.json"), "utf8"),
);
const { colors, shades, ramps } = palette;
const prefix = palette.prefix ?? "loomi";
const pub = (color, shade) => `--${prefix}-${color}-${shade}`; // public override slot
const priv = (color, shade) => `--_${prefix}-${color}-${shade}-default`; // private default

// --- read Tailwind's default color ramps (oklch) as the source of default values ---
const twTheme = readFileSync(require.resolve("tailwindcss/theme.css"), "utf8");
const defaults = {}; // { ramp: { shade: value } }
const re = /--color-([a-z]+)-(\d+)\s*:\s*([^;]+);/g;
let m;
while ((m = re.exec(twTheme)) !== null) {
  const [, ramp, shade, value] = m;
  (defaults[ramp] ??= {})[shade] = value.trim();
}

function defaultFor(colorName, shade) {
  const ramp = ramps[colorName] ?? colorName;
  const value = defaults[ramp]?.[String(shade)];
  if (!value) {
    throw new Error(
      `No Tailwind default found for ramp "${ramp}" shade ${shade} (color "${colorName}"). ` +
        `Check packages/theme/palette.json against your installed tailwindcss version.`,
    );
  }
  return value;
}

// --- 1. tokens (:host defaults) ---
//
// IMPORTANT: defaults are declared as PRIVATE slots `--_loomi-<color>-<shade>` on
// :host, not as the public `--loomi-<color>-<shade>` slot. If we declared the public
// slot on :host, that element-local declaration would beat any value inherited from
// the consumer's :root/body, making global theme overrides impossible. Instead,
// utilities resolve `var(--loomi-X, var(--_loomi-X-default))`: the public slot is left
// undeclared (so a :root override inherits straight through the shadow boundary), and
// the private slot supplies the fallback default. No hex ever lands in a utility.
const tokenLines = [];
for (const color of colors) {
  for (const shade of shades) {
    tokenLines.push(`  ${priv(color, shade)}: ${defaultFor(color, shade)};`);
  }
}

const tokensCss = `/* Generated by @loomi/theme — do not edit by hand. */
:host {
  /* Base tokens */
  --${prefix}-font-sans: ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto,
    Helvetica, Arial, sans-serif;
  --${prefix}-white: #ffffff;
  font-family: var(--${prefix}-font-sans);

  /* Private default values for each palette slot. Override the PUBLIC slot from your
     page instead, e.g. :root { ${pub("primary", 600)}: #16a34a; } (no build, no Tailwind).
     Public slots are intentionally NOT declared here so :root overrides inherit in. */
${tokenLines.join("\n")}
}

/* Minimal, Shadow-DOM-scoped reset so components render predictably. */
*,
*::before,
*::after {
  box-sizing: border-box;
}
`;

const tokensTs = `// Generated by @loomi/theme — do not edit by hand. Run \`pnpm build\` to regenerate.
import { unsafeCSS } from "lit";

/**
 * Shared loomi design tokens as a Lit \`CSSResult\`.
 *
 * Add this first in a component's \`static styles\` so every \`var(--loomi-*)\`
 * reference resolves inside the Shadow DOM. Consumers override any slot from
 * their own page CSS (e.g. \`:root { --loomi-primary-600: #16a34a; }\`); custom
 * properties inherit through the shadow boundary, so no rebuild is needed.
 */
export const themeStyles = unsafeCSS(${JSON.stringify(tokensCss)});
`;

mkdirSync(resolve(pkgRoot, "src/generated"), { recursive: true });
writeFileSync(resolve(pkgRoot, "src/generated/tokens.css.ts"), tokensTs);

// --- typed palette consts (so TS never imports the root JSON across rootDir) ---
const paletteTs = `// Generated by @loomi/theme — do not edit by hand. Run \`pnpm build\` to regenerate.
export const LOOMI_COLORS = ${JSON.stringify(colors)} as const;
export const LOOMI_SHADES = ${JSON.stringify(shades)} as const;
export type LoomiColor = (typeof LOOMI_COLORS)[number];
export type LoomiShade = (typeof LOOMI_SHADES)[number];
`;
writeFileSync(resolve(pkgRoot, "src/generated/palette.gen.ts"), paletteTs);

// --- 2. Tailwind color mapping (no hex; maps utilities onto --loomi-* slots) ---
const mapLines = [];
for (const color of colors) {
  for (const shade of shades) {
    mapLines.push(
      `  --color-${color}-${shade}: var(${pub(color, shade)}, ${priv(color, shade)});`,
    );
  }
}

const colorsCss = `/* Generated by @loomi/theme — do not edit by hand.
 *
 * Tailwind color mapping for authoring loomi components. Using \`@theme inline\`
 * means the value is substituted directly into generated utilities
 * (\`.bg-primary-600 { background-color: var(--loomi-primary-600, var(--_loomi-primary-600-default)) }\`)
 * and Tailwind does NOT emit its own \`--color-*\` variables. The public \`--loomi-*\`
 * slot is the override hook; the private \`--_loomi-*-default\` slot (declared on :host
 * in tokens.css) supplies the default. No hex lands in a utility.
 *
 * Component build scripts read \`palette.json\` directly to embed this block, so
 * this file is primarily a reference for editor tooling / manual authoring.
 */
@theme inline {
${mapLines.join("\n")}
}
`;

writeFileSync(resolve(pkgRoot, "src/tailwind-colors.css"), colorsCss);

console.log(
  `[@loomi/theme] generated ${colors.length} colors x ${shades.length} shades ` +
    `(${tokenLines.length} token slots).`,
);
