import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const pkgRoot = resolve(__dirname, "..");
const css = readFileSync(resolve(pkgRoot, "src/styles.css"), "utf8").trim();

const generated = `// Generated by @loomidev/password — do not edit by hand. Run \`pnpm build\` to regenerate.
import { unsafeCSS } from "lit";

/** Compiled, Shadow-DOM-scoped styles. Colors resolve via \`var(--loomi-*)\`. */
export const componentStyles = unsafeCSS(${JSON.stringify(css)});
`;

mkdirSync(resolve(pkgRoot, "src/generated"), { recursive: true });
writeFileSync(resolve(pkgRoot, "src/generated/styles.css.ts"), generated);
console.log(`[@loomidev/password] compiled styles (${(css.length / 1024).toFixed(1)} kB).`);
