// Generated by scripts/generate-react-types.mjs. Do not edit directly.
import type { HTMLAttributes, RefAttributes } from "react";
import type { LoomiElement } from "@loomidev/core";
import type {} from "@loomidev/components";

type LoomiAttributeValue = string | number | boolean | undefined;
type LoomiOwnPropertyNames<T extends LoomiElement> = {
  [K in Exclude<keyof T, keyof LoomiElement>]: T[K] extends (...args: never[]) => unknown
    ? never
    : K;
}[Exclude<keyof T, keyof LoomiElement>];
type LoomiOwnProperties<T extends LoomiElement> = Partial<Pick<T, LoomiOwnPropertyNames<T>>>;

export type LoomiReactProps<
  T extends LoomiElement,
  TAttributes extends object = Record<never, never>,
> = Omit<HTMLAttributes<T>, keyof LoomiOwnProperties<T> | keyof TAttributes> &
  RefAttributes<T> &
  LoomiOwnProperties<T> &
  TAttributes & {
    name?: string;
  };

interface LoomiAccordionAttributes {
  "can-open-multiple"?: LoomiAttributeValue;
}

interface LoomiAccordionItemAttributes {
  "no-padding"?: LoomiAttributeValue;
}

interface LoomiAlertAttributes {
  "icon-placement"?: LoomiAttributeValue;
  "show-close-icon"?: LoomiAttributeValue;
  "show-icon"?: LoomiAttributeValue;
  "show-ring"?: LoomiAttributeValue;
}

interface LoomiArcMeterAttributes {
  "active-marker"?: LoomiAttributeValue;
  "marker-color"?: LoomiAttributeValue;
}

interface LoomiAutocompleteAttributes {
  "description-key"?: LoomiAttributeValue;
  "image-key"?: LoomiAttributeValue;
  "label-key"?: LoomiAttributeValue;
  "label-position"?: LoomiAttributeValue;
  "selected-value"?: LoomiAttributeValue;
  "show-focus-ring"?: LoomiAttributeValue;
  "value-key"?: LoomiAttributeValue;
}

interface LoomiAvatarAttributes {
  "bg-color"?: LoomiAttributeValue;
  "dot-color"?: LoomiAttributeValue;
  "dot-position"?: LoomiAttributeValue;
  "edit-label"?: LoomiAttributeValue;
  "pulse-dot"?: LoomiAttributeValue;
  "show-ring"?: LoomiAttributeValue;
}

interface LoomiAvatarsAttributes {
  "dot-color"?: LoomiAttributeValue;
  "dot-position"?: LoomiAttributeValue;
  "pulse-dot"?: LoomiAttributeValue;
  "stack-space"?: LoomiAttributeValue;
}

interface LoomiBellAttributes {
  "animate-dot"?: LoomiAttributeValue;
  "show-dot"?: LoomiAttributeValue;
}

interface LoomiBottomNavAttributes {
  "active-style"?: LoomiAttributeValue;
  "icon-source"?: LoomiAttributeValue;
  "mobile-only"?: LoomiAttributeValue;
}

interface LoomiBottomNavItemAttributes {
  "active-style"?: LoomiAttributeValue;
  "icon-source"?: LoomiAttributeValue;
  "prevent-default"?: LoomiAttributeValue;
}

interface LoomiButtonAttributes {
  "border-width"?: LoomiAttributeValue;
  "can-submit"?: LoomiAttributeValue;
  "has-spinner"?: LoomiAttributeValue;
  "icon-right"?: LoomiAttributeValue;
  "show-focus-ring"?: LoomiAttributeValue;
  "show-spinner"?: LoomiAttributeValue;
}

interface LoomiButtonGroupAttributes {
  "aria-label"?: LoomiAttributeValue;
  "icon-only"?: LoomiAttributeValue;
}

interface LoomiButtonGroupItemAttributes {
  "aria-label"?: LoomiAttributeValue;
  "icon-only"?: LoomiAttributeValue;
  "icon-right"?: LoomiAttributeValue;
}

interface LoomiCalendarAttributes {
  "end-hour"?: LoomiAttributeValue;
  "show-sidebar"?: LoomiAttributeValue;
  "show-timezone"?: LoomiAttributeValue;
  "show-weekends"?: LoomiAttributeValue;
  "sidebar-open"?: LoomiAttributeValue;
  "slot-minutes"?: LoomiAttributeValue;
  "start-hour"?: LoomiAttributeValue;
  "week-starts"?: LoomiAttributeValue;
}

interface LoomiCardAttributes {
  "has-border"?: LoomiAttributeValue;
  "has-hover"?: LoomiAttributeValue;
  "has-shadow"?: LoomiAttributeValue;
}

interface LoomiCardActionAttributes {}

interface LoomiCardContentAttributes {}

interface LoomiCardDescriptionAttributes {}

interface LoomiCardFooterAttributes {}

interface LoomiCardHeaderAttributes {}

interface LoomiCardTitleAttributes {}

interface LoomiCenteredContentAttributes {
  "max-width"?: LoomiAttributeValue;
  "min-height"?: LoomiAttributeValue;
}

interface LoomiChartAttributes {
  "donut-radius"?: LoomiAttributeValue;
  "legend-position"?: LoomiAttributeValue;
  "series-label"?: LoomiAttributeValue;
  "series2-label"?: LoomiAttributeValue;
  "series2-type"?: LoomiAttributeValue;
  "series3-label"?: LoomiAttributeValue;
  "show-border"?: LoomiAttributeValue;
  "show-grid"?: LoomiAttributeValue;
  "show-legend"?: LoomiAttributeValue;
  "show-tooltip"?: LoomiAttributeValue;
  "show-y-axis"?: LoomiAttributeValue;
  "with-gap"?: LoomiAttributeValue;
}

interface LoomiChatMessageAttributes {
  "avatar-label"?: LoomiAttributeValue;
  "bubble-color"?: LoomiAttributeValue;
  "sender-id"?: LoomiAttributeValue;
  "show-avatar"?: LoomiAttributeValue;
  "show-sender"?: LoomiAttributeValue;
}

interface LoomiChatWindowAttributes {
  "active-conversation-id"?: LoomiAttributeValue;
  "auto-scroll"?: LoomiAttributeValue;
  "conversations-avatars-only"?: LoomiAttributeValue;
  "current-user-id"?: LoomiAttributeValue;
  "empty-description"?: LoomiAttributeValue;
  "empty-title"?: LoomiAttributeValue;
  "footer-note"?: LoomiAttributeValue;
  "input-max-rows"?: LoomiAttributeValue;
  "input-placeholder"?: LoomiAttributeValue;
  "input-rows"?: LoomiAttributeValue;
  "loading-icon"?: LoomiAttributeValue;
  "loading-text"?: LoomiAttributeValue;
  "read-only"?: LoomiAttributeValue;
  "show-avatars"?: LoomiAttributeValue;
  "show-conversations"?: LoomiAttributeValue;
  "show-header-avatars"?: LoomiAttributeValue;
  "show-reset"?: LoomiAttributeValue;
  "window-height"?: LoomiAttributeValue;
}

interface LoomiCheckboxAttributes {}

interface LoomiCheckcardAttributes {
  "align-items"?: LoomiAttributeValue;
}

interface LoomiCheckcardsAttributes {
  "align-items"?: LoomiAttributeValue;
  "auto-select-new"?: LoomiAttributeValue;
  "border-color"?: LoomiAttributeValue;
  "border-width"?: LoomiAttributeValue;
  "selected-value"?: LoomiAttributeValue;
}

interface LoomiClipboardAttributes {
  "copied-label"?: LoomiAttributeValue;
  "copy-label"?: LoomiAttributeValue;
}

interface LoomiColorpickerAttributes {
  "selected-value"?: LoomiAttributeValue;
  "show-value"?: LoomiAttributeValue;
}

interface LoomiCommandPaletteAttributes {
  "empty-description"?: LoomiAttributeValue;
  "empty-title"?: LoomiAttributeValue;
}

interface LoomiContactCardAttributes {
  "has-hover"?: LoomiAttributeValue;
  "has-shadow"?: LoomiAttributeValue;
  "no-padding"?: LoomiAttributeValue;
}

interface LoomiContextMenuAttributes {
  "hide-after-click"?: LoomiAttributeValue;
  "icon-right"?: LoomiAttributeValue;
}

interface LoomiContextMenuItemAttributes {
  "icon-right"?: LoomiAttributeValue;
}

interface LoomiCountriesAttributes {
  "empty-placeholder"?: LoomiAttributeValue;
  "label-position"?: LoomiAttributeValue;
}

interface LoomiCreditcardAttributes {
  "cardholder-name"?: LoomiAttributeValue;
  "error-message"?: LoomiAttributeValue;
  "expiry-month"?: LoomiAttributeValue;
  "expiry-year"?: LoomiAttributeValue;
  "show-error-inline"?: LoomiAttributeValue;
}

interface LoomiDataGridAttributes {
  "empty-description"?: LoomiAttributeValue;
  "empty-title"?: LoomiAttributeValue;
  "max-height"?: LoomiAttributeValue;
  "page-size"?: LoomiAttributeValue;
  "row-key"?: LoomiAttributeValue;
  "server-side"?: LoomiAttributeValue;
  "sticky-header"?: LoomiAttributeValue;
  "total-rows"?: LoomiAttributeValue;
}

interface LoomiDateRangePickerAttributes {
  "compare-end-date"?: LoomiAttributeValue;
  "compare-start-date"?: LoomiAttributeValue;
  "end-date"?: LoomiAttributeValue;
  "preset-id"?: LoomiAttributeValue;
  "show-presets"?: LoomiAttributeValue;
  "start-date"?: LoomiAttributeValue;
}

interface LoomiDatepickerAttributes {
  "dp-style"?: LoomiAttributeValue;
  "label-position"?: LoomiAttributeValue;
  "max-date"?: LoomiAttributeValue;
  "min-date"?: LoomiAttributeValue;
  "selected-value"?: LoomiAttributeValue;
  "week-starts"?: LoomiAttributeValue;
}

interface LoomiDividerAttributes {}

interface LoomiDrawerAttributes {
  "close-on-outside-click"?: LoomiAttributeValue;
  "prevent-scroll"?: LoomiAttributeValue;
  "show-close-icon"?: LoomiAttributeValue;
}

interface LoomiDropmenuAttributes {
  "hide-after-click"?: LoomiAttributeValue;
  "icon-right"?: LoomiAttributeValue;
  "trigger-on"?: LoomiAttributeValue;
}

interface LoomiDropmenuItemAttributes {
  "icon-right"?: LoomiAttributeValue;
}

interface LoomiEmojiPickerAttributes {
  "empty-text"?: LoomiAttributeValue;
  "selected-value"?: LoomiAttributeValue;
  "show-categories"?: LoomiAttributeValue;
  "show-text"?: LoomiAttributeValue;
}

interface LoomiEmptyStateAttributes {
  "button-label"?: LoomiAttributeValue;
  "image-size"?: LoomiAttributeValue;
  "show-image"?: LoomiAttributeValue;
}

interface LoomiFabAttributes {
  "close-on-select"?: LoomiAttributeValue;
  "icon-source"?: LoomiAttributeValue;
  "icons-only"?: LoomiAttributeValue;
}

interface LoomiFabItemAttributes {
  "icon-source"?: LoomiAttributeValue;
}

interface LoomiFilepickerAttributes {
  "accepted-file-types"?: LoomiAttributeValue;
  "can-browse"?: LoomiAttributeValue;
  "can-drop"?: LoomiAttributeValue;
  "crop-aspect-ratio"?: LoomiAttributeValue;
  "has-border"?: LoomiAttributeValue;
  "max-file-size"?: LoomiAttributeValue;
  "max-files"?: LoomiAttributeValue;
  "placeholder-line1"?: LoomiAttributeValue;
  "placeholder-line2"?: LoomiAttributeValue;
  "resize-height"?: LoomiAttributeValue;
  "resize-width"?: LoomiAttributeValue;
  "show-image-preview"?: LoomiAttributeValue;
}

interface LoomiFilterBuilderAttributes {
  "add-label"?: LoomiAttributeValue;
  "apply-label"?: LoomiAttributeValue;
  "empty-label"?: LoomiAttributeValue;
  "show-apply"?: LoomiAttributeValue;
}

interface LoomiFloatingPanelAttributes {
  "auto-save-id"?: LoomiAttributeValue;
  "drag-handle"?: LoomiAttributeValue;
  "max-height"?: LoomiAttributeValue;
  "max-width"?: LoomiAttributeValue;
  "min-height"?: LoomiAttributeValue;
  "min-width"?: LoomiAttributeValue;
  "no-drag"?: LoomiAttributeValue;
  "show-close-icon"?: LoomiAttributeValue;
}

interface LoomiHorizontalLineGraphAttributes {
  "show-legend"?: LoomiAttributeValue;
  "show-values"?: LoomiAttributeValue;
}

interface LoomiIconAttributes {
  "stroke-width"?: LoomiAttributeValue;
}

interface LoomiInputAttributes {
  "dynamic-mask"?: LoomiAttributeValue;
  "error-message"?: LoomiAttributeValue;
  "label-position"?: LoomiAttributeValue;
  "prefix-icon"?: LoomiAttributeValue;
  "prefix-options"?: LoomiAttributeValue;
  "prefix-value"?: LoomiAttributeValue;
  "show-error-inline"?: LoomiAttributeValue;
  "show-focus-ring"?: LoomiAttributeValue;
  "show-placeholder-always"?: LoomiAttributeValue;
  "suffix-icon"?: LoomiAttributeValue;
  "suffix-options"?: LoomiAttributeValue;
  "suffix-value"?: LoomiAttributeValue;
  "transparent-prefix"?: LoomiAttributeValue;
  "transparent-suffix"?: LoomiAttributeValue;
  "with-dots"?: LoomiAttributeValue;
}

interface LoomiLightboxImageAttributes {}

interface LoomiListviewAttributes {}

interface LoomiListviewItemAttributes {
  "as-flex"?: LoomiAttributeValue;
}

interface LoomiModalAttributes {
  "align-buttons"?: LoomiAttributeValue;
  "backdrop-can-close"?: LoomiAttributeValue;
  "blur-size"?: LoomiAttributeValue;
  "cancel-button-label"?: LoomiAttributeValue;
  "close-after-action"?: LoomiAttributeValue;
  "icon-source"?: LoomiAttributeValue;
  "ok-button-label"?: LoomiAttributeValue;
  "prevent-scroll"?: LoomiAttributeValue;
  "show-action-buttons"?: LoomiAttributeValue;
  "show-close-icon"?: LoomiAttributeValue;
  "stretch-action-buttons"?: LoomiAttributeValue;
}

interface LoomiNotificationAttributes {
  "full-width"?: LoomiAttributeValue;
}

interface LoomiNumberAttributes {
  "label-position"?: LoomiAttributeValue;
  "transparent-icons"?: LoomiAttributeValue;
  "with-dots"?: LoomiAttributeValue;
}

interface LoomiOtpAttributes {
  "error-message"?: LoomiAttributeValue;
  "hide-digits"?: LoomiAttributeValue;
  "show-error-inline"?: LoomiAttributeValue;
  "total-digits"?: LoomiAttributeValue;
}

interface LoomiPaginationAttributes {
  "page-size"?: LoomiAttributeValue;
  "pagination-style"?: LoomiAttributeValue;
  "show-page-number"?: LoomiAttributeValue;
  "show-total"?: LoomiAttributeValue;
  "show-total-pages"?: LoomiAttributeValue;
  "total-label"?: LoomiAttributeValue;
}

interface LoomiPasswordAttributes {
  "error-message"?: LoomiAttributeValue;
  "label-position"?: LoomiAttributeValue;
  "prefix-icon"?: LoomiAttributeValue;
  "prefix-options"?: LoomiAttributeValue;
  "prefix-value"?: LoomiAttributeValue;
  "show-error-inline"?: LoomiAttributeValue;
  "show-placeholder-always"?: LoomiAttributeValue;
  "strength-color"?: LoomiAttributeValue;
  "transparent-prefix"?: LoomiAttributeValue;
}

interface LoomiPhotoGalleryAttributes {
  "album-panel-open"?: LoomiAttributeValue;
  "album-view"?: LoomiAttributeValue;
  "lightbox-show-close"?: LoomiAttributeValue;
  "lightbox-show-favourite"?: LoomiAttributeValue;
  "lightbox-show-rotate"?: LoomiAttributeValue;
  "lightbox-show-share"?: LoomiAttributeValue;
  "lightbox-show-zoom-in"?: LoomiAttributeValue;
  "lightbox-show-zoom-out"?: LoomiAttributeValue;
  "show-album-toggle"?: LoomiAttributeValue;
  "show-slideshow"?: LoomiAttributeValue;
  "show-square-toggle"?: LoomiAttributeValue;
  "show-zoom-in"?: LoomiAttributeValue;
  "show-zoom-out"?: LoomiAttributeValue;
  "slideshow-interval"?: LoomiAttributeValue;
  "square-thumbnails"?: LoomiAttributeValue;
  "thumb-size"?: LoomiAttributeValue;
}

interface LoomiPhotoGalleryItemAttributes {}

interface LoomiPopoverAttributes {
  "trigger-on"?: LoomiAttributeValue;
}

interface LoomiProcessingAttributes {}

interface LoomiProfileMenuAttributes {
  "avatar-alt"?: LoomiAttributeValue;
  "avatar-bg-color"?: LoomiAttributeValue;
  "avatar-label"?: LoomiAttributeValue;
  "avatar-position"?: LoomiAttributeValue;
  "avatar-size"?: LoomiAttributeValue;
  "dot-color"?: LoomiAttributeValue;
  "dot-position"?: LoomiAttributeValue;
  "has-hover"?: LoomiAttributeValue;
  "hide-after-click"?: LoomiAttributeValue;
  "pulse-dot"?: LoomiAttributeValue;
  "trigger-label"?: LoomiAttributeValue;
}

interface LoomiProgressBarAttributes {
  "percentage-label-position"?: LoomiAttributeValue;
  "percentage-prefix"?: LoomiAttributeValue;
  "percentage-suffix"?: LoomiAttributeValue;
  "show-percentage-label"?: LoomiAttributeValue;
  "show-percentage-label-inline"?: LoomiAttributeValue;
  "show-percentage-tooltip"?: LoomiAttributeValue;
}

interface LoomiProgressCircleAttributes {
  "circle-width"?: LoomiAttributeValue;
  "show-label"?: LoomiAttributeValue;
  "show-percent"?: LoomiAttributeValue;
}

interface LoomiProgressStepAttributes {
  "hide-index"?: LoomiAttributeValue;
  "step-index"?: LoomiAttributeValue;
}

interface LoomiProgressStepsAttributes {}

interface LoomiQrcodeAttributes {
  "aria-label"?: LoomiAttributeValue;
  "corner-border-color"?: LoomiAttributeValue;
  "corner-border-length"?: LoomiAttributeValue;
  "corner-border-width"?: LoomiAttributeValue;
  "corner-borders"?: LoomiAttributeValue;
  "error-correction"?: LoomiAttributeValue;
  "gradient-from"?: LoomiAttributeValue;
  "gradient-scan"?: LoomiAttributeValue;
  "gradient-to"?: LoomiAttributeValue;
  "module-radius"?: LoomiAttributeValue;
  "quiet-zone"?: LoomiAttributeValue;
  "scan-color"?: LoomiAttributeValue;
  "scan-count"?: LoomiAttributeValue;
  "scan-duration"?: LoomiAttributeValue;
}

interface LoomiRadioAttributes {}

interface LoomiRatingAttributes {}

interface LoomiResizableHandleAttributes {
  "with-handle"?: LoomiAttributeValue;
}

interface LoomiResizablePanelAttributes {
  "collapsed-size"?: LoomiAttributeValue;
  "default-size"?: LoomiAttributeValue;
  "max-size"?: LoomiAttributeValue;
  "min-size"?: LoomiAttributeValue;
  "panel-id"?: LoomiAttributeValue;
}

interface LoomiResizablePanelGroupAttributes {
  "auto-save-id"?: LoomiAttributeValue;
}

interface LoomiScrollerAttributes {
  "blurred-edges"?: LoomiAttributeValue;
  "edge-size"?: LoomiAttributeValue;
  "pause-on-hover"?: LoomiAttributeValue;
  "scroll-count"?: LoomiAttributeValue;
}

interface LoomiSelectAttributes {
  "empty-action-label"?: LoomiAttributeValue;
  "empty-action-url"?: LoomiAttributeValue;
  "empty-placeholder"?: LoomiAttributeValue;
  "image-key"?: LoomiAttributeValue;
  "label-key"?: LoomiAttributeValue;
  "label-position"?: LoomiAttributeValue;
  "max-selectable"?: LoomiAttributeValue;
  "selected-value"?: LoomiAttributeValue;
  "show-focus-ring"?: LoomiAttributeValue;
  "value-key"?: LoomiAttributeValue;
}

interface LoomiSideNavAttributes {
  "collapse-mode"?: LoomiAttributeValue;
  "icon-size"?: LoomiAttributeValue;
}

interface LoomiSideNavItemAttributes {}

interface LoomiSliderAttributes {
  "handle-variant"?: LoomiAttributeValue;
  "handle-width"?: LoomiAttributeValue;
  "selected-end"?: LoomiAttributeValue;
  "show-tooltip"?: LoomiAttributeValue;
  "show-values"?: LoomiAttributeValue;
  "track-radius"?: LoomiAttributeValue;
  "value-target"?: LoomiAttributeValue;
}

interface LoomiSortableAttributes {
  "handle-icon"?: LoomiAttributeValue;
  "has-handle"?: LoomiAttributeValue;
  "multi-drag"?: LoomiAttributeValue;
  "selected-class"?: LoomiAttributeValue;
  "swap-class"?: LoomiAttributeValue;
}

interface LoomiSpinnerAttributes {}

interface LoomiSplitButtonAttributes {
  "border-width"?: LoomiAttributeValue;
  "can-submit"?: LoomiAttributeValue;
  "has-spinner"?: LoomiAttributeValue;
  "hide-after-click"?: LoomiAttributeValue;
  "icon-right"?: LoomiAttributeValue;
  "menu-disabled"?: LoomiAttributeValue;
  "menu-label"?: LoomiAttributeValue;
  "show-spinner"?: LoomiAttributeValue;
}

interface LoomiStatisticAttributes {
  "currency-position"?: LoomiAttributeValue;
  "has-border"?: LoomiAttributeValue;
  "has-shadow"?: LoomiAttributeValue;
  "icon-color"?: LoomiAttributeValue;
  "icon-position"?: LoomiAttributeValue;
  "icon-size"?: LoomiAttributeValue;
  "label-position"?: LoomiAttributeValue;
  "show-spinner"?: LoomiAttributeValue;
}

interface LoomiTabAttributes {}

interface LoomiTableAttributes {
  "action-icons"?: LoomiAttributeValue;
  "actions-title"?: LoomiAttributeValue;
  "button-label"?: LoomiAttributeValue;
  "column-aliases"?: LoomiAttributeValue;
  "default-page"?: LoomiAttributeValue;
  "exclude-columns"?: LoomiAttributeValue;
  "group-by"?: LoomiAttributeValue;
  "has-border"?: LoomiAttributeValue;
  "has-hover"?: LoomiAttributeValue;
  "has-shadow"?: LoomiAttributeValue;
  "id-key"?: LoomiAttributeValue;
  "include-columns"?: LoomiAttributeValue;
  "message-as-empty-state"?: LoomiAttributeValue;
  "no-data-message"?: LoomiAttributeValue;
  "page-size"?: LoomiAttributeValue;
  "pagination-style"?: LoomiAttributeValue;
  "row-template"?: LoomiAttributeValue;
  "search-container"?: LoomiAttributeValue;
  "search-placeholder"?: LoomiAttributeValue;
  "selected-value"?: LoomiAttributeValue;
  "show-image"?: LoomiAttributeValue;
  "show-page-number"?: LoomiAttributeValue;
  "show-row-numbers"?: LoomiAttributeValue;
  "show-total"?: LoomiAttributeValue;
  "show-total-pages"?: LoomiAttributeValue;
  "sortable-columns"?: LoomiAttributeValue;
  "total-label"?: LoomiAttributeValue;
}

interface LoomiTabsAttributes {
  "tab-style"?: LoomiAttributeValue;
}

interface LoomiTagAttributes {
  "can-close"?: LoomiAttributeValue;
  "icon-position"?: LoomiAttributeValue;
}

interface LoomiTagInputAttributes {
  "autocomplete-data"?: LoomiAttributeValue;
  "autocomplete-description-key"?: LoomiAttributeValue;
  "autocomplete-image-key"?: LoomiAttributeValue;
  "autocomplete-label-key"?: LoomiAttributeValue;
  "autocomplete-value-key"?: LoomiAttributeValue;
  "error-message"?: LoomiAttributeValue;
  "label-position"?: LoomiAttributeValue;
  "show-error-inline"?: LoomiAttributeValue;
  "show-focus-ring"?: LoomiAttributeValue;
  "suffix-icon"?: LoomiAttributeValue;
}

interface LoomiTagsAttributes {
  "selected-value"?: LoomiAttributeValue;
}

interface LoomiTextEditorAttributes {
  "error-message"?: LoomiAttributeValue;
  "label-position"?: LoomiAttributeValue;
  "no-file-upload"?: LoomiAttributeValue;
  "show-error-inline"?: LoomiAttributeValue;
}

interface LoomiTextareaAttributes {
  "error-message"?: LoomiAttributeValue;
  "label-position"?: LoomiAttributeValue;
  "mention-data"?: LoomiAttributeValue;
  "mention-triggers"?: LoomiAttributeValue;
  "show-error-inline"?: LoomiAttributeValue;
  "show-focus-ring"?: LoomiAttributeValue;
}

interface LoomiThemeSwitcherAttributes {
  "dark-icon"?: LoomiAttributeValue;
  "dark-text"?: LoomiAttributeValue;
  "icon-right"?: LoomiAttributeValue;
  "light-icon"?: LoomiAttributeValue;
  "light-text"?: LoomiAttributeValue;
  "show-labels"?: LoomiAttributeValue;
  "system-icon"?: LoomiAttributeValue;
  "system-text"?: LoomiAttributeValue;
}

interface LoomiTimelineAttributes {}

interface LoomiTimelineItemAttributes {}

interface LoomiTimepickerAttributes {
  "label-position"?: LoomiAttributeValue;
  "selected-value"?: LoomiAttributeValue;
  "show-focus-ring"?: LoomiAttributeValue;
  "tp-style"?: LoomiAttributeValue;
}

interface LoomiTimerAttributes {
  "auto-start"?: LoomiAttributeValue;
  "show-border"?: LoomiAttributeValue;
  "show-controls"?: LoomiAttributeValue;
  "start-value"?: LoomiAttributeValue;
}

interface LoomiTimezonepickerAttributes {
  "empty-placeholder"?: LoomiAttributeValue;
  "label-position"?: LoomiAttributeValue;
}

interface LoomiToggleAttributes {
  "label-position"?: LoomiAttributeValue;
}

interface LoomiTooltipAttributes {}

interface LoomiVideoAttributes {
  "aspect-ratio"?: LoomiAttributeValue;
  "autohide-controls"?: LoomiAttributeValue;
  "disable-fullscreen"?: LoomiAttributeValue;
  "disable-pip"?: LoomiAttributeValue;
}

declare module "react" {
  namespace JSX {
    interface IntrinsicElements {
      "loomi-accordion": LoomiReactProps<
        HTMLElementTagNameMap["loomi-accordion"],
        LoomiAccordionAttributes
      >;
      "loomi-accordion-item": LoomiReactProps<
        HTMLElementTagNameMap["loomi-accordion-item"],
        LoomiAccordionItemAttributes
      >;
      "loomi-alert": LoomiReactProps<HTMLElementTagNameMap["loomi-alert"], LoomiAlertAttributes>;
      "loomi-arc-meter": LoomiReactProps<
        HTMLElementTagNameMap["loomi-arc-meter"],
        LoomiArcMeterAttributes
      >;
      "loomi-autocomplete": LoomiReactProps<
        HTMLElementTagNameMap["loomi-autocomplete"],
        LoomiAutocompleteAttributes
      >;
      "loomi-avatar": LoomiReactProps<HTMLElementTagNameMap["loomi-avatar"], LoomiAvatarAttributes>;
      "loomi-avatars": LoomiReactProps<
        HTMLElementTagNameMap["loomi-avatars"],
        LoomiAvatarsAttributes
      >;
      "loomi-bell": LoomiReactProps<HTMLElementTagNameMap["loomi-bell"], LoomiBellAttributes>;
      "loomi-bottom-nav": LoomiReactProps<
        HTMLElementTagNameMap["loomi-bottom-nav"],
        LoomiBottomNavAttributes
      >;
      "loomi-bottom-nav-item": LoomiReactProps<
        HTMLElementTagNameMap["loomi-bottom-nav-item"],
        LoomiBottomNavItemAttributes
      >;
      "loomi-button": LoomiReactProps<HTMLElementTagNameMap["loomi-button"], LoomiButtonAttributes>;
      "loomi-button-group": LoomiReactProps<
        HTMLElementTagNameMap["loomi-button-group"],
        LoomiButtonGroupAttributes
      >;
      "loomi-button-group-item": LoomiReactProps<
        HTMLElementTagNameMap["loomi-button-group-item"],
        LoomiButtonGroupItemAttributes
      >;
      "loomi-calendar": LoomiReactProps<
        HTMLElementTagNameMap["loomi-calendar"],
        LoomiCalendarAttributes
      >;
      "loomi-card": LoomiReactProps<HTMLElementTagNameMap["loomi-card"], LoomiCardAttributes>;
      "loomi-card-action": LoomiReactProps<
        HTMLElementTagNameMap["loomi-card-action"],
        LoomiCardActionAttributes
      >;
      "loomi-card-content": LoomiReactProps<
        HTMLElementTagNameMap["loomi-card-content"],
        LoomiCardContentAttributes
      >;
      "loomi-card-description": LoomiReactProps<
        HTMLElementTagNameMap["loomi-card-description"],
        LoomiCardDescriptionAttributes
      >;
      "loomi-card-footer": LoomiReactProps<
        HTMLElementTagNameMap["loomi-card-footer"],
        LoomiCardFooterAttributes
      >;
      "loomi-card-header": LoomiReactProps<
        HTMLElementTagNameMap["loomi-card-header"],
        LoomiCardHeaderAttributes
      >;
      "loomi-card-title": LoomiReactProps<
        HTMLElementTagNameMap["loomi-card-title"],
        LoomiCardTitleAttributes
      >;
      "loomi-centered-content": LoomiReactProps<
        HTMLElementTagNameMap["loomi-centered-content"],
        LoomiCenteredContentAttributes
      >;
      "loomi-chart": LoomiReactProps<HTMLElementTagNameMap["loomi-chart"], LoomiChartAttributes>;
      "loomi-chat-message": LoomiReactProps<
        HTMLElementTagNameMap["loomi-chat-message"],
        LoomiChatMessageAttributes
      >;
      "loomi-chat-window": LoomiReactProps<
        HTMLElementTagNameMap["loomi-chat-window"],
        LoomiChatWindowAttributes
      >;
      "loomi-checkbox": LoomiReactProps<
        HTMLElementTagNameMap["loomi-checkbox"],
        LoomiCheckboxAttributes
      >;
      "loomi-checkcard": LoomiReactProps<
        HTMLElementTagNameMap["loomi-checkcard"],
        LoomiCheckcardAttributes
      >;
      "loomi-checkcards": LoomiReactProps<
        HTMLElementTagNameMap["loomi-checkcards"],
        LoomiCheckcardsAttributes
      >;
      "loomi-clipboard": LoomiReactProps<
        HTMLElementTagNameMap["loomi-clipboard"],
        LoomiClipboardAttributes
      >;
      "loomi-colorpicker": LoomiReactProps<
        HTMLElementTagNameMap["loomi-colorpicker"],
        LoomiColorpickerAttributes
      >;
      "loomi-command-palette": LoomiReactProps<
        HTMLElementTagNameMap["loomi-command-palette"],
        LoomiCommandPaletteAttributes
      >;
      "loomi-contact-card": LoomiReactProps<
        HTMLElementTagNameMap["loomi-contact-card"],
        LoomiContactCardAttributes
      >;
      "loomi-context-menu": LoomiReactProps<
        HTMLElementTagNameMap["loomi-context-menu"],
        LoomiContextMenuAttributes
      >;
      "loomi-context-menu-item": LoomiReactProps<
        HTMLElementTagNameMap["loomi-context-menu-item"],
        LoomiContextMenuItemAttributes
      >;
      "loomi-countries": LoomiReactProps<
        HTMLElementTagNameMap["loomi-countries"],
        LoomiCountriesAttributes
      >;
      "loomi-creditcard": LoomiReactProps<
        HTMLElementTagNameMap["loomi-creditcard"],
        LoomiCreditcardAttributes
      >;
      "loomi-data-grid": LoomiReactProps<
        HTMLElementTagNameMap["loomi-data-grid"],
        LoomiDataGridAttributes
      >;
      "loomi-date-range-picker": LoomiReactProps<
        HTMLElementTagNameMap["loomi-date-range-picker"],
        LoomiDateRangePickerAttributes
      >;
      "loomi-datepicker": LoomiReactProps<
        HTMLElementTagNameMap["loomi-datepicker"],
        LoomiDatepickerAttributes
      >;
      "loomi-divider": LoomiReactProps<
        HTMLElementTagNameMap["loomi-divider"],
        LoomiDividerAttributes
      >;
      "loomi-drawer": LoomiReactProps<HTMLElementTagNameMap["loomi-drawer"], LoomiDrawerAttributes>;
      "loomi-dropmenu": LoomiReactProps<
        HTMLElementTagNameMap["loomi-dropmenu"],
        LoomiDropmenuAttributes
      >;
      "loomi-dropmenu-item": LoomiReactProps<
        HTMLElementTagNameMap["loomi-dropmenu-item"],
        LoomiDropmenuItemAttributes
      >;
      "loomi-emoji-picker": LoomiReactProps<
        HTMLElementTagNameMap["loomi-emoji-picker"],
        LoomiEmojiPickerAttributes
      >;
      "loomi-empty-state": LoomiReactProps<
        HTMLElementTagNameMap["loomi-empty-state"],
        LoomiEmptyStateAttributes
      >;
      "loomi-fab": LoomiReactProps<HTMLElementTagNameMap["loomi-fab"], LoomiFabAttributes>;
      "loomi-fab-item": LoomiReactProps<
        HTMLElementTagNameMap["loomi-fab-item"],
        LoomiFabItemAttributes
      >;
      "loomi-filepicker": LoomiReactProps<
        HTMLElementTagNameMap["loomi-filepicker"],
        LoomiFilepickerAttributes
      >;
      "loomi-filter-builder": LoomiReactProps<
        HTMLElementTagNameMap["loomi-filter-builder"],
        LoomiFilterBuilderAttributes
      >;
      "loomi-floating-panel": LoomiReactProps<
        HTMLElementTagNameMap["loomi-floating-panel"],
        LoomiFloatingPanelAttributes
      >;
      "loomi-horizontal-line-graph": LoomiReactProps<
        HTMLElementTagNameMap["loomi-horizontal-line-graph"],
        LoomiHorizontalLineGraphAttributes
      >;
      "loomi-icon": LoomiReactProps<HTMLElementTagNameMap["loomi-icon"], LoomiIconAttributes>;
      "loomi-input": LoomiReactProps<HTMLElementTagNameMap["loomi-input"], LoomiInputAttributes>;
      "loomi-lightbox-image": LoomiReactProps<
        HTMLElementTagNameMap["loomi-lightbox-image"],
        LoomiLightboxImageAttributes
      >;
      "loomi-listview": LoomiReactProps<
        HTMLElementTagNameMap["loomi-listview"],
        LoomiListviewAttributes
      >;
      "loomi-listview-item": LoomiReactProps<
        HTMLElementTagNameMap["loomi-listview-item"],
        LoomiListviewItemAttributes
      >;
      "loomi-modal": LoomiReactProps<HTMLElementTagNameMap["loomi-modal"], LoomiModalAttributes>;
      "loomi-notification": LoomiReactProps<
        HTMLElementTagNameMap["loomi-notification"],
        LoomiNotificationAttributes
      >;
      "loomi-number": LoomiReactProps<HTMLElementTagNameMap["loomi-number"], LoomiNumberAttributes>;
      "loomi-otp": LoomiReactProps<HTMLElementTagNameMap["loomi-otp"], LoomiOtpAttributes>;
      "loomi-pagination": LoomiReactProps<
        HTMLElementTagNameMap["loomi-pagination"],
        LoomiPaginationAttributes
      >;
      "loomi-password": LoomiReactProps<
        HTMLElementTagNameMap["loomi-password"],
        LoomiPasswordAttributes
      >;
      "loomi-photo-gallery": LoomiReactProps<
        HTMLElementTagNameMap["loomi-photo-gallery"],
        LoomiPhotoGalleryAttributes
      >;
      "loomi-photo-gallery-item": LoomiReactProps<
        HTMLElementTagNameMap["loomi-photo-gallery-item"],
        LoomiPhotoGalleryItemAttributes
      >;
      "loomi-popover": LoomiReactProps<
        HTMLElementTagNameMap["loomi-popover"],
        LoomiPopoverAttributes
      >;
      "loomi-processing": LoomiReactProps<
        HTMLElementTagNameMap["loomi-processing"],
        LoomiProcessingAttributes
      >;
      "loomi-profile-menu": LoomiReactProps<
        HTMLElementTagNameMap["loomi-profile-menu"],
        LoomiProfileMenuAttributes
      >;
      "loomi-progress-bar": LoomiReactProps<
        HTMLElementTagNameMap["loomi-progress-bar"],
        LoomiProgressBarAttributes
      >;
      "loomi-progress-circle": LoomiReactProps<
        HTMLElementTagNameMap["loomi-progress-circle"],
        LoomiProgressCircleAttributes
      >;
      "loomi-progress-step": LoomiReactProps<
        HTMLElementTagNameMap["loomi-progress-step"],
        LoomiProgressStepAttributes
      >;
      "loomi-progress-steps": LoomiReactProps<
        HTMLElementTagNameMap["loomi-progress-steps"],
        LoomiProgressStepsAttributes
      >;
      "loomi-qrcode": LoomiReactProps<HTMLElementTagNameMap["loomi-qrcode"], LoomiQrcodeAttributes>;
      "loomi-radio": LoomiReactProps<HTMLElementTagNameMap["loomi-radio"], LoomiRadioAttributes>;
      "loomi-rating": LoomiReactProps<HTMLElementTagNameMap["loomi-rating"], LoomiRatingAttributes>;
      "loomi-resizable-handle": LoomiReactProps<
        HTMLElementTagNameMap["loomi-resizable-handle"],
        LoomiResizableHandleAttributes
      >;
      "loomi-resizable-panel": LoomiReactProps<
        HTMLElementTagNameMap["loomi-resizable-panel"],
        LoomiResizablePanelAttributes
      >;
      "loomi-resizable-panel-group": LoomiReactProps<
        HTMLElementTagNameMap["loomi-resizable-panel-group"],
        LoomiResizablePanelGroupAttributes
      >;
      "loomi-scroller": LoomiReactProps<
        HTMLElementTagNameMap["loomi-scroller"],
        LoomiScrollerAttributes
      >;
      "loomi-select": LoomiReactProps<HTMLElementTagNameMap["loomi-select"], LoomiSelectAttributes>;
      "loomi-side-nav": LoomiReactProps<
        HTMLElementTagNameMap["loomi-side-nav"],
        LoomiSideNavAttributes
      >;
      "loomi-side-nav-item": LoomiReactProps<
        HTMLElementTagNameMap["loomi-side-nav-item"],
        LoomiSideNavItemAttributes
      >;
      "loomi-slider": LoomiReactProps<HTMLElementTagNameMap["loomi-slider"], LoomiSliderAttributes>;
      "loomi-sortable": LoomiReactProps<
        HTMLElementTagNameMap["loomi-sortable"],
        LoomiSortableAttributes
      >;
      "loomi-spinner": LoomiReactProps<
        HTMLElementTagNameMap["loomi-spinner"],
        LoomiSpinnerAttributes
      >;
      "loomi-split-button": LoomiReactProps<
        HTMLElementTagNameMap["loomi-split-button"],
        LoomiSplitButtonAttributes
      >;
      "loomi-statistic": LoomiReactProps<
        HTMLElementTagNameMap["loomi-statistic"],
        LoomiStatisticAttributes
      >;
      "loomi-tab": LoomiReactProps<HTMLElementTagNameMap["loomi-tab"], LoomiTabAttributes>;
      "loomi-table": LoomiReactProps<HTMLElementTagNameMap["loomi-table"], LoomiTableAttributes>;
      "loomi-tabs": LoomiReactProps<HTMLElementTagNameMap["loomi-tabs"], LoomiTabsAttributes>;
      "loomi-tag": LoomiReactProps<HTMLElementTagNameMap["loomi-tag"], LoomiTagAttributes>;
      "loomi-tag-input": LoomiReactProps<
        HTMLElementTagNameMap["loomi-tag-input"],
        LoomiTagInputAttributes
      >;
      "loomi-tags": LoomiReactProps<HTMLElementTagNameMap["loomi-tags"], LoomiTagsAttributes>;
      "loomi-text-editor": LoomiReactProps<
        HTMLElementTagNameMap["loomi-text-editor"],
        LoomiTextEditorAttributes
      >;
      "loomi-textarea": LoomiReactProps<
        HTMLElementTagNameMap["loomi-textarea"],
        LoomiTextareaAttributes
      >;
      "loomi-theme-switcher": LoomiReactProps<
        HTMLElementTagNameMap["loomi-theme-switcher"],
        LoomiThemeSwitcherAttributes
      >;
      "loomi-timeline": LoomiReactProps<
        HTMLElementTagNameMap["loomi-timeline"],
        LoomiTimelineAttributes
      >;
      "loomi-timeline-item": LoomiReactProps<
        HTMLElementTagNameMap["loomi-timeline-item"],
        LoomiTimelineItemAttributes
      >;
      "loomi-timepicker": LoomiReactProps<
        HTMLElementTagNameMap["loomi-timepicker"],
        LoomiTimepickerAttributes
      >;
      "loomi-timer": LoomiReactProps<HTMLElementTagNameMap["loomi-timer"], LoomiTimerAttributes>;
      "loomi-timezonepicker": LoomiReactProps<
        HTMLElementTagNameMap["loomi-timezonepicker"],
        LoomiTimezonepickerAttributes
      >;
      "loomi-toggle": LoomiReactProps<HTMLElementTagNameMap["loomi-toggle"], LoomiToggleAttributes>;
      "loomi-tooltip": LoomiReactProps<
        HTMLElementTagNameMap["loomi-tooltip"],
        LoomiTooltipAttributes
      >;
      "loomi-video": LoomiReactProps<HTMLElementTagNameMap["loomi-video"], LoomiVideoAttributes>;
    }
  }
}

declare global {
  namespace JSX {
    interface IntrinsicElements {
      "loomi-accordion": LoomiReactProps<
        HTMLElementTagNameMap["loomi-accordion"],
        LoomiAccordionAttributes
      >;
      "loomi-accordion-item": LoomiReactProps<
        HTMLElementTagNameMap["loomi-accordion-item"],
        LoomiAccordionItemAttributes
      >;
      "loomi-alert": LoomiReactProps<HTMLElementTagNameMap["loomi-alert"], LoomiAlertAttributes>;
      "loomi-arc-meter": LoomiReactProps<
        HTMLElementTagNameMap["loomi-arc-meter"],
        LoomiArcMeterAttributes
      >;
      "loomi-autocomplete": LoomiReactProps<
        HTMLElementTagNameMap["loomi-autocomplete"],
        LoomiAutocompleteAttributes
      >;
      "loomi-avatar": LoomiReactProps<HTMLElementTagNameMap["loomi-avatar"], LoomiAvatarAttributes>;
      "loomi-avatars": LoomiReactProps<
        HTMLElementTagNameMap["loomi-avatars"],
        LoomiAvatarsAttributes
      >;
      "loomi-bell": LoomiReactProps<HTMLElementTagNameMap["loomi-bell"], LoomiBellAttributes>;
      "loomi-bottom-nav": LoomiReactProps<
        HTMLElementTagNameMap["loomi-bottom-nav"],
        LoomiBottomNavAttributes
      >;
      "loomi-bottom-nav-item": LoomiReactProps<
        HTMLElementTagNameMap["loomi-bottom-nav-item"],
        LoomiBottomNavItemAttributes
      >;
      "loomi-button": LoomiReactProps<HTMLElementTagNameMap["loomi-button"], LoomiButtonAttributes>;
      "loomi-button-group": LoomiReactProps<
        HTMLElementTagNameMap["loomi-button-group"],
        LoomiButtonGroupAttributes
      >;
      "loomi-button-group-item": LoomiReactProps<
        HTMLElementTagNameMap["loomi-button-group-item"],
        LoomiButtonGroupItemAttributes
      >;
      "loomi-calendar": LoomiReactProps<
        HTMLElementTagNameMap["loomi-calendar"],
        LoomiCalendarAttributes
      >;
      "loomi-card": LoomiReactProps<HTMLElementTagNameMap["loomi-card"], LoomiCardAttributes>;
      "loomi-card-action": LoomiReactProps<
        HTMLElementTagNameMap["loomi-card-action"],
        LoomiCardActionAttributes
      >;
      "loomi-card-content": LoomiReactProps<
        HTMLElementTagNameMap["loomi-card-content"],
        LoomiCardContentAttributes
      >;
      "loomi-card-description": LoomiReactProps<
        HTMLElementTagNameMap["loomi-card-description"],
        LoomiCardDescriptionAttributes
      >;
      "loomi-card-footer": LoomiReactProps<
        HTMLElementTagNameMap["loomi-card-footer"],
        LoomiCardFooterAttributes
      >;
      "loomi-card-header": LoomiReactProps<
        HTMLElementTagNameMap["loomi-card-header"],
        LoomiCardHeaderAttributes
      >;
      "loomi-card-title": LoomiReactProps<
        HTMLElementTagNameMap["loomi-card-title"],
        LoomiCardTitleAttributes
      >;
      "loomi-centered-content": LoomiReactProps<
        HTMLElementTagNameMap["loomi-centered-content"],
        LoomiCenteredContentAttributes
      >;
      "loomi-chart": LoomiReactProps<HTMLElementTagNameMap["loomi-chart"], LoomiChartAttributes>;
      "loomi-chat-message": LoomiReactProps<
        HTMLElementTagNameMap["loomi-chat-message"],
        LoomiChatMessageAttributes
      >;
      "loomi-chat-window": LoomiReactProps<
        HTMLElementTagNameMap["loomi-chat-window"],
        LoomiChatWindowAttributes
      >;
      "loomi-checkbox": LoomiReactProps<
        HTMLElementTagNameMap["loomi-checkbox"],
        LoomiCheckboxAttributes
      >;
      "loomi-checkcard": LoomiReactProps<
        HTMLElementTagNameMap["loomi-checkcard"],
        LoomiCheckcardAttributes
      >;
      "loomi-checkcards": LoomiReactProps<
        HTMLElementTagNameMap["loomi-checkcards"],
        LoomiCheckcardsAttributes
      >;
      "loomi-clipboard": LoomiReactProps<
        HTMLElementTagNameMap["loomi-clipboard"],
        LoomiClipboardAttributes
      >;
      "loomi-colorpicker": LoomiReactProps<
        HTMLElementTagNameMap["loomi-colorpicker"],
        LoomiColorpickerAttributes
      >;
      "loomi-command-palette": LoomiReactProps<
        HTMLElementTagNameMap["loomi-command-palette"],
        LoomiCommandPaletteAttributes
      >;
      "loomi-contact-card": LoomiReactProps<
        HTMLElementTagNameMap["loomi-contact-card"],
        LoomiContactCardAttributes
      >;
      "loomi-context-menu": LoomiReactProps<
        HTMLElementTagNameMap["loomi-context-menu"],
        LoomiContextMenuAttributes
      >;
      "loomi-context-menu-item": LoomiReactProps<
        HTMLElementTagNameMap["loomi-context-menu-item"],
        LoomiContextMenuItemAttributes
      >;
      "loomi-countries": LoomiReactProps<
        HTMLElementTagNameMap["loomi-countries"],
        LoomiCountriesAttributes
      >;
      "loomi-creditcard": LoomiReactProps<
        HTMLElementTagNameMap["loomi-creditcard"],
        LoomiCreditcardAttributes
      >;
      "loomi-data-grid": LoomiReactProps<
        HTMLElementTagNameMap["loomi-data-grid"],
        LoomiDataGridAttributes
      >;
      "loomi-date-range-picker": LoomiReactProps<
        HTMLElementTagNameMap["loomi-date-range-picker"],
        LoomiDateRangePickerAttributes
      >;
      "loomi-datepicker": LoomiReactProps<
        HTMLElementTagNameMap["loomi-datepicker"],
        LoomiDatepickerAttributes
      >;
      "loomi-divider": LoomiReactProps<
        HTMLElementTagNameMap["loomi-divider"],
        LoomiDividerAttributes
      >;
      "loomi-drawer": LoomiReactProps<HTMLElementTagNameMap["loomi-drawer"], LoomiDrawerAttributes>;
      "loomi-dropmenu": LoomiReactProps<
        HTMLElementTagNameMap["loomi-dropmenu"],
        LoomiDropmenuAttributes
      >;
      "loomi-dropmenu-item": LoomiReactProps<
        HTMLElementTagNameMap["loomi-dropmenu-item"],
        LoomiDropmenuItemAttributes
      >;
      "loomi-emoji-picker": LoomiReactProps<
        HTMLElementTagNameMap["loomi-emoji-picker"],
        LoomiEmojiPickerAttributes
      >;
      "loomi-empty-state": LoomiReactProps<
        HTMLElementTagNameMap["loomi-empty-state"],
        LoomiEmptyStateAttributes
      >;
      "loomi-fab": LoomiReactProps<HTMLElementTagNameMap["loomi-fab"], LoomiFabAttributes>;
      "loomi-fab-item": LoomiReactProps<
        HTMLElementTagNameMap["loomi-fab-item"],
        LoomiFabItemAttributes
      >;
      "loomi-filepicker": LoomiReactProps<
        HTMLElementTagNameMap["loomi-filepicker"],
        LoomiFilepickerAttributes
      >;
      "loomi-filter-builder": LoomiReactProps<
        HTMLElementTagNameMap["loomi-filter-builder"],
        LoomiFilterBuilderAttributes
      >;
      "loomi-floating-panel": LoomiReactProps<
        HTMLElementTagNameMap["loomi-floating-panel"],
        LoomiFloatingPanelAttributes
      >;
      "loomi-horizontal-line-graph": LoomiReactProps<
        HTMLElementTagNameMap["loomi-horizontal-line-graph"],
        LoomiHorizontalLineGraphAttributes
      >;
      "loomi-icon": LoomiReactProps<HTMLElementTagNameMap["loomi-icon"], LoomiIconAttributes>;
      "loomi-input": LoomiReactProps<HTMLElementTagNameMap["loomi-input"], LoomiInputAttributes>;
      "loomi-lightbox-image": LoomiReactProps<
        HTMLElementTagNameMap["loomi-lightbox-image"],
        LoomiLightboxImageAttributes
      >;
      "loomi-listview": LoomiReactProps<
        HTMLElementTagNameMap["loomi-listview"],
        LoomiListviewAttributes
      >;
      "loomi-listview-item": LoomiReactProps<
        HTMLElementTagNameMap["loomi-listview-item"],
        LoomiListviewItemAttributes
      >;
      "loomi-modal": LoomiReactProps<HTMLElementTagNameMap["loomi-modal"], LoomiModalAttributes>;
      "loomi-notification": LoomiReactProps<
        HTMLElementTagNameMap["loomi-notification"],
        LoomiNotificationAttributes
      >;
      "loomi-number": LoomiReactProps<HTMLElementTagNameMap["loomi-number"], LoomiNumberAttributes>;
      "loomi-otp": LoomiReactProps<HTMLElementTagNameMap["loomi-otp"], LoomiOtpAttributes>;
      "loomi-pagination": LoomiReactProps<
        HTMLElementTagNameMap["loomi-pagination"],
        LoomiPaginationAttributes
      >;
      "loomi-password": LoomiReactProps<
        HTMLElementTagNameMap["loomi-password"],
        LoomiPasswordAttributes
      >;
      "loomi-photo-gallery": LoomiReactProps<
        HTMLElementTagNameMap["loomi-photo-gallery"],
        LoomiPhotoGalleryAttributes
      >;
      "loomi-photo-gallery-item": LoomiReactProps<
        HTMLElementTagNameMap["loomi-photo-gallery-item"],
        LoomiPhotoGalleryItemAttributes
      >;
      "loomi-popover": LoomiReactProps<
        HTMLElementTagNameMap["loomi-popover"],
        LoomiPopoverAttributes
      >;
      "loomi-processing": LoomiReactProps<
        HTMLElementTagNameMap["loomi-processing"],
        LoomiProcessingAttributes
      >;
      "loomi-profile-menu": LoomiReactProps<
        HTMLElementTagNameMap["loomi-profile-menu"],
        LoomiProfileMenuAttributes
      >;
      "loomi-progress-bar": LoomiReactProps<
        HTMLElementTagNameMap["loomi-progress-bar"],
        LoomiProgressBarAttributes
      >;
      "loomi-progress-circle": LoomiReactProps<
        HTMLElementTagNameMap["loomi-progress-circle"],
        LoomiProgressCircleAttributes
      >;
      "loomi-progress-step": LoomiReactProps<
        HTMLElementTagNameMap["loomi-progress-step"],
        LoomiProgressStepAttributes
      >;
      "loomi-progress-steps": LoomiReactProps<
        HTMLElementTagNameMap["loomi-progress-steps"],
        LoomiProgressStepsAttributes
      >;
      "loomi-qrcode": LoomiReactProps<HTMLElementTagNameMap["loomi-qrcode"], LoomiQrcodeAttributes>;
      "loomi-radio": LoomiReactProps<HTMLElementTagNameMap["loomi-radio"], LoomiRadioAttributes>;
      "loomi-rating": LoomiReactProps<HTMLElementTagNameMap["loomi-rating"], LoomiRatingAttributes>;
      "loomi-resizable-handle": LoomiReactProps<
        HTMLElementTagNameMap["loomi-resizable-handle"],
        LoomiResizableHandleAttributes
      >;
      "loomi-resizable-panel": LoomiReactProps<
        HTMLElementTagNameMap["loomi-resizable-panel"],
        LoomiResizablePanelAttributes
      >;
      "loomi-resizable-panel-group": LoomiReactProps<
        HTMLElementTagNameMap["loomi-resizable-panel-group"],
        LoomiResizablePanelGroupAttributes
      >;
      "loomi-scroller": LoomiReactProps<
        HTMLElementTagNameMap["loomi-scroller"],
        LoomiScrollerAttributes
      >;
      "loomi-select": LoomiReactProps<HTMLElementTagNameMap["loomi-select"], LoomiSelectAttributes>;
      "loomi-side-nav": LoomiReactProps<
        HTMLElementTagNameMap["loomi-side-nav"],
        LoomiSideNavAttributes
      >;
      "loomi-side-nav-item": LoomiReactProps<
        HTMLElementTagNameMap["loomi-side-nav-item"],
        LoomiSideNavItemAttributes
      >;
      "loomi-slider": LoomiReactProps<HTMLElementTagNameMap["loomi-slider"], LoomiSliderAttributes>;
      "loomi-sortable": LoomiReactProps<
        HTMLElementTagNameMap["loomi-sortable"],
        LoomiSortableAttributes
      >;
      "loomi-spinner": LoomiReactProps<
        HTMLElementTagNameMap["loomi-spinner"],
        LoomiSpinnerAttributes
      >;
      "loomi-split-button": LoomiReactProps<
        HTMLElementTagNameMap["loomi-split-button"],
        LoomiSplitButtonAttributes
      >;
      "loomi-statistic": LoomiReactProps<
        HTMLElementTagNameMap["loomi-statistic"],
        LoomiStatisticAttributes
      >;
      "loomi-tab": LoomiReactProps<HTMLElementTagNameMap["loomi-tab"], LoomiTabAttributes>;
      "loomi-table": LoomiReactProps<HTMLElementTagNameMap["loomi-table"], LoomiTableAttributes>;
      "loomi-tabs": LoomiReactProps<HTMLElementTagNameMap["loomi-tabs"], LoomiTabsAttributes>;
      "loomi-tag": LoomiReactProps<HTMLElementTagNameMap["loomi-tag"], LoomiTagAttributes>;
      "loomi-tag-input": LoomiReactProps<
        HTMLElementTagNameMap["loomi-tag-input"],
        LoomiTagInputAttributes
      >;
      "loomi-tags": LoomiReactProps<HTMLElementTagNameMap["loomi-tags"], LoomiTagsAttributes>;
      "loomi-text-editor": LoomiReactProps<
        HTMLElementTagNameMap["loomi-text-editor"],
        LoomiTextEditorAttributes
      >;
      "loomi-textarea": LoomiReactProps<
        HTMLElementTagNameMap["loomi-textarea"],
        LoomiTextareaAttributes
      >;
      "loomi-theme-switcher": LoomiReactProps<
        HTMLElementTagNameMap["loomi-theme-switcher"],
        LoomiThemeSwitcherAttributes
      >;
      "loomi-timeline": LoomiReactProps<
        HTMLElementTagNameMap["loomi-timeline"],
        LoomiTimelineAttributes
      >;
      "loomi-timeline-item": LoomiReactProps<
        HTMLElementTagNameMap["loomi-timeline-item"],
        LoomiTimelineItemAttributes
      >;
      "loomi-timepicker": LoomiReactProps<
        HTMLElementTagNameMap["loomi-timepicker"],
        LoomiTimepickerAttributes
      >;
      "loomi-timer": LoomiReactProps<HTMLElementTagNameMap["loomi-timer"], LoomiTimerAttributes>;
      "loomi-timezonepicker": LoomiReactProps<
        HTMLElementTagNameMap["loomi-timezonepicker"],
        LoomiTimezonepickerAttributes
      >;
      "loomi-toggle": LoomiReactProps<HTMLElementTagNameMap["loomi-toggle"], LoomiToggleAttributes>;
      "loomi-tooltip": LoomiReactProps<
        HTMLElementTagNameMap["loomi-tooltip"],
        LoomiTooltipAttributes
      >;
      "loomi-video": LoomiReactProps<HTMLElementTagNameMap["loomi-video"], LoomiVideoAttributes>;
    }
  }
}
